class AnkletsExec
{
	public static void main(String[] args)
	{
		Anklets a1 = new Anklets();
		a1.brand="GRT";
		System.out.println("The brand is "+a1.brand);
		a1.cost=2000;
		System.out.println("The cost is "+a1.cost);
		a1.material="Silver";
		System.out.println("The material is "+a1.material);
		a1.colour="Silver";
		System.out.println("The colour is "+a1.colour);
		a1.type="Traditional";
		System.out.println("The type is "+a1.type);
		a1.length=24;
		System.out.println("The length is "+a1.length);
		a1.isAdjustable=true;
		System.out.println("Adjustable: "+a1.isAdjustable);
		a1.design="Chain";
		System.out.println("The design is "+a1.design);

		Anklets a2 = new Anklets();
		a2.brand="Tanishq";
		System.out.println("The brand is "+a2.brand);
		a2.cost=3500;
		System.out.println("The cost is "+a2.cost);
		a2.material="Silver";
		System.out.println("The material is "+a2.material);
		a2.colour="Silver";
		System.out.println("The colour is "+a2.colour);
		a2.type="Casual";
		System.out.println("The type is "+a2.type);
		a2.length=23;
		System.out.println("The length is "+a2.length);
		a2.isAdjustable=false;
		System.out.println("Adjustable: "+a2.isAdjustable);
		a2.design="Plain";
		System.out.println("The design is "+a2.design);

		Anklets a3 = new Anklets();
		a3.brand="Kalyan";
		System.out.println("The brand is "+a3.brand);
		a3.cost=4000;
		System.out.println("The cost is "+a3.cost);
		a3.material="Silver";
		System.out.println("The material is "+a3.material);
		a3.colour="Silver";
		System.out.println("The colour is "+a3.colour);
		a3.type="Party";
		System.out.println("The type is "+a3.type);
		a3.length=25;
		System.out.println("The length is "+a3.length);
		a3.isAdjustable=true;
		System.out.println("Adjustable: "+a3.isAdjustable);
		a3.design="Stone";
		System.out.println("The design is "+a3.design);

		Anklets a4 = new Anklets();
		a4.brand="Malabar";
		System.out.println("The brand is "+a4.brand);
		a4.cost=2800;
		System.out.println("The cost is "+a4.cost);
		a4.material="Silver";
		System.out.println("The material is "+a4.material);
		a4.colour="Silver";
		System.out.println("The colour is "+a4.colour);
		a4.type="Traditional";
		System.out.println("The type is "+a4.type);
		a4.length=24;
		System.out.println("The length is "+a4.length);
		a4.isAdjustable=false;
		System.out.println("Adjustable: "+a4.isAdjustable);
		a4.design="Chain";
		System.out.println("The design is "+a4.design);

		Anklets a5 = new Anklets();
		a5.brand="Joyalukkas";
		System.out.println("The brand is "+a5.brand);
		a5.cost=3200;
		System.out.println("The cost is "+a5.cost);
		a5.material="Silver";
		System.out.println("The material is "+a5.material);
		a5.colour="Silver";
		System.out.println("The colour is "+a5.colour);
		a5.type="Casual";
		System.out.println("The type is "+a5.type);
		a5.length=23;
		System.out.println("The length is "+a5.length);
		a5.isAdjustable=true;
		System.out.println("Adjustable: "+a5.isAdjustable);
		a5.design="Beads";
		System.out.println("The design is "+a5.design);

		Anklets a6 = new Anklets();
		a6.brand="Bluestone";
		System.out.println("The brand is "+a6.brand);
		a6.cost=4500;
		System.out.println("The cost is "+a6.cost);
		a6.material="Silver";
		System.out.println("The material is "+a6.material);
		a6.colour="Silver";
		System.out.println("The colour is "+a6.colour);
		a6.type="Party";
		System.out.println("The type is "+a6.type);
		a6.length=26;
		System.out.println("The length is "+a6.length);
		a6.isAdjustable=false;
		System.out.println("Adjustable: "+a6.isAdjustable);
		a6.design="Stone";
		System.out.println("The design is "+a6.design);

		Anklets a7 = new Anklets();
		a7.brand="CaratLane";
		System.out.println("The brand is "+a7.brand);
		a7.cost=3800;
		System.out.println("The cost is "+a7.cost);
		a7.material="Silver";
		System.out.println("The material is "+a7.material);
		a7.colour="Silver";
		System.out.println("The colour is "+a7.colour);
		a7.type="Traditional";
		System.out.println("The type is "+a7.type);
		a7.length=24;
		System.out.println("The length is "+a7.length);
		a7.isAdjustable=true;
		System.out.println("Adjustable: "+a7.isAdjustable);
		a7.design="Chain";
		System.out.println("The design is "+a7.design);

		Anklets a8 = new Anklets();
		a8.brand="Reliance";
		System.out.println("The brand is "+a8.brand);
		a8.cost=2600;
		System.out.println("The cost is "+a8.cost);
		a8.material="Silver";
		System.out.println("The material is "+a8.material);
		a8.colour="Silver";
		System.out.println("The colour is "+a8.colour);
		a8.type="Casual";
		System.out.println("The type is "+a8.type);
		a8.length=22;
		System.out.println("The length is "+a8.length);
		a8.isAdjustable=true;
		System.out.println("Adjustable: "+a8.isAdjustable);
		a8.design="Plain";
		System.out.println("The design is "+a8.design);

		Anklets a9 = new Anklets();
		a9.brand="Senco";
		System.out.println("The brand is "+a9.brand);
		a9.cost=4100;
		System.out.println("The cost is "+a9.cost);
		a9.material="Silver";
		System.out.println("The material is "+a9.material);
		a9.colour="Silver";
		System.out.println("The colour is "+a9.colour);
		a9.type="Party";
		System.out.println("The type is "+a9.type);
		a9.length=25;
		System.out.println("The length is "+a9.length);
		a9.isAdjustable=false;
		System.out.println("Adjustable: "+a9.isAdjustable);
		a9.design="Stone";
		System.out.println("The design is "+a9.design);

		Anklets a10 = new Anklets();
		a10.brand="TBZ";
		System.out.println("The brand is "+a10.brand);
		a10.cost=3700;
		System.out.println("The cost is "+a10.cost);
		a10.material="Silver";
		System.out.println("The material is "+a10.material);
		a10.colour="Silver";
		System.out.println("The colour is "+a10.colour);
		a10.type="Traditional";
		System.out.println("The type is "+a10.type);
		a10.length=24;
		System.out.println("The length is "+a10.length);
		a10.isAdjustable=true;
		System.out.println("Adjustable: "+a10.isAdjustable);
		a10.design="Chain";
		System.out.println("The design is "+a10.design);
		
				Anklets a21 = new Anklets();
		a21.brand="Street Style";
		System.out.println("The brand is "+a21.brand);
		a21.cost=1200;
		System.out.println("The cost is "+a21.cost);
		a21.material="Alloy";
		System.out.println("The material is "+a21.material);
		a21.colour="Black";
		System.out.println("The colour is "+a21.colour);
		a21.type="Casual";
		System.out.println("The type is "+a21.type);
		a21.length=22;
		System.out.println("The length is "+a21.length);
		a21.isAdjustable=true;
		System.out.println("Adjustable: "+a21.isAdjustable);
		a21.design="Modern";
		System.out.println("The design is "+a21.design);

		Anklets a22 = new Anklets();
		a22.brand="Silver Shine";
		System.out.println("The brand is "+a22.brand);
		a22.cost=2000;
		System.out.println("The cost is "+a22.cost);
		a22.material="Silver";
		System.out.println("The material is "+a22.material);
		a22.colour="Silver";
		System.out.println("The colour is "+a22.colour);
		a22.type="Casual";
		System.out.println("The type is "+a22.type);
		a22.length=23;
		System.out.println("The length is "+a22.length);
		a22.isAdjustable=true;
		System.out.println("Adjustable: "+a22.isAdjustable);
		a22.design="Beads";
		System.out.println("The design is "+a22.design);

		Anklets a23 = new Anklets();
		a23.brand="Gold Art";
		System.out.println("The brand is "+a23.brand);
		a23.cost=5500;
		System.out.println("The cost is "+a23.cost);
		a23.material="Gold";
		System.out.println("The material is "+a23.material);
		a23.colour="Gold";
		System.out.println("The colour is "+a23.colour);
		a23.type="Traditional";
		System.out.println("The type is "+a23.type);
		a23.length=25;
		System.out.println("The length is "+a23.length);
		a23.isAdjustable=false;
		System.out.println("Adjustable: "+a23.isAdjustable);
		a23.design="Designer";
		System.out.println("The design is "+a23.design);

		Anklets a24 = new Anklets();
		a24.brand="Diamond Hub";
		System.out.println("The brand is "+a24.brand);
		a24.cost=8000;
		System.out.println("The cost is "+a24.cost);
		a24.material="Gold";
		System.out.println("The material is "+a24.material);
		a24.colour="Gold";
		System.out.println("The colour is "+a24.colour);
		a24.type="Party";
		System.out.println("The type is "+a24.type);
		a24.length=26;
		System.out.println("The length is "+a24.length);
		a24.isAdjustable=false;
		System.out.println("Adjustable: "+a24.isAdjustable);
		a24.design="Diamond";
		System.out.println("The design is "+a24.design);

		Anklets a25 = new Anklets();
		a25.brand="Fashion Anklet";
		System.out.println("The brand is "+a25.brand);
		a25.cost=1000;
		System.out.println("The cost is "+a25.cost);
		a25.material="Alloy";
		System.out.println("The material is "+a25.material);
		a25.colour="Pink";
		System.out.println("The colour is "+a25.colour);
		a25.type="Casual";
		System.out.println("The type is "+a25.type);
		a25.length=21;
		System.out.println("The length is "+a25.length);
		a25.isAdjustable=true;
		System.out.println("Adjustable: "+a25.isAdjustable);
		a25.design="Modern";
		System.out.println("The design is "+a25.design);

		Anklets a26 = new Anklets();
		a26.brand="Classic Silver";
		System.out.println("The brand is "+a26.brand);
		a26.cost=3000;
		System.out.println("The cost is "+a26.cost);
		a26.material="Silver";
		System.out.println("The material is "+a26.material);
		a26.colour="Silver";
		System.out.println("The colour is "+a26.colour);
		a26.type="Traditional";
		System.out.println("The type is "+a26.type);
		a26.length=24;
		System.out.println("The length is "+a26.length);
		a26.isAdjustable=false;
		System.out.println("Adjustable: "+a26.isAdjustable);
		a26.design="Chain";
		System.out.println("The design is "+a26.design);

		Anklets a27 = new Anklets();
		a27.brand="Modern Style";
		System.out.println("The brand is "+a27.brand);
		a27.cost=1800;
		System.out.println("The cost is "+a27.cost);
		a27.material="Alloy";
		System.out.println("The material is "+a27.material);
		a27.colour="Black";
		System.out.println("The colour is "+a27.colour);
		a27.type="Casual";
		System.out.println("The type is "+a27.type);
		a27.length=22;
		System.out.println("The length is "+a27.length);
		a27.isAdjustable=true;
		System.out.println("Adjustable: "+a27.isAdjustable);
		a27.design="Trendy";
		System.out.println("The design is "+a27.design);

		Anklets a28 = new Anklets();
		a28.brand="Royal Gold";
		System.out.println("The brand is "+a28.brand);
		a28.cost=7000;
		System.out.println("The cost is "+a28.cost);
		a28.material="Gold";
		System.out.println("The material is "+a28.material);
		a28.colour="Gold";
		System.out.println("The colour is "+a28.colour);
		a28.type="Traditional";
		System.out.println("The type is "+a28.type);
		a28.length=25;
		System.out.println("The length is "+a28.length);
		a28.isAdjustable=false;
		System.out.println("Adjustable: "+a28.isAdjustable);
		a28.design="Designer";
		System.out.println("The design is "+a28.design);

		Anklets a29 = new Anklets();
		a29.brand="Elite Anklets";
		System.out.println("The brand is "+a29.brand);
		a29.cost=6500;
		System.out.println("The cost is "+a29.cost);
		a29.material="Silver";
		System.out.println("The material is "+a29.material);
		a29.colour="Silver";
		System.out.println("The colour is "+a29.colour);
		a29.type="Party";
		System.out.println("The type is "+a29.type);
		a29.length=26;
		System.out.println("The length is "+a29.length);
		a29.isAdjustable=false;
		System.out.println("Adjustable: "+a29.isAdjustable);
		a29.design="Stone";
		System.out.println("The design is "+a29.design);

		Anklets a30 = new Anklets();
		a30.brand="Simple Anklet";
		System.out.println("The brand is "+a30.brand);
		a30.cost=1200;
		System.out.println("The cost is "+a30.cost);
		a30.material="Alloy";
		System.out.println("The material is "+a30.material);
		a30.colour="Silver";
		System.out.println("The colour is "+a30.colour);
		a30.type="Casual";
		System.out.println("The type is "+a30.type);
		a30.length=22;
		System.out.println("The length is "+a30.length);
		a30.isAdjustable=true;
		System.out.println("Adjustable: "+a30.isAdjustable);
		a30.design="Plain";
		System.out.println("The design is "+a30.design);
	}
}