class BagExec
{
    public static void main(String[] args)
    {
        Bag bag1=new Bag();
        bag1.brand="Wildcraft";
        System.out.println("The brand is "+bag1.brand);
        bag1.type="Backpack";
        System.out.println("The type is "+bag1.type);
        bag1.color="Black";
        System.out.println("The color is "+bag1.color);
        bag1.price=1999;
        System.out.println("The price is "+bag1.price);
        bag1.weight=0.8;
        System.out.println("The weight is "+bag1.weight);
        bag1.material="Polyester";
        System.out.println("The material is "+bag1.material);
        bag1.capacity=30;
        System.out.println("The capacity is "+bag1.capacity);
        bag1.numberOfCompartments=3;
        System.out.println("Compartments "+bag1.numberOfCompartments);

        Bag bag2=new Bag();
        bag2.brand="Skybags";
        System.out.println("The brand is "+bag2.brand);
        bag2.type="Laptop";
        System.out.println("The type is "+bag2.type);
        bag2.color="Blue";
        System.out.println("The color is "+bag2.color);
        bag2.price=2499;
        System.out.println("The price is "+bag2.price);
        bag2.weight=1.0;
        System.out.println("The weight is "+bag2.weight);
        bag2.material="Nylon";
        System.out.println("The material is "+bag2.material);
        bag2.capacity=35;
        System.out.println("The capacity is "+bag2.capacity);
        bag2.numberOfCompartments=4;
        System.out.println("Compartments "+bag2.numberOfCompartments);

        Bag bag3=new Bag();
        bag3.brand="AmericanTourister";
        System.out.println("The brand is "+bag3.brand);
        bag3.type="Travel";
        System.out.println("The type is "+bag3.type);
        bag3.color="Red";
        System.out.println("The color is "+bag3.color);
        bag3.price=2999;
        System.out.println("The price is "+bag3.price);
        bag3.weight=1.2;
        System.out.println("The weight is "+bag3.weight);
        bag3.material="Polyester";
        System.out.println("The material is "+bag3.material);
        bag3.capacity=40;
        System.out.println("The capacity is "+bag3.capacity);
        bag3.numberOfCompartments=5;
        System.out.println("Compartments "+bag3.numberOfCompartments);

        Bag bag4=new Bag();
        bag4.brand="Puma";
        System.out.println("The brand is "+bag4.brand);
        bag4.type="Gym";
        System.out.println("The type is "+bag4.type);
        bag4.color="Black";
        System.out.println("The color is "+bag4.color);
        bag4.price=1799;
        System.out.println("The price is "+bag4.price);
        bag4.weight=0.7;
        System.out.println("The weight is "+bag4.weight);
        bag4.material="Canvas";
        System.out.println("The material is "+bag4.material);
        bag4.capacity=25;
        System.out.println("The capacity is "+bag4.capacity);
        bag4.numberOfCompartments=2;
        System.out.println("Compartments "+bag4.numberOfCompartments);

        Bag bag5=new Bag();
        bag5.brand="Adidas";
        System.out.println("The brand is "+bag5.brand);
        bag5.type="Sports";
        System.out.println("The type is "+bag5.type);
        bag5.color="White";
        System.out.println("The color is "+bag5.color);
        bag5.price=1899;
        System.out.println("The price is "+bag5.price);
        bag5.weight=0.9;
        System.out.println("The weight is "+bag5.weight);
        bag5.material="Polyester";
        System.out.println("The material is "+bag5.material);
        bag5.capacity=28;
        System.out.println("The capacity is "+bag5.capacity);
        bag5.numberOfCompartments=3;
        System.out.println("Compartments "+bag5.numberOfCompartments);

        Bag bag6=new Bag();
        bag6.brand="Nike";
        System.out.println("The brand is "+bag6.brand);
        bag6.type="Backpack";
        System.out.println("The type is "+bag6.type);
        bag6.color="Grey";
        System.out.println("The color is "+bag6.color);
        bag6.price=2199;
        System.out.println("The price is "+bag6.price);
        bag6.weight=1.1;
        System.out.println("The weight is "+bag6.weight);
        bag6.material="Nylon";
        System.out.println("The material is "+bag6.material);
        bag6.capacity=32;
        System.out.println("The capacity is "+bag6.capacity);
        bag6.numberOfCompartments=4;
        System.out.println("Compartments "+bag6.numberOfCompartments);

        Bag bag7=new Bag();
        bag7.brand="Safari";
        System.out.println("The brand is "+bag7.brand);
        bag7.type="Travel";
        System.out.println("The type is "+bag7.type);
        bag7.color="Brown";
        System.out.println("The color is "+bag7.color);
        bag7.price=2799;
        System.out.println("The price is "+bag7.price);
        bag7.weight=1.3;
        System.out.println("The weight is "+bag7.weight);
        bag7.material="Leather";
        System.out.println("The material is "+bag7.material);
        bag7.capacity=45;
        System.out.println("The capacity is "+bag7.capacity);
        bag7.numberOfCompartments=5;
        System.out.println("Compartments "+bag7.numberOfCompartments);

        Bag bag8=new Bag();
        bag8.brand="VIP";
        System.out.println("The brand is "+bag8.brand);
        bag8.type="Office";
        System.out.println("The type is "+bag8.type);
        bag8.color="Black";
        System.out.println("The color is "+bag8.color);
        bag8.price=2599;
        System.out.println("The price is "+bag8.price);
        bag8.weight=1.0;
        System.out.println("The weight is "+bag8.weight);
        bag8.material="Synthetic";
        System.out.println("The material is "+bag8.material);
        bag8.capacity=30;
        System.out.println("The capacity is "+bag8.capacity);
        bag8.numberOfCompartments=4;
        System.out.println("Compartments "+bag8.numberOfCompartments);

        Bag bag9=new Bag();
        bag9.brand="Tommy";
        System.out.println("The brand is "+bag9.brand);
        bag9.type="Casual";
        System.out.println("The type is "+bag9.type);
        bag9.color="Blue";
        System.out.println("The color is "+bag9.color);
        bag9.price=3099;
        System.out.println("The price is "+bag9.price);
        bag9.weight=1.0;
        System.out.println("The weight is "+bag9.weight);
        bag9.material="Denim";
        System.out.println("The material is "+bag9.material);
        bag9.capacity=33;
        System.out.println("The capacity is "+bag9.capacity);
        bag9.numberOfCompartments=3;
        System.out.println("Compartments "+bag9.numberOfCompartments);

        Bag bag10=new Bag();
        bag10.brand="Guess";
        System.out.println("The brand is "+bag10.brand);
        bag10.type="Handbag";
        System.out.println("The type is "+bag10.type);
        bag10.color="Pink";
        System.out.println("The color is "+bag10.color);
        bag10.price=4599;
        System.out.println("The price is "+bag10.price);
        bag10.weight=0.9;
        System.out.println("The weight is "+bag10.weight);
        bag10.material="Leather";
        System.out.println("The material is "+bag10.material);
        bag10.capacity=20;
        System.out.println("The capacity is "+bag10.capacity);
        bag10.numberOfCompartments=2;
        System.out.println("Compartments "+bag10.numberOfCompartments);
		
		        Bag bag11=new Bag();
        bag11.brand="Fastrack";
        System.out.println("The brand is "+bag11.brand);
        bag11.type="Casual";
        System.out.println("The type is "+bag11.type);
        bag11.color="Black";
        System.out.println("The color is "+bag11.color);
        bag11.price=1899;
        System.out.println("The price is "+bag11.price);
        bag11.weight=0.8;
        System.out.println("The weight is "+bag11.weight);
        bag11.material="Polyester";
        System.out.println("The material is "+bag11.material);
        bag11.capacity=28;
        System.out.println("The capacity is "+bag11.capacity);
        bag11.numberOfCompartments=3;
        System.out.println("Compartments "+bag11.numberOfCompartments);

        Bag bag12=new Bag();
        bag12.brand="Lavie";
        System.out.println("The brand is "+bag12.brand);
        bag12.type="Handbag";
        System.out.println("The type is "+bag12.type);
        bag12.color="Red";
        System.out.println("The color is "+bag12.color);
        bag12.price=2599;
        System.out.println("The price is "+bag12.price);
        bag12.weight=0.9;
        System.out.println("The weight is "+bag12.weight);
        bag12.material="Synthetic";
        System.out.println("The material is "+bag12.material);
        bag12.capacity=22;
        System.out.println("The capacity is "+bag12.capacity);
        bag12.numberOfCompartments=2;
        System.out.println("Compartments "+bag12.numberOfCompartments);

        Bag bag13=new Bag();
        bag13.brand="Caprese";
        System.out.println("The brand is "+bag13.brand);
        bag13.type="Handbag";
        System.out.println("The type is "+bag13.type);
        bag13.color="Pink";
        System.out.println("The color is "+bag13.color);
        bag13.price=2799;
        System.out.println("The price is "+bag13.price);
        bag13.weight=0.95;
        System.out.println("The weight is "+bag13.weight);
        bag13.material="Leather";
        System.out.println("The material is "+bag13.material);
        bag13.capacity=24;
        System.out.println("The capacity is "+bag13.capacity);
        bag13.numberOfCompartments=3;
        System.out.println("Compartments "+bag13.numberOfCompartments);

        Bag bag14=new Bag();
        bag14.brand="Baggit";
        System.out.println("The brand is "+bag14.brand);
        bag14.type="Casual";
        System.out.println("The type is "+bag14.type);
        bag14.color="Brown";
        System.out.println("The color is "+bag14.color);
        bag14.price=2399;
        System.out.println("The price is "+bag14.price);
        bag14.weight=1.0;
        System.out.println("The weight is "+bag14.weight);
        bag14.material="Synthetic";
        System.out.println("The material is "+bag14.material);
        bag14.capacity=26;
        System.out.println("The capacity is "+bag14.capacity);
        bag14.numberOfCompartments=3;
        System.out.println("Compartments "+bag14.numberOfCompartments);

        Bag bag15=new Bag();
        bag15.brand="AllenSolly";
        System.out.println("The brand is "+bag15.brand);
        bag15.type="Office";
        System.out.println("The type is "+bag15.type);
        bag15.color="Black";
        System.out.println("The color is "+bag15.color);
        bag15.price=3199;
        System.out.println("The price is "+bag15.price);
        bag15.weight=1.2;
        System.out.println("The weight is "+bag15.weight);
        bag15.material="Leather";
        System.out.println("The material is "+bag15.material);
        bag15.capacity=30;
        System.out.println("The capacity is "+bag15.capacity);
        bag15.numberOfCompartments=4;
        System.out.println("Compartments "+bag15.numberOfCompartments);

        Bag bag16=new Bag();
        bag16.brand="Hidesign";
        System.out.println("The brand is "+bag16.brand);
        bag16.type="Formal";
        System.out.println("The type is "+bag16.type);
        bag16.color="Brown";
        System.out.println("The color is "+bag16.color);
        bag16.price=5999;
        System.out.println("The price is "+bag16.price);
        bag16.weight=1.4;
        System.out.println("The weight is "+bag16.weight);
        bag16.material="Genuine Leather";
        System.out.println("The material is "+bag16.material);
        bag16.capacity=35;
        System.out.println("The capacity is "+bag16.capacity);
        bag16.numberOfCompartments=5;
        System.out.println("Compartments "+bag16.numberOfCompartments);

        Bag bag17=new Bag();
        bag17.brand="Woodland";
        System.out.println("The brand is "+bag17.brand);
        bag17.type="Travel";
        System.out.println("The type is "+bag17.type);
        bag17.color="Green";
        System.out.println("The color is "+bag17.color);
        bag17.price=3499;
        System.out.println("The price is "+bag17.price);
        bag17.weight=1.5;
        System.out.println("The weight is "+bag17.weight);
        bag17.material="Canvas";
        System.out.println("The material is "+bag17.material);
        bag17.capacity=45;
        System.out.println("The capacity is "+bag17.capacity);
        bag17.numberOfCompartments=5;
        System.out.println("Compartments "+bag17.numberOfCompartments);

        Bag bag18=new Bag();
        bag18.brand="Reebok";
        System.out.println("The brand is "+bag18.brand);
        bag18.type="Sports";
        System.out.println("The type is "+bag18.type);
        bag18.color="Blue";
        System.out.println("The color is "+bag18.color);
        bag18.price=1999;
        System.out.println("The price is "+bag18.price);
        bag18.weight=1.0;
        System.out.println("The weight is "+bag18.weight);
        bag18.material="Polyester";
        System.out.println("The material is "+bag18.material);
        bag18.capacity=30;
        System.out.println("The capacity is "+bag18.capacity);
        bag18.numberOfCompartments=3;
        System.out.println("Compartments "+bag18.numberOfCompartments);

        Bag bag19=new Bag();
        bag19.brand="Fila";
        System.out.println("The brand is "+bag19.brand);
        bag19.type="Casual";
        System.out.println("The type is "+bag19.type);
        bag19.color="Grey";
        System.out.println("The color is "+bag19.color);
        bag19.price=1799;
        System.out.println("The price is "+bag19.price);
        bag19.weight=0.9;
        System.out.println("The weight is "+bag19.weight);
        bag19.material="Synthetic";
        System.out.println("The material is "+bag19.material);
        bag19.capacity=27;
        System.out.println("The capacity is "+bag19.capacity);
        bag19.numberOfCompartments=3;
        System.out.println("Compartments "+bag19.numberOfCompartments);

        Bag bag20=new Bag();
        bag20.brand="LouisPhilippe";
        System.out.println("The brand is "+bag20.brand);
        bag20.type="Office";
        System.out.println("The type is "+bag20.type);
        bag20.color="Black";
        System.out.println("The color is "+bag20.color);
        bag20.price=4599;
        System.out.println("The price is "+bag20.price);
        bag20.weight=1.3;
        System.out.println("The weight is "+bag20.weight);
        bag20.material="Leather";
        System.out.println("The material is "+bag20.material);
        bag20.capacity=32;
        System.out.println("The capacity is "+bag20.capacity);
        bag20.numberOfCompartments=4;
        System.out.println("Compartments "+bag20.numberOfCompartments);
		
		        Bag bag21=new Bag();
        bag21.brand="Zara";
        System.out.println("The brand is "+bag21.brand);
        bag21.type="Handbag";
        System.out.println("The type is "+bag21.type);
        bag21.color="Beige";
        System.out.println("The color is "+bag21.color);
        bag21.price=3999;
        System.out.println("The price is "+bag21.price);
        bag21.weight=1.0;
        System.out.println("The weight is "+bag21.weight);
        bag21.material="Leather";
        System.out.println("The material is "+bag21.material);
        bag21.capacity=25;
        System.out.println("The capacity is "+bag21.capacity);
        bag21.numberOfCompartments=3;
        System.out.println("Compartments "+bag21.numberOfCompartments);

        Bag bag22=new Bag();
        bag22.brand="H&M";
        System.out.println("The brand is "+bag22.brand);
        bag22.type="Casual";
        System.out.println("The type is "+bag22.type);
        bag22.color="Black";
        System.out.println("The color is "+bag22.color);
        bag22.price=1999;
        System.out.println("The price is "+bag22.price);
        bag22.weight=0.8;
        System.out.println("The weight is "+bag22.weight);
        bag22.material="Cotton";
        System.out.println("The material is "+bag22.material);
        bag22.capacity=22;
        System.out.println("The capacity is "+bag22.capacity);
        bag22.numberOfCompartments=2;
        System.out.println("Compartments "+bag22.numberOfCompartments);

        Bag bag23=new Bag();
        bag23.brand="Gucci";
        System.out.println("The brand is "+bag23.brand);
        bag23.type="Luxury";
        System.out.println("The type is "+bag23.type);
        bag23.color="Black";
        System.out.println("The color is "+bag23.color);
        bag23.price=15999;
        System.out.println("The price is "+bag23.price);
        bag23.weight=1.5;
        System.out.println("The weight is "+bag23.weight);
        bag23.material="Premium Leather";
        System.out.println("The material is "+bag23.material);
        bag23.capacity=35;
        System.out.println("The capacity is "+bag23.capacity);
        bag23.numberOfCompartments=5;
        System.out.println("Compartments "+bag23.numberOfCompartments);

        Bag bag24=new Bag();
        bag24.brand="Prada";
        System.out.println("The brand is "+bag24.brand);
        bag24.type="Luxury";
        System.out.println("The type is "+bag24.type);
        bag24.color="Brown";
        System.out.println("The color is "+bag24.color);
        bag24.price=18999;
        System.out.println("The price is "+bag24.price);
        bag24.weight=1.6;
        System.out.println("The weight is "+bag24.weight);
        bag24.material="Premium Leather";
        System.out.println("The material is "+bag24.material);
        bag24.capacity=36;
        System.out.println("The capacity is "+bag24.capacity);
        bag24.numberOfCompartments=5;
        System.out.println("Compartments "+bag24.numberOfCompartments);

        Bag bag25=new Bag();
        bag25.brand="Chanel";
        System.out.println("The brand is "+bag25.brand);
        bag25.type="Handbag";
        System.out.println("The type is "+bag25.type);
        bag25.color="Pink";
        System.out.println("The color is "+bag25.color);
        bag25.price=20999;
        System.out.println("The price is "+bag25.price);
        bag25.weight=1.2;
        System.out.println("The weight is "+bag25.weight);
        bag25.material="Leather";
        System.out.println("The material is "+bag25.material);
        bag25.capacity=28;
        System.out.println("The capacity is "+bag25.capacity);
        bag25.numberOfCompartments=4;
        System.out.println("Compartments "+bag25.numberOfCompartments);

        Bag bag26=new Bag();
        bag26.brand="MichaelKors";
        System.out.println("The brand is "+bag26.brand);
        bag26.type="Handbag";
        System.out.println("The type is "+bag26.type);
        bag26.color="White";
        System.out.println("The color is "+bag26.color);
        bag26.price=14999;
        System.out.println("The price is "+bag26.price);
        bag26.weight=1.3;
        System.out.println("The weight is "+bag26.weight);
        bag26.material="Leather";
        System.out.println("The material is "+bag26.material);
        bag26.capacity=30;
        System.out.println("The capacity is "+bag26.capacity);
        bag26.numberOfCompartments=4;
        System.out.println("Compartments "+bag26.numberOfCompartments);

        Bag bag27=new Bag();
        bag27.brand="Fossil";
        System.out.println("The brand is "+bag27.brand);
        bag27.type="Office";
        System.out.println("The type is "+bag27.type);
        bag27.color="Brown";
        System.out.println("The color is "+bag27.color);
        bag27.price=7999;
        System.out.println("The price is "+bag27.price);
        bag27.weight=1.4;
        System.out.println("The weight is "+bag27.weight);
        bag27.material="Leather";
        System.out.println("The material is "+bag27.material);
        bag27.capacity=34;
        System.out.println("The capacity is "+bag27.capacity);
        bag27.numberOfCompartments=5;
        System.out.println("Compartments "+bag27.numberOfCompartments);

        Bag bag28=new Bag();
        bag28.brand="Coach";
        System.out.println("The brand is "+bag28.brand);
        bag28.type="Luxury";
        System.out.println("The type is "+bag28.type);
        bag28.color="Black";
        System.out.println("The color is "+bag28.color);
        bag28.price=16999;
        System.out.println("The price is "+bag28.price);
        bag28.weight=1.5;
        System.out.println("The weight is "+bag28.weight);
        bag28.material="Premium Leather";
        System.out.println("The material is "+bag28.material);
        bag28.capacity=33;
        System.out.println("The capacity is "+bag28.capacity);
        bag28.numberOfCompartments=5;
        System.out.println("Compartments "+bag28.numberOfCompartments);

        Bag bag29=new Bag();
        bag29.brand="Dior";
        System.out.println("The brand is "+bag29.brand);
        bag29.type="Luxury";
        System.out.println("The type is "+bag29.type);
        bag29.color="Grey";
        System.out.println("The color is "+bag29.color);
        bag29.price=24999;
        System.out.println("The price is "+bag29.price);
        bag29.weight=1.6;
        System.out.println("The weight is "+bag29.weight);
        bag29.material="Premium Leather";
        System.out.println("The material is "+bag29.material);
        bag29.capacity=38;
        System.out.println("The capacity is "+bag29.capacity);
        bag29.numberOfCompartments=6;
        System.out.println("Compartments "+bag29.numberOfCompartments);

        Bag bag30=new Bag();
        bag30.brand="Versace";
        System.out.println("The brand is "+bag30.brand);
        bag30.type="Luxury";
        System.out.println("The type is "+bag30.type);
        bag30.color="Gold";
        System.out.println("The color is "+bag30.color);
        bag30.price=27999;
        System.out.println("The price is "+bag30.price);
        bag30.weight=1.7;
        System.out.println("The weight is "+bag30.weight);
        bag30.material="Premium Leather";
        System.out.println("The material is "+bag30.material);
        bag30.capacity=40;
        System.out.println("The capacity is "+bag30.capacity);
        bag30.numberOfCompartments=6;
        System.out.println("Compartments "+bag30.numberOfCompartments);
    }
}