class BanglesExec
{
	public static void main(String[] args)
	{
		Bangles b1 = new Bangles();
		b1.brand="Giva";
		System.out.println("The brand is "+b1.brand);
		b1.size=2;
		System.out.println("The size is "+b1.size);
		b1.colour="Red";
		System.out.println("The colour is "+b1.colour);
		b1.type="Glass";
		System.out.println("The type is "+b1.type);
		b1.cost=200;
		System.out.println("The cost is "+b1.cost);
		b1.material="Glass";
		System.out.println("The material is "+b1.material);
		b1.design="Simple";
		System.out.println("The design is "+b1.design);
		b1.quantity=12;
		System.out.println("The quantity is "+b1.quantity);

		Bangles b2 = new Bangles();
		b2.brand="Tanishq";
		System.out.println("The brand is "+b2.brand);
		b2.size=2;
		System.out.println("The size is "+b2.size);
		b2.colour="Green";
		System.out.println("The colour is "+b2.colour);
		b2.type="Metal";
		System.out.println("The type is "+b2.type);
		b2.cost=500;
		System.out.println("The cost is "+b2.cost);
		b2.material="Gold";
		System.out.println("The material is "+b2.material);
		b2.design="Fancy";
		System.out.println("The design is "+b2.design);
		b2.quantity=6;
		System.out.println("The quantity is "+b2.quantity);

		Bangles b3 = new Bangles();
		b3.brand="Kalyan";
		System.out.println("The brand is "+b3.brand);
		b3.size=2;
		System.out.println("The size is "+b3.size);
		b3.colour="Blue";
		System.out.println("The colour is "+b3.colour);
		b3.type="Plastic";
		System.out.println("The type is "+b3.type);
		b3.cost=150;
		System.out.println("The cost is "+b3.cost);
		b3.material="Plastic";
		System.out.println("The material is "+b3.material);
		b3.design="Stone";
		System.out.println("The design is "+b3.design);
		b3.quantity=10;
		System.out.println("The quantity is "+b3.quantity);

		Bangles b4 = new Bangles();
		b4.brand="Reliance";
		System.out.println("The brand is "+b4.brand);
		b4.size=2;
		System.out.println("The size is "+b4.size);
		b4.colour="Pink";
		System.out.println("The colour is "+b4.colour);
		b4.type="Glass";
		System.out.println("The type is "+b4.type);
		b4.cost=220;
		System.out.println("The cost is "+b4.cost);
		b4.material="Glass";
		System.out.println("The material is "+b4.material);
		b4.design="Designer";
		System.out.println("The design is "+b4.design);
		b4.quantity=8;
		System.out.println("The quantity is "+b4.quantity);

		Bangles b5 = new Bangles();
		b5.brand="Zaveri";
		System.out.println("The brand is "+b5.brand);
		b5.size=2;
		System.out.println("The size is "+b5.size);
		b5.colour="Yellow";
		System.out.println("The colour is "+b5.colour);
		b5.type="Metal";
		System.out.println("The type is "+b5.type);
		b5.cost=600;
		System.out.println("The cost is "+b5.cost);
		b5.material="Gold";
		System.out.println("The material is "+b5.material);
		b5.design="Traditional";
		System.out.println("The design is "+b5.design);
		b5.quantity=4;
		System.out.println("The quantity is "+b5.quantity);

		Bangles b6 = new Bangles();
		b6.brand="Malabar";
		System.out.println("The brand is "+b6.brand);
		b6.size=2;
		System.out.println("The size is "+b6.size);
		b6.colour="White";
		System.out.println("The colour is "+b6.colour);
		b6.type="Metal";
		System.out.println("The type is "+b6.type);
		b6.cost=700;
		System.out.println("The cost is "+b6.cost);
		b6.material="Silver";
		System.out.println("The material is "+b6.material);
		b6.design="Simple";
		System.out.println("The design is "+b6.design);
		b6.quantity=5;
		System.out.println("The quantity is "+b6.quantity);

		Bangles b7 = new Bangles();
		b7.brand="Trendy";
		System.out.println("The brand is "+b7.brand);
		b7.size=2;
		System.out.println("The size is "+b7.size);
		b7.colour="Purple";
		System.out.println("The colour is "+b7.colour);
		b7.type="Plastic";
		System.out.println("The type is "+b7.type);
		b7.cost=120;
		System.out.println("The cost is "+b7.cost);
		b7.material="Plastic";
		System.out.println("The material is "+b7.material);
		b7.design="Fancy";
		System.out.println("The design is "+b7.design);
		b7.quantity=9;
		System.out.println("The quantity is "+b7.quantity);

		Bangles b8 = new Bangles();
		b8.brand="StyleHub";
		System.out.println("The brand is "+b8.brand);
		b8.size=2;
		System.out.println("The size is "+b8.size);
		b8.colour="Orange";
		System.out.println("The colour is "+b8.colour);
		b8.type="Glass";
		System.out.println("The type is "+b8.type);
		b8.cost=180;
		System.out.println("The cost is "+b8.cost);
		b8.material="Glass";
		System.out.println("The material is "+b8.material);
		b8.design="Designer";
		System.out.println("The design is "+b8.design);
		b8.quantity=7;
		System.out.println("The quantity is "+b8.quantity);

		Bangles b9 = new Bangles();
		b9.brand="Urban";
		System.out.println("The brand is "+b9.brand);
		b9.size=2;
		System.out.println("The size is "+b9.size);
		b9.colour="Black";
		System.out.println("The colour is "+b9.colour);
		b9.type="Metal";
		System.out.println("The type is "+b9.type);
		b9.cost=350;
		System.out.println("The cost is "+b9.cost);
		b9.material="Alloy";
		System.out.println("The material is "+b9.material);
		b9.design="Modern";
		System.out.println("The design is "+b9.design);
		b9.quantity=6;
		System.out.println("The quantity is "+b9.quantity);

		Bangles b10 = new Bangles();
		b10.brand="Classic";
		System.out.println("The brand is "+b10.brand);
		b10.size=2;
		System.out.println("The size is "+b10.size);
		b10.colour="Maroon";
		System.out.println("The colour is "+b10.colour);
		b10.type="Glass";
		System.out.println("The type is "+b10.type);
		b10.cost=210;
		System.out.println("The cost is "+b10.cost);
		b10.material="Glass";
		System.out.println("The material is "+b10.material);
		b10.design="Traditional";
		System.out.println("The design is "+b10.design);
		b10.quantity=10;
		System.out.println("The quantity is "+b10.quantity);
		
				Bangles b11 = new Bangles();
		b11.brand="Elegant";
		System.out.println("The brand is "+b11.brand);
		b11.size=2;
		System.out.println("The size is "+b11.size);
		b11.colour="Gold";
		System.out.println("The colour is "+b11.colour);
		b11.type="Metal";
		System.out.println("The type is "+b11.type);
		b11.cost=800;
		System.out.println("The cost is "+b11.cost);
		b11.material="Gold";
		System.out.println("The material is "+b11.material);
		b11.design="Designer";
		System.out.println("The design is "+b11.design);
		b11.quantity=4;
		System.out.println("The quantity is "+b11.quantity);

		Bangles b12 = new Bangles();
		b12.brand="Royal";
		System.out.println("The brand is "+b12.brand);
		b12.size=2;
		System.out.println("The size is "+b12.size);
		b12.colour="Silver";
		System.out.println("The colour is "+b12.colour);
		b12.type="Metal";
		System.out.println("The type is "+b12.type);
		b12.cost=650;
		System.out.println("The cost is "+b12.cost);
		b12.material="Silver";
		System.out.println("The material is "+b12.material);
		b12.design="Fancy";
		System.out.println("The design is "+b12.design);
		b12.quantity=5;
		System.out.println("The quantity is "+b12.quantity);

		Bangles b20 = new Bangles();
		b20.brand="Glow";
		System.out.println("The brand is "+b20.brand);
		b20.size=2;
		System.out.println("The size is "+b20.size);
		b20.colour="White";
		System.out.println("The colour is "+b20.colour);
		b20.type="Glass";
		System.out.println("The type is "+b20.type);
		b20.cost=190;
		System.out.println("The cost is "+b20.cost);
		b20.material="Glass";
		System.out.println("The material is "+b20.material);
		b20.design="Simple";
		System.out.println("The design is "+b20.design);
		b20.quantity=11;
		System.out.println("The quantity is "+b20.quantity);
		
				Bangles b21 = new Bangles();
		b21.brand="Nova";
		System.out.println("The brand is "+b21.brand);
		b21.size=2;
		System.out.println("The size is "+b21.size);
		b21.colour="Pink";
		System.out.println("The colour is "+b21.colour);
		b21.type="Plastic";
		System.out.println("The type is "+b21.type);
		b21.cost=140;
		System.out.println("The cost is "+b21.cost);
		b21.material="Plastic";
		System.out.println("The material is "+b21.material);
		b21.design="Fancy";
		System.out.println("The design is "+b21.design);
		b21.quantity=8;
		System.out.println("The quantity is "+b21.quantity);

		Bangles b30 = new Bangles();
		b30.brand="Elite";
		System.out.println("The brand is "+b30.brand);
		b30.size=2;
		System.out.println("The size is "+b30.size);
		b30.colour="Red";
		System.out.println("The colour is "+b30.colour);
		b30.type="Glass";
		System.out.println("The type is "+b30.type);
		b30.cost=300;
		System.out.println("The cost is "+b30.cost);
		b30.material="Glass";
		System.out.println("The material is "+b30.material);
		b30.design="Designer";
		System.out.println("The design is "+b30.design);
		b30.quantity=12;
		System.out.println("The quantity is "+b30.quantity);
	}
}