class FlowerExec
{
	public static void main(String[] args)
	{
		Flower f1 = new Flower();
		f1.name="Rose";
		System.out.println("The name is "+f1.name);
		f1.colour="Red";
		System.out.println("The colour is "+f1.colour);
		f1.price=10;
		System.out.println("The price is "+f1.price);
		f1.fragrance="Strong";
		System.out.println("Fragrance is "+f1.fragrance);
		f1.type="Natural";
		System.out.println("Type is "+f1.type);
		f1.isFresh=true;
		System.out.println("Fresh: "+f1.isFresh);
		f1.numberOfPetals=32;
		System.out.println("Petals "+f1.numberOfPetals);
		f1.season="Winter";
		System.out.println("Season "+f1.season);

		Flower f2 = new Flower();
		f2.name="Jasmine";
		System.out.println("The name is "+f2.name);
		f2.colour="White";
		System.out.println("The colour is "+f2.colour);
		f2.price=5;
		System.out.println("The price is "+f2.price);
		f2.fragrance="Strong";
		System.out.println("Fragrance is "+f2.fragrance);
		f2.type="Natural";
		System.out.println("Type is "+f2.type);
		f2.isFresh=true;
		System.out.println("Fresh: "+f2.isFresh);
		f2.numberOfPetals=8;
		System.out.println("Petals "+f2.numberOfPetals);
		f2.season="Summer";
		System.out.println("Season "+f2.season);

		Flower f3 = new Flower();
		f3.name="Lotus";
		System.out.println("The name is "+f3.name);
		f3.colour="Pink";
		System.out.println("The colour is "+f3.colour);
		f3.price=20;
		System.out.println("The price is "+f3.price);
		f3.fragrance="Mild";
		System.out.println("Fragrance is "+f3.fragrance);
		f3.type="Natural";
		System.out.println("Type is "+f3.type);
		f3.isFresh=true;
		System.out.println("Fresh: "+f3.isFresh);
		f3.numberOfPetals=24;
		System.out.println("Petals "+f3.numberOfPetals);
		f3.season="Monsoon";
		System.out.println("Season "+f3.season);

		Flower f4 = new Flower();
		f4.name="Sunflower";
		System.out.println("The name is "+f4.name);
		f4.colour="Yellow";
		System.out.println("The colour is "+f4.colour);
		f4.price=15;
		System.out.println("The price is "+f4.price);
		f4.fragrance="None";
		System.out.println("Fragrance is "+f4.fragrance);
		f4.type="Natural";
		System.out.println("Type is "+f4.type);
		f4.isFresh=true;
		System.out.println("Fresh: "+f4.isFresh);
		f4.numberOfPetals=30;
		System.out.println("Petals "+f4.numberOfPetals);
		f4.season="Summer";
		System.out.println("Season "+f4.season);

		Flower f5 = new Flower();
		f5.name="Tulip";
		System.out.println("The name is "+f5.name);
		f5.colour="Red";
		System.out.println("The colour is "+f5.colour);
		f5.price=25;
		System.out.println("The price is "+f5.price);
		f5.fragrance="Mild";
		System.out.println("Fragrance is "+f5.fragrance);
		f5.type="Natural";
		System.out.println("Type is "+f5.type);
		f5.isFresh=true;
		System.out.println("Fresh: "+f5.isFresh);
		f5.numberOfPetals=6;
		System.out.println("Petals "+f5.numberOfPetals);
		f5.season="Spring";
		System.out.println("Season "+f5.season);

		Flower f6 = new Flower();
		f6.name="Lily";
		System.out.println("The name is "+f6.name);
		f6.colour="White";
		System.out.println("The colour is "+f6.colour);
		f6.price=18;
		System.out.println("The price is "+f6.price);
		f6.fragrance="Strong";
		System.out.println("Fragrance is "+f6.fragrance);
		f6.type="Natural";
		System.out.println("Type is "+f6.type);
		f6.isFresh=true;
		System.out.println("Fresh: "+f6.isFresh);
		f6.numberOfPetals=6;
		System.out.println("Petals "+f6.numberOfPetals);
		f6.season="Spring";
		System.out.println("Season "+f6.season);

		Flower f7 = new Flower();
		f7.name="Marigold";
		System.out.println("The name is "+f7.name);
		f7.colour="Orange";
		System.out.println("The colour is "+f7.colour);
		f7.price=8;
		System.out.println("The price is "+f7.price);
		f7.fragrance="Strong";
		System.out.println("Fragrance is "+f7.fragrance);
		f7.type="Natural";
		System.out.println("Type is "+f7.type);
		f7.isFresh=true;
		System.out.println("Fresh: "+f7.isFresh);
		f7.numberOfPetals=40;
		System.out.println("Petals "+f7.numberOfPetals);
		f7.season="Winter";
		System.out.println("Season "+f7.season);

		Flower f8 = new Flower();
		f8.name="Daisy";
		System.out.println("The name is "+f8.name);
		f8.colour="White";
		System.out.println("The colour is "+f8.colour);
		f8.price=12;
		System.out.println("The price is "+f8.price);
		f8.fragrance="Mild";
		System.out.println("Fragrance is "+f8.fragrance);
		f8.type="Natural";
		System.out.println("Type is "+f8.type);
		f8.isFresh=true;
		System.out.println("Fresh: "+f8.isFresh);
		f8.numberOfPetals=20;
		System.out.println("Petals "+f8.numberOfPetals);
		f8.season="Spring";
		System.out.println("Season "+f8.season);

		Flower f9 = new Flower();
		f9.name="Orchid";
		System.out.println("The name is "+f9.name);
		f9.colour="Purple";
		System.out.println("The colour is "+f9.colour);
		f9.price=30;
		System.out.println("The price is "+f9.price);
		f9.fragrance="Mild";
		System.out.println("Fragrance is "+f9.fragrance);
		f9.type="Natural";
		System.out.println("Type is "+f9.type);
		f9.isFresh=true;
		System.out.println("Fresh: "+f9.isFresh);
		f9.numberOfPetals=10;
		System.out.println("Petals "+f9.numberOfPetals);
		f9.season="All";
		System.out.println("Season "+f9.season);

		Flower f10 = new Flower();
		f10.name="Hibiscus";
		System.out.println("The name is "+f10.name);
		f10.colour="Red";
		System.out.println("The colour is "+f10.colour);
		f10.price=7;
		System.out.println("The price is "+f10.price);
		f10.fragrance="None";
		System.out.println("Fragrance is "+f10.fragrance);
		f10.type="Natural";
		System.out.println("Type is "+f10.type);
		f10.isFresh=true;
		System.out.println("Fresh: "+f10.isFresh);
		f10.numberOfPetals=5;
		System.out.println("Petals "+f10.numberOfPetals);
		f10.season="Summer";
		System.out.println("Season "+f10.season);
		
				Flower f11 = new Flower();
		f11.name="Lavender";
		System.out.println("The name is "+f11.name);
		f11.colour="Purple";
		System.out.println("The colour is "+f11.colour);
		f11.price=22;
		System.out.println("The price is "+f11.price);
		f11.fragrance="Strong";
		System.out.println("Fragrance is "+f11.fragrance);
		f11.type="Natural";
		System.out.println("Type is "+f11.type);
		f11.isFresh=true;
		System.out.println("Fresh: "+f11.isFresh);
		f11.numberOfPetals=12;
		System.out.println("Petals "+f11.numberOfPetals);
		f11.season="Spring";
		System.out.println("Season "+f11.season);

		Flower f12 = new Flower();
		f12.name="Bluebell";
		System.out.println("The name is "+f12.name);
		f12.colour="Blue";
		System.out.println("The colour is "+f12.colour);
		f12.price=16;
		System.out.println("The price is "+f12.price);
		f12.fragrance="Mild";
		System.out.println("Fragrance is "+f12.fragrance);
		f12.type="Natural";
		System.out.println("Type is "+f12.type);
		f12.isFresh=true;
		System.out.println("Fresh: "+f12.isFresh);
		f12.numberOfPetals=6;
		System.out.println("Petals "+f12.numberOfPetals);
		f12.season="Spring";
		System.out.println("Season "+f12.season);

		Flower f13 = new Flower();
		f13.name="Chrysanthemum";
		System.out.println("The name is "+f13.name);
		f13.colour="Yellow";
		System.out.println("The colour is "+f13.colour);
		f13.price=14;
		System.out.println("The price is "+f13.price);
		f13.fragrance="Mild";
		System.out.println("Fragrance is "+f13.fragrance);
		f13.type="Natural";
		System.out.println("Type is "+f13.type);
		f13.isFresh=true;
		System.out.println("Fresh: "+f13.isFresh);
		f13.numberOfPetals=45;
		System.out.println("Petals "+f13.numberOfPetals);
		f13.season="Winter";
		System.out.println("Season "+f13.season);

		Flower f14 = new Flower();
		f14.name="Carnation";
		System.out.println("The name is "+f14.name);
		f14.colour="Pink";
		System.out.println("The colour is "+f14.colour);
		f14.price=13;
		System.out.println("The price is "+f14.price);
		f14.fragrance="Mild";
		System.out.println("Fragrance is "+f14.fragrance);
		f14.type="Natural";
		System.out.println("Type is "+f14.type);
		f14.isFresh=true;
		System.out.println("Fresh: "+f14.isFresh);
		f14.numberOfPetals=25;
		System.out.println("Petals "+f14.numberOfPetals);
		f14.season="Spring";
		System.out.println("Season "+f14.season);

		Flower f15 = new Flower();
		f15.name="Gerbera";
		System.out.println("The name is "+f15.name);
		f15.colour="Orange";
		System.out.println("The colour is "+f15.colour);
		f15.price=11;
		System.out.println("The price is "+f15.price);
		f15.fragrance="None";
		System.out.println("Fragrance is "+f15.fragrance);
		f15.type="Natural";
		System.out.println("Type is "+f15.type);
		f15.isFresh=true;
		System.out.println("Fresh: "+f15.isFresh);
		f15.numberOfPetals=30;
		System.out.println("Petals "+f15.numberOfPetals);
		f15.season="Summer";
		System.out.println("Season "+f15.season);

		Flower f16 = new Flower();
		f16.name="Peony";
		System.out.println("The name is "+f16.name);
		f16.colour="Pink";
		System.out.println("The colour is "+f16.colour);
		f16.price=35;
		System.out.println("The price is "+f16.price);
		f16.fragrance="Strong";
		System.out.println("Fragrance is "+f16.fragrance);
		f16.type="Natural";
		System.out.println("Type is "+f16.type);
		f16.isFresh=true;
		System.out.println("Fresh: "+f16.isFresh);
		f16.numberOfPetals=50;
		System.out.println("Petals "+f16.numberOfPetals);
		f16.season="Spring";
		System.out.println("Season "+f16.season);

		Flower f17 = new Flower();
		f17.name="Daffodil";
		System.out.println("The name is "+f17.name);
		f17.colour="Yellow";
		System.out.println("The colour is "+f17.colour);
		f17.price=9;
		System.out.println("The price is "+f17.price);
		f17.fragrance="Mild";
		System.out.println("Fragrance is "+f17.fragrance);
		f17.type="Natural";
		System.out.println("Type is "+f17.type);
		f17.isFresh=true;
		System.out.println("Fresh: "+f17.isFresh);
		f17.numberOfPetals=6;
		System.out.println("Petals "+f17.numberOfPetals);
		f17.season="Spring";
		System.out.println("Season "+f17.season);

		Flower f18 = new Flower();
		f18.name="Zinnia";
		System.out.println("The name is "+f18.name);
		f18.colour="Red";
		System.out.println("The colour is "+f18.colour);
		f18.price=10;
		System.out.println("The price is "+f18.price);
		f18.fragrance="None";
		System.out.println("Fragrance is "+f18.fragrance);
		f18.type="Natural";
		System.out.println("Type is "+f18.type);
		f18.isFresh=true;
		System.out.println("Fresh: "+f18.isFresh);
		f18.numberOfPetals=20;
		System.out.println("Petals "+f18.numberOfPetals);
		f18.season="Summer";
		System.out.println("Season "+f18.season);

		Flower f19 = new Flower();
		f19.name="Begonia";
		System.out.println("The name is "+f19.name);
		f19.colour="Pink";
		System.out.println("The colour is "+f19.colour);
		f19.price=12;
		System.out.println("The price is "+f19.price);
		f19.fragrance="Mild";
		System.out.println("Fragrance is "+f19.fragrance);
		f19.type="Natural";
		System.out.println("Type is "+f19.type);
		f19.isFresh=true;
		System.out.println("Fresh: "+f19.isFresh);
		f19.numberOfPetals=18;
		System.out.println("Petals "+f19.numberOfPetals);
		f19.season="Summer";
		System.out.println("Season "+f19.season);

		Flower f20 = new Flower();
		f20.name="Magnolia";
		System.out.println("The name is "+f20.name);
		f20.colour="White";
		System.out.println("The colour is "+f20.colour);
		f20.price=28;
		System.out.println("The price is "+f20.price);
		f20.fragrance="Strong";
		System.out.println("Fragrance is "+f20.fragrance);
		f20.type="Natural";
		System.out.println("Type is "+f20.type);
		f20.isFresh=true;
		System.out.println("Fresh: "+f20.isFresh);
		f20.numberOfPetals=12;
		System.out.println("Petals "+f20.numberOfPetals);
		f20.season="Spring";
		System.out.println("Season "+f20.season);
		
				Flower f21 = new Flower();
		f21.name="Artificial Rose";
		System.out.println("The name is "+f21.name);
		f21.colour="Red";
		System.out.println("The colour is "+f21.colour);
		f21.price=50;
		System.out.println("The price is "+f21.price);
		f21.fragrance="None";
		System.out.println("Fragrance is "+f21.fragrance);
		f21.type="Artificial";
		System.out.println("Type is "+f21.type);
		f21.isFresh=false;
		System.out.println("Fresh: "+f21.isFresh);
		f21.numberOfPetals=30;
		System.out.println("Petals "+f21.numberOfPetals);
		f21.season="All";
		System.out.println("Season "+f21.season);

		Flower f22 = new Flower();
		f22.name="Artificial Lily";
		System.out.println("The name is "+f22.name);
		f22.colour="White";
		System.out.println("The colour is "+f22.colour);
		f22.price=45;
		System.out.println("The price is "+f22.price);
		f22.fragrance="None";
		System.out.println("Fragrance is "+f22.fragrance);
		f22.type="Artificial";
		System.out.println("Type is "+f22.type);
		f22.isFresh=false;
		System.out.println("Fresh: "+f22.isFresh);
		f22.numberOfPetals=6;
		System.out.println("Petals "+f22.numberOfPetals);
		f22.season="All";
		System.out.println("Season "+f22.season);

		Flower f23 = new Flower();
		f23.name="Artificial Tulip";
		System.out.println("The name is "+f23.name);
		f23.colour="Yellow";
		System.out.println("The colour is "+f23.colour);
		f23.price=40;
		System.out.println("The price is "+f23.price);
		f23.fragrance="None";
		System.out.println("Fragrance is "+f23.fragrance);
		f23.type="Artificial";
		System.out.println("Type is "+f23.type);
		f23.isFresh=false;
		System.out.println("Fresh: "+f23.isFresh);
		f23.numberOfPetals=6;
		System.out.println("Petals "+f23.numberOfPetals);
		f23.season="All";
		System.out.println("Season "+f23.season);

		Flower f24 = new Flower();
		f24.name="Artificial Daisy";
		System.out.println("The name is "+f24.name);
		f24.colour="White";
		System.out.println("The colour is "+f24.colour);
		f24.price=35;
		System.out.println("The price is "+f24.price);
		f24.fragrance="None";
		System.out.println("Fragrance is "+f24.fragrance);
		f24.type="Artificial";
		System.out.println("Type is "+f24.type);
		f24.isFresh=false;
		System.out.println("Fresh: "+f24.isFresh);
		f24.numberOfPetals=20;
		System.out.println("Petals "+f24.numberOfPetals);
		f24.season="All";
		System.out.println("Season "+f24.season);

		Flower f25 = new Flower();
		f25.name="Artificial Orchid";
		System.out.println("The name is "+f25.name);
		f25.colour="Purple";
		System.out.println("The colour is "+f25.colour);
		f25.price=60;
		System.out.println("The price is "+f25.price);
		f25.fragrance="None";
		System.out.println("Fragrance is "+f25.fragrance);
		f25.type="Artificial";
		System.out.println("Type is "+f25.type);
		f25.isFresh=false;
		System.out.println("Fresh: "+f25.isFresh);
		f25.numberOfPetals=10;
		System.out.println("Petals "+f25.numberOfPetals);
		f25.season="All";
		System.out.println("Season "+f25.season);

		Flower f26 = new Flower();
		f26.name="Gardenia";
		System.out.println("The name is "+f26.name);
		f26.colour="White";
		System.out.println("The colour is "+f26.colour);
		f26.price=18;
		System.out.println("The price is "+f26.price);
		f26.fragrance="Strong";
		System.out.println("Fragrance is "+f26.fragrance);
		f26.type="Natural";
		System.out.println("Type is "+f26.type);
		f26.isFresh=true;
		System.out.println("Fresh: "+f26.isFresh);
		f26.numberOfPetals=12;
		System.out.println("Petals "+f26.numberOfPetals);
		f26.season="Summer";
		System.out.println("Season "+f26.season);

		Flower f27 = new Flower();
		f27.name="Camellia";
		System.out.println("The name is "+f27.name);
		f27.colour="Pink";
		System.out.println("The colour is "+f27.colour);
		f27.price=20;
		System.out.println("The price is "+f27.price);
		f27.fragrance="Mild";
		System.out.println("Fragrance is "+f27.fragrance);
		f27.type="Natural";
		System.out.println("Type is "+f27.type);
		f27.isFresh=true;
		System.out.println("Fresh: "+f27.isFresh);
		f27.numberOfPetals=25;
		System.out.println("Petals "+f27.numberOfPetals);
		f27.season="Winter";
		System.out.println("Season "+f27.season);

		Flower f28 = new Flower();
		f28.name="Cosmos";
		System.out.println("The name is "+f28.name);
		f28.colour="Pink";
		System.out.println("The colour is "+f28.colour);
		f28.price=9;
		System.out.println("The price is "+f28.price);
		f28.fragrance="None";
		System.out.println("Fragrance is "+f28.fragrance);
		f28.type="Natural";
		System.out.println("Type is "+f28.type);
		f28.isFresh=true;
		System.out.println("Fresh: "+f28.isFresh);
		f28.numberOfPetals=8;
		System.out.println("Petals "+f28.numberOfPetals);
		f28.season="Summer";
		System.out.println("Season "+f28.season);

		Flower f29 = new Flower();
		f29.name="Aster";
		System.out.println("The name is "+f29.name);
		f29.colour="Purple";
		System.out.println("The colour is "+f29.colour);
		f29.price=11;
		System.out.println("The price is "+f29.price);
		f29.fragrance="Mild";
		System.out.println("Fragrance is "+f29.fragrance);
		f29.type="Natural";
		System.out.println("Type is "+f29.type);
		f29.isFresh=true;
		System.out.println("Fresh: "+f29.isFresh);
		f29.numberOfPetals=15;
		System.out.println("Petals "+f29.numberOfPetals);
		f29.season="Autumn";
		System.out.println("Season "+f29.season);

		Flower f30 = new Flower();
		f30.name="Poppy";
		System.out.println("The name is "+f30.name);
		f30.colour="Red";
		System.out.println("The colour is "+f30.colour);
		f30.price=13;
		System.out.println("The price is "+f30.price);
		f30.fragrance="None";
		System.out.println("Fragrance is "+f30.fragrance);
		f30.type="Natural";
		System.out.println("Type is "+f30.type);
		f30.isFresh=true;
		System.out.println("Fresh: "+f30.isFresh);
		f30.numberOfPetals=4;
		System.out.println("Petals "+f30.numberOfPetals);
		f30.season="Spring";
		System.out.println("Season "+f30.season);
	}
}