class GogglesExec
{
	public static void main(String[] args)
	{
		Goggles g1 = new Goggles();
		g1.brand="RayBan";
		System.out.println("The brand is "+g1.brand);
		g1.cost=2500;
		System.out.println("The cost is "+g1.cost);
		g1.colour="Black";
		System.out.println("The colour is "+g1.colour);
		g1.type="Sunglasses";
		System.out.println("The type is "+g1.type);
		g1.lensType="UV Protection";
		System.out.println("The lens type is "+g1.lensType);
		g1.frameMaterial="Metal";
		System.out.println("The frame material is "+g1.frameMaterial);
		g1.isPolarized=true;
		System.out.println("Polarized: "+g1.isPolarized);
		g1.size="Medium";
		System.out.println("The size is "+g1.size);

		Goggles g2 = new Goggles();
		g2.brand="Fastrack";
		System.out.println("The brand is "+g2.brand);
		g2.cost=1500;
		System.out.println("The cost is "+g2.cost);
		g2.colour="Blue";
		System.out.println("The colour is "+g2.colour);
		g2.type="Sunglasses";
		System.out.println("The type is "+g2.type);
		g2.lensType="Anti-glare";
		System.out.println("The lens type is "+g2.lensType);
		g2.frameMaterial="Plastic";
		System.out.println("The frame material is "+g2.frameMaterial);
		g2.isPolarized=false;
		System.out.println("Polarized: "+g2.isPolarized);
		g2.size="Medium";
		System.out.println("The size is "+g2.size);

		Goggles g3 = new Goggles();
		g3.brand="Oakley";
		System.out.println("The brand is "+g3.brand);
		g3.cost=4000;
		System.out.println("The cost is "+g3.cost);
		g3.colour="Grey";
		System.out.println("The colour is "+g3.colour);
		g3.type="Sports";
		System.out.println("The type is "+g3.type);
		g3.lensType="Polarized";
		System.out.println("The lens type is "+g3.lensType);
		g3.frameMaterial="Fiber";
		System.out.println("The frame material is "+g3.frameMaterial);
		g3.isPolarized=true;
		System.out.println("Polarized: "+g3.isPolarized);
		g3.size="Large";
		System.out.println("The size is "+g3.size);

		Goggles g4 = new Goggles();
		g4.brand="Puma";
		System.out.println("The brand is "+g4.brand);
		g4.cost=1800;
		System.out.println("The cost is "+g4.cost);
		g4.colour="Red";
		System.out.println("The colour is "+g4.colour);
		g4.type="Sports";
		System.out.println("The type is "+g4.type);
		g4.lensType="UV";
		System.out.println("The lens type is "+g4.lensType);
		g4.frameMaterial="Plastic";
		System.out.println("The frame material is "+g4.frameMaterial);
		g4.isPolarized=false;
		System.out.println("Polarized: "+g4.isPolarized);
		g4.size="Medium";
		System.out.println("The size is "+g4.size);

		Goggles g5 = new Goggles();
		g5.brand="Adidas";
		System.out.println("The brand is "+g5.brand);
		g5.cost=2200;
		System.out.println("The cost is "+g5.cost);
		g5.colour="Black";
		System.out.println("The colour is "+g5.colour);
		g5.type="Sunglasses";
		System.out.println("The type is "+g5.type);
		g5.lensType="Mirrored";
		System.out.println("The lens type is "+g5.lensType);
		g5.frameMaterial="Fiber";
		System.out.println("The frame material is "+g5.frameMaterial);
		g5.isPolarized=true;
		System.out.println("Polarized: "+g5.isPolarized);
		g5.size="Large";
		System.out.println("The size is "+g5.size);

		Goggles g6 = new Goggles();
		g6.brand="Nike";
		System.out.println("The brand is "+g6.brand);
		g6.cost=2100;
		System.out.println("The cost is "+g6.cost);
		g6.colour="Blue";
		System.out.println("The colour is "+g6.colour);
		g6.type="Sports";
		System.out.println("The type is "+g6.type);
		g6.lensType="UV Protection";
		System.out.println("The lens type is "+g6.lensType);
		g6.frameMaterial="Plastic";
		System.out.println("The frame material is "+g6.frameMaterial);
		g6.isPolarized=true;
		System.out.println("Polarized: "+g6.isPolarized);
		g6.size="Medium";
		System.out.println("The size is "+g6.size);

		Goggles g7 = new Goggles();
		g7.brand="Reebok";
		System.out.println("The brand is "+g7.brand);
		g7.cost=1700;
		System.out.println("The cost is "+g7.cost);
		g7.colour="Grey";
		System.out.println("The colour is "+g7.colour);
		g7.type="Sunglasses";
		System.out.println("The type is "+g7.type);
		g7.lensType="Anti-glare";
		System.out.println("The lens type is "+g7.lensType);
		g7.frameMaterial="Plastic";
		System.out.println("The frame material is "+g7.frameMaterial);
		g7.isPolarized=false;
		System.out.println("Polarized: "+g7.isPolarized);
		g7.size="Small";
		System.out.println("The size is "+g7.size);

		Goggles g8 = new Goggles();
		g8.brand="Gucci";
		System.out.println("The brand is "+g8.brand);
		g8.cost=6000;
		System.out.println("The cost is "+g8.cost);
		g8.colour="Black";
		System.out.println("The colour is "+g8.colour);
		g8.type="Fashion";
		System.out.println("The type is "+g8.type);
		g8.lensType="Polarized";
		System.out.println("The lens type is "+g8.lensType);
		g8.frameMaterial="Metal";
		System.out.println("The frame material is "+g8.frameMaterial);
		g8.isPolarized=true;
		System.out.println("Polarized: "+g8.isPolarized);
		g8.size="Large";
		System.out.println("The size is "+g8.size);

		Goggles g9 = new Goggles();
		g9.brand="Prada";
		System.out.println("The brand is "+g9.brand);
		g9.cost=5500;
		System.out.println("The cost is "+g9.cost);
		g9.colour="Brown";
		System.out.println("The colour is "+g9.colour);
		g9.type="Fashion";
		System.out.println("The type is "+g9.type);
		g9.lensType="UV";
		System.out.println("The lens type is "+g9.lensType);
		g9.frameMaterial="Metal";
		System.out.println("The frame material is "+g9.frameMaterial);
		g9.isPolarized=true;
		System.out.println("Polarized: "+g9.isPolarized);
		g9.size="Large";
		System.out.println("The size is "+g9.size);

		Goggles g10 = new Goggles();
		g10.brand="Police";
		System.out.println("The brand is "+g10.brand);
		g10.cost=3000;
		System.out.println("The cost is "+g10.cost);
		g10.colour="Black";
		System.out.println("The colour is "+g10.colour);
		g10.type="Sunglasses";
		System.out.println("The type is "+g10.type);
		g10.lensType="Mirrored";
		System.out.println("The lens type is "+g10.lensType);
		g10.frameMaterial="Metal";
		System.out.println("The frame material is "+g10.frameMaterial);
		g10.isPolarized=true;
		System.out.println("Polarized: "+g10.isPolarized);
		g10.size="Medium";
		System.out.println("The size is "+g10.size);
		
				Goggles g11 = new Goggles();
		g11.brand="Titan Eye+";
		System.out.println("The brand is "+g11.brand);
		g11.cost=2000;
		System.out.println("The cost is "+g11.cost);
		g11.colour="Blue";
		System.out.println("The colour is "+g11.colour);
		g11.type="Sunglasses";
		System.out.println("The type is "+g11.type);
		g11.lensType="UV";
		System.out.println("The lens type is "+g11.lensType);
		g11.frameMaterial="Plastic";
		System.out.println("The frame material is "+g11.frameMaterial);
		g11.isPolarized=false;
		System.out.println("Polarized: "+g11.isPolarized);
		g11.size="Medium";
		System.out.println("The size is "+g11.size);

		Goggles g12 = new Goggles();
		g12.brand="IDEE";
		System.out.println("The brand is "+g12.brand);
		g12.cost=1800;
		System.out.println("The cost is "+g12.cost);
		g12.colour="Grey";
		System.out.println("The colour is "+g12.colour);
		g12.type="Sunglasses";
		System.out.println("The type is "+g12.type);
		g12.lensType="Anti-glare";
		System.out.println("The lens type is "+g12.lensType);
		g12.frameMaterial="Plastic";
		System.out.println("The frame material is "+g12.frameMaterial);
		g12.isPolarized=false;
		System.out.println("Polarized: "+g12.isPolarized);
		g12.size="Small";
		System.out.println("The size is "+g12.size);

		Goggles g13 = new Goggles();
		g13.brand="Carrera";
		System.out.println("The brand is "+g13.brand);
		g13.cost=3500;
		System.out.println("The cost is "+g13.cost);
		g13.colour="Red";
		System.out.println("The colour is "+g13.colour);
		g13.type="Sports";
		System.out.println("The type is "+g13.type);
		g13.lensType="Polarized";
		System.out.println("The lens type is "+g13.lensType);
		g13.frameMaterial="Fiber";
		System.out.println("The frame material is "+g13.frameMaterial);
		g13.isPolarized=true;
		System.out.println("Polarized: "+g13.isPolarized);
		g13.size="Large";
		System.out.println("The size is "+g13.size);

		Goggles g14 = new Goggles();
		g14.brand="Versace";
		System.out.println("The brand is "+g14.brand);
		g14.cost=7000;
		System.out.println("The cost is "+g14.cost);
		g14.colour="Black";
		System.out.println("The colour is "+g14.colour);
		g14.type="Fashion";
		System.out.println("The type is "+g14.type);
		g14.lensType="UV Protection";
		System.out.println("The lens type is "+g14.lensType);
		g14.frameMaterial="Metal";
		System.out.println("The frame material is "+g14.frameMaterial);
		g14.isPolarized=true;
		System.out.println("Polarized: "+g14.isPolarized);
		g14.size="Large";
		System.out.println("The size is "+g14.size);

		Goggles g15 = new Goggles();
		g15.brand="Tommy";
		System.out.println("The brand is "+g15.brand);
		g15.cost=3200;
		System.out.println("The cost is "+g15.cost);
		g15.colour="Blue";
		System.out.println("The colour is "+g15.colour);
		g15.type="Sunglasses";
		System.out.println("The type is "+g15.type);
		g15.lensType="Mirrored";
		System.out.println("The lens type is "+g15.lensType);
		g15.frameMaterial="Plastic";
		System.out.println("The frame material is "+g15.frameMaterial);
		g15.isPolarized=true;
		System.out.println("Polarized: "+g15.isPolarized);
		g15.size="Medium";
		System.out.println("The size is "+g15.size);

		Goggles g16 = new Goggles();
		g16.brand="Armani";
		System.out.println("The brand is "+g16.brand);
		g16.cost=6500;
		System.out.println("The cost is "+g16.cost);
		g16.colour="Brown";
		System.out.println("The colour is "+g16.colour);
		g16.type="Fashion";
		System.out.println("The type is "+g16.type);
		g16.lensType="Polarized";
		System.out.println("The lens type is "+g16.lensType);
		g16.frameMaterial="Metal";
		System.out.println("The frame material is "+g16.frameMaterial);
		g16.isPolarized=true;
		System.out.println("Polarized: "+g16.isPolarized);
		g16.size="Large";
		System.out.println("The size is "+g16.size);

		Goggles g17 = new Goggles();
		g17.brand="Boss";
		System.out.println("The brand is "+g17.brand);
		g17.cost=5000;
		System.out.println("The cost is "+g17.cost);
		g17.colour="Black";
		System.out.println("The colour is "+g17.colour);
		g17.type="Sunglasses";
		System.out.println("The type is "+g17.type);
		g17.lensType="UV";
		System.out.println("The lens type is "+g17.lensType);
		g17.frameMaterial="Metal";
		System.out.println("The frame material is "+g17.frameMaterial);
		g17.isPolarized=true;
		System.out.println("Polarized: "+g17.isPolarized);
		g17.size="Medium";
		System.out.println("The size is "+g17.size);

		Goggles g18 = new Goggles();
		g18.brand="Calvin Klein";
		System.out.println("The brand is "+g18.brand);
		g18.cost=4500;
		System.out.println("The cost is "+g18.cost);
		g18.colour="Grey";
		System.out.println("The colour is "+g18.colour);
		g18.type="Fashion";
		System.out.println("The type is "+g18.type);
		g18.lensType="Anti-glare";
		System.out.println("The lens type is "+g18.lensType);
		g18.frameMaterial="Plastic";
		System.out.println("The frame material is "+g18.frameMaterial);
		g18.isPolarized=false;
		System.out.println("Polarized: "+g18.isPolarized);
		g18.size="Medium";
		System.out.println("The size is "+g18.size);

		Goggles g19 = new Goggles();
		g19.brand="Diesel";
		System.out.println("The brand is "+g19.brand);
		g19.cost=3800;
		System.out.println("The cost is "+g19.cost);
		g19.colour="Black";
		System.out.println("The colour is "+g19.colour);
		g19.type="Sunglasses";
		System.out.println("The type is "+g19.type);
		g19.lensType="Mirrored";
		System.out.println("The lens type is "+g19.lensType);
		g19.frameMaterial="Metal";
		System.out.println("The frame material is "+g19.frameMaterial);
		g19.isPolarized=true;
		System.out.println("Polarized: "+g19.isPolarized);
		g19.size="Large";
		System.out.println("The size is "+g19.size);

		Goggles g20 = new Goggles();
		g20.brand="Police X";
		System.out.println("The brand is "+g20.brand);
		g20.cost=3400;
		System.out.println("The cost is "+g20.cost);
		g20.colour="Blue";
		System.out.println("The colour is "+g20.colour);
		g20.type="Sports";
		System.out.println("The type is "+g20.type);
		g20.lensType="UV Protection";
		System.out.println("The lens type is "+g20.lensType);
		g20.frameMaterial="Fiber";
		System.out.println("The frame material is "+g20.frameMaterial);
		g20.isPolarized=true;
		System.out.println("Polarized: "+g20.isPolarized);
		g20.size="Medium";
		System.out.println("The size is "+g20.size);
		
		
				Goggles g21 = new Goggles();
		g21.brand="Roadster";
		System.out.println("The brand is "+g21.brand);
		g21.cost=1200;
		System.out.println("The cost is "+g21.cost);
		g21.colour="Black";
		System.out.println("The colour is "+g21.colour);
		g21.type="Sunglasses";
		System.out.println("The type is "+g21.type);
		g21.lensType="UV";
		System.out.println("The lens type is "+g21.lensType);
		g21.frameMaterial="Plastic";
		System.out.println("The frame material is "+g21.frameMaterial);
		g21.isPolarized=false;
		System.out.println("Polarized: "+g21.isPolarized);
		g21.size="Medium";
		System.out.println("The size is "+g21.size);

		Goggles g22 = new Goggles();
		g22.brand="HRX";
		System.out.println("The brand is "+g22.brand);
		g22.cost=1400;
		System.out.println("The cost is "+g22.cost);
		g22.colour="Grey";
		System.out.println("The colour is "+g22.colour);
		g22.type="Sports";
		System.out.println("The type is "+g22.type);
		g22.lensType="Anti-glare";
		System.out.println("The lens type is "+g22.lensType);
		g22.frameMaterial="Plastic";
		System.out.println("The frame material is "+g22.frameMaterial);
		g22.isPolarized=false;
		System.out.println("Polarized: "+g22.isPolarized);
		g22.size="Small";
		System.out.println("The size is "+g22.size);

		Goggles g23 = new Goggles();
		g23.brand="Decathlon";
		System.out.println("The brand is "+g23.brand);
		g23.cost=1600;
		System.out.println("The cost is "+g23.cost);
		g23.colour="Blue";
		System.out.println("The colour is "+g23.colour);
		g23.type="Sports";
		System.out.println("The type is "+g23.type);
		g23.lensType="UV Protection";
		System.out.println("The lens type is "+g23.lensType);
		g23.frameMaterial="Fiber";
		System.out.println("The frame material is "+g23.frameMaterial);
		g23.isPolarized=true;
		System.out.println("Polarized: "+g23.isPolarized);
		g23.size="Medium";
		System.out.println("The size is "+g23.size);

		Goggles g24 = new Goggles();
		g24.brand="Speedo";
		System.out.println("The brand is "+g24.brand);
		g24.cost=900;
		System.out.println("The cost is "+g24.cost);
		g24.colour="Black";
		System.out.println("The colour is "+g24.colour);
		g24.type="Swimming";
		System.out.println("The type is "+g24.type);
		g24.lensType="Anti-fog";
		System.out.println("The lens type is "+g24.lensType);
		g24.frameMaterial="Rubber";
		System.out.println("The frame material is "+g24.frameMaterial);
		g24.isPolarized=false;
		System.out.println("Polarized: "+g24.isPolarized);
		g24.size="Small";
		System.out.println("The size is "+g24.size);

		Goggles g25 = new Goggles();
		g25.brand="Arena";
		System.out.println("The brand is "+g25.brand);
		g25.cost=1100;
		System.out.println("The cost is "+g25.cost);
		g25.colour="Blue";
		System.out.println("The colour is "+g25.colour);
		g25.type="Swimming";
		System.out.println("The type is "+g25.type);
		g25.lensType="Anti-fog";
		System.out.println("The lens type is "+g25.lensType);
		g25.frameMaterial="Rubber";
		System.out.println("The frame material is "+g25.frameMaterial);
		g25.isPolarized=false;
		System.out.println("Polarized: "+g25.isPolarized);
		g25.size="Small";
		System.out.println("The size is "+g25.size);

		Goggles g26 = new Goggles();
		g26.brand="Zara";
		System.out.println("The brand is "+g26.brand);
		g26.cost=2000;
		System.out.println("The cost is "+g26.cost);
		g26.colour="Brown";
		System.out.println("The colour is "+g26.colour);
		g26.type="Fashion";
		System.out.println("The type is "+g26.type);
		g26.lensType="UV";
		System.out.println("The lens type is "+g26.lensType);
		g26.frameMaterial="Plastic";
		System.out.println("The frame material is "+g26.frameMaterial);
		g26.isPolarized=false;
		System.out.println("Polarized: "+g26.isPolarized);
		g26.size="Medium";
		System.out.println("The size is "+g26.size);

		Goggles g27 = new Goggles();
		g27.brand="H&M";
		System.out.println("The brand is "+g27.brand);
		g27.cost=1300;
		System.out.println("The cost is "+g27.cost);
		g27.colour="Black";
		System.out.println("The colour is "+g27.colour);
		g27.type="Fashion";
		System.out.println("The type is "+g27.type);
		g27.lensType="Anti-glare";
		System.out.println("The lens type is "+g27.lensType);
		g27.frameMaterial="Plastic";
		System.out.println("The frame material is "+g27.frameMaterial);
		g27.isPolarized=false;
		System.out.println("Polarized: "+g27.isPolarized);
		g27.size="Medium";
		System.out.println("The size is "+g27.size);

		Goggles g28 = new Goggles();
		g28.brand="Forever21";
		System.out.println("The brand is "+g28.brand);
		g28.cost=1200;
		System.out.println("The cost is "+g28.cost);
		g28.colour="Pink";
		System.out.println("The colour is "+g28.colour);
		g28.type="Fashion";
		System.out.println("The type is "+g28.type);
		g28.lensType="UV";
		System.out.println("The lens type is "+g28.lensType);
		g28.frameMaterial="Plastic";
		System.out.println("The frame material is "+g28.frameMaterial);
		g28.isPolarized=false;
		System.out.println("Polarized: "+g28.isPolarized);
		g28.size="Small";
		System.out.println("The size is "+g28.size);

		Goggles g29 = new Goggles();
		g29.brand="Urban Style";
		System.out.println("The brand is "+g29.brand);
		g29.cost=1000;
		System.out.println("The cost is "+g29.cost);
		g29.colour="Grey";
		System.out.println("The colour is "+g29.colour);
		g29.type="Sunglasses";
		System.out.println("The type is "+g29.type);
		g29.lensType="UV";
		System.out.println("The lens type is "+g29.lensType);
		g29.frameMaterial="Plastic";
		System.out.println("The frame material is "+g29.frameMaterial);
		g29.isPolarized=false;
		System.out.println("Polarized: "+g29.isPolarized);
		g29.size="Medium";
		System.out.println("The size is "+g29.size);

		Goggles g30 = new Goggles();
		g30.brand="Elite Vision";
		System.out.println("The brand is "+g30.brand);
		g30.cost=2200;
		System.out.println("The cost is "+g30.cost);
		g30.colour="Black";
		System.out.println("The colour is "+g30.colour);
		g30.type="Sunglasses";
		System.out.println("The type is "+g30.type);
		g30.lensType="Polarized";
		System.out.println("The lens type is "+g30.lensType);
		g30.frameMaterial="Metal";
		System.out.println("The frame material is "+g30.frameMaterial);
		g30.isPolarized=true;
		System.out.println("Polarized: "+g30.isPolarized);
		g30.size="Large";
		System.out.println("The size is "+g30.size);
	}
}