class GoldExec
{
	public static void main(String[] args)
	{
		Gold g1 = new Gold();
		g1.brand="Tanishq";
		System.out.println("The brand is "+g1.brand);
		g1.pricePerGram=6000;
		System.out.println("Price per gram is "+g1.pricePerGram);
		g1.weight=10;
		System.out.println("Weight is "+g1.weight);
		g1.purity="22K";
		System.out.println("Purity is "+g1.purity);
		g1.type="Ring";
		System.out.println("Type is "+g1.type);
		g1.colour="Yellow";
		System.out.println("Colour is "+g1.colour);
		g1.isHallmarked=true;
		System.out.println("Hallmarked: "+g1.isHallmarked);
		g1.design="Simple";
		System.out.println("Design is "+g1.design);

		Gold g2 = new Gold();
		g2.brand="Malabar";
		System.out.println("The brand is "+g2.brand);
		g2.pricePerGram=6100;
		System.out.println("Price per gram is "+g2.pricePerGram);
		g2.weight=15;
		System.out.println("Weight is "+g2.weight);
		g2.purity="24K";
		System.out.println("Purity is "+g2.purity);
		g2.type="Chain";
		System.out.println("Type is "+g2.type);
		g2.colour="Yellow";
		System.out.println("Colour is "+g2.colour);
		g2.isHallmarked=true;
		System.out.println("Hallmarked: "+g2.isHallmarked);
		g2.design="Antique";
		System.out.println("Design is "+g2.design);

		Gold g3 = new Gold();
		g3.brand="Kalyan";
		System.out.println("The brand is "+g3.brand);
		g3.pricePerGram=6050;
		System.out.println("Price per gram is "+g3.pricePerGram);
		g3.weight=20;
		System.out.println("Weight is "+g3.weight);
		g3.purity="22K";
		System.out.println("Purity is "+g3.purity);
		g3.type="Necklace";
		System.out.println("Type is "+g3.type);
		g3.colour="Gold";
		System.out.println("Colour is "+g3.colour);
		g3.isHallmarked=true;
		System.out.println("Hallmarked: "+g3.isHallmarked);
		g3.design="Designer";
		System.out.println("Design is "+g3.design);

		Gold g4 = new Gold();
		g4.brand="Joyalukkas";
		System.out.println("The brand is "+g4.brand);
		g4.pricePerGram=6200;
		System.out.println("Price per gram is "+g4.pricePerGram);
		g4.weight=12;
		System.out.println("Weight is "+g4.weight);
		g4.purity="22K";
		System.out.println("Purity is "+g4.purity);
		g4.type="Bangles";
		System.out.println("Type is "+g4.type);
		g4.colour="Yellow";
		System.out.println("Colour is "+g4.colour);
		g4.isHallmarked=true;
		System.out.println("Hallmarked: "+g4.isHallmarked);
		g4.design="Traditional";
		System.out.println("Design is "+g4.design);

		Gold g5 = new Gold();
		g5.brand="Bluestone";
		System.out.println("The brand is "+g5.brand);
		g5.pricePerGram=6300;
		System.out.println("Price per gram is "+g5.pricePerGram);
		g5.weight=8;
		System.out.println("Weight is "+g5.weight);
		g5.purity="18K";
		System.out.println("Purity is "+g5.purity);
		g5.type="Ring";
		System.out.println("Type is "+g5.type);
		g5.colour="Rose";
		System.out.println("Colour is "+g5.colour);
		g5.isHallmarked=true;
		System.out.println("Hallmarked: "+g5.isHallmarked);
		g5.design="Modern";
		System.out.println("Design is "+g5.design);

		Gold g6 = new Gold();
		g6.brand="CaratLane";
		System.out.println("The brand is "+g6.brand);
		g6.pricePerGram=6400;
		System.out.println("Price per gram is "+g6.pricePerGram);
		g6.weight=18;
		System.out.println("Weight is "+g6.weight);
		g6.purity="22K";
		System.out.println("Purity is "+g6.purity);
		g6.type="Chain";
		System.out.println("Type is "+g6.type);
		g6.colour="White";
		System.out.println("Colour is "+g6.colour);
		g6.isHallmarked=true;
		System.out.println("Hallmarked: "+g6.isHallmarked);
		g6.design="Stylish";
		System.out.println("Design is "+g6.design);

		Gold g7 = new Gold();
		g7.brand="TBZ";
		System.out.println("The brand is "+g7.brand);
		g7.pricePerGram=6000;
		System.out.println("Price per gram is "+g7.pricePerGram);
		g7.weight=25;
		System.out.println("Weight is "+g7.weight);
		g7.purity="24K";
		System.out.println("Purity is "+g7.purity);
		g7.type="Coin";
		System.out.println("Type is "+g7.type);
		g7.colour="Yellow";
		System.out.println("Colour is "+g7.colour);
		g7.isHallmarked=true;
		System.out.println("Hallmarked: "+g7.isHallmarked);
		g7.design="Plain";
		System.out.println("Design is "+g7.design);

		Gold g8 = new Gold();
		g8.brand="Senco";
		System.out.println("The brand is "+g8.brand);
		g8.pricePerGram=6100;
		System.out.println("Price per gram is "+g8.pricePerGram);
		g8.weight=14;
		System.out.println("Weight is "+g8.weight);
		g8.purity="22K";
		System.out.println("Purity is "+g8.purity);
		g8.type="Earrings";
		System.out.println("Type is "+g8.type);
		g8.colour="Gold";
		System.out.println("Colour is "+g8.colour);
		g8.isHallmarked=true;
		System.out.println("Hallmarked: "+g8.isHallmarked);
		g8.design="Simple";
		System.out.println("Design is "+g8.design);

		Gold g9 = new Gold();
		g9.brand="Reliance";
		System.out.println("The brand is "+g9.brand);
		g9.pricePerGram=6050;
		System.out.println("Price per gram is "+g9.pricePerGram);
		g9.weight=16;
		System.out.println("Weight is "+g9.weight);
		g9.purity="22K";
		System.out.println("Purity is "+g9.purity);
		g9.type="Pendant";
		System.out.println("Type is "+g9.type);
		g9.colour="Yellow";
		System.out.println("Colour is "+g9.colour);
		g9.isHallmarked=true;
		System.out.println("Hallmarked: "+g9.isHallmarked);
		g9.design="Modern";
		System.out.println("Design is "+g9.design);

		Gold g10 = new Gold();
		g10.brand="Local Jeweller";
		System.out.println("The brand is "+g10.brand);
		g10.pricePerGram=5900;
		System.out.println("Price per gram is "+g10.pricePerGram);
		g10.weight=10;
		System.out.println("Weight is "+g10.weight);
		g10.purity="22K";
		System.out.println("Purity is "+g10.purity);
		g10.type="Ring";
		System.out.println("Type is "+g10.type);
		g10.colour="Yellow";
		System.out.println("Colour is "+g10.colour);
		g10.isHallmarked=false;
		System.out.println("Hallmarked: "+g10.isHallmarked);
		g10.design="Simple";
		System.out.println("Design is "+g10.design);
		
				Gold g11 = new Gold();
		g11.brand="Amrapali";
		System.out.println("The brand is "+g11.brand);
		g11.pricePerGram=6500;
		System.out.println("Price per gram is "+g11.pricePerGram);
		g11.weight=22;
		System.out.println("Weight is "+g11.weight);
		g11.purity="22K";
		System.out.println("Purity is "+g11.purity);
		g11.type="Necklace";
		System.out.println("Type is "+g11.type);
		g11.colour="Gold";
		System.out.println("Colour is "+g11.colour);
		g11.isHallmarked=true;
		System.out.println("Hallmarked: "+g11.isHallmarked);
		g11.design="Antique";
		System.out.println("Design is "+g11.design);

		Gold g12 = new Gold();
		g12.brand="Orra";
		System.out.println("The brand is "+g12.brand);
		g12.pricePerGram=6450;
		System.out.println("Price per gram is "+g12.pricePerGram);
		g12.weight=19;
		System.out.println("Weight is "+g12.weight);
		g12.purity="18K";
		System.out.println("Purity is "+g12.purity);
		g12.type="Ring";
		System.out.println("Type is "+g12.type);
		g12.colour="White";
		System.out.println("Colour is "+g12.colour);
		g12.isHallmarked=true;
		System.out.println("Hallmarked: "+g12.isHallmarked);
		g12.design="Diamond";
		System.out.println("Design is "+g12.design);

		Gold g13 = new Gold();
		g13.brand="Zoya";
		System.out.println("The brand is "+g13.brand);
		g13.pricePerGram=7000;
		System.out.println("Price per gram is "+g13.pricePerGram);
		g13.weight=30;
		System.out.println("Weight is "+g13.weight);
		g13.purity="24K";
		System.out.println("Purity is "+g13.purity);
		g13.type="Necklace";
		System.out.println("Type is "+g13.type);
		g13.colour="Gold";
		System.out.println("Colour is "+g13.colour);
		g13.isHallmarked=true;
		System.out.println("Hallmarked: "+g13.isHallmarked);
		g13.design="Luxury";
		System.out.println("Design is "+g13.design);

		Gold g14 = new Gold();
		g14.brand="Mejuri";
		System.out.println("The brand is "+g14.brand);
		g14.pricePerGram=6200;
		System.out.println("Price per gram is "+g14.pricePerGram);
		g14.weight=9;
		System.out.println("Weight is "+g14.weight);
		g14.purity="18K";
		System.out.println("Purity is "+g14.purity);
		g14.type="Bracelet";
		System.out.println("Type is "+g14.type);
		g14.colour="Rose";
		System.out.println("Colour is "+g14.colour);
		g14.isHallmarked=true;
		System.out.println("Hallmarked: "+g14.isHallmarked);
		g14.design="Modern";
		System.out.println("Design is "+g14.design);

		Gold g15 = new Gold();
		g15.brand="Pandora";
		System.out.println("The brand is "+g15.brand);
		g15.pricePerGram=6800;
		System.out.println("Price per gram is "+g15.pricePerGram);
		g15.weight=11;
		System.out.println("Weight is "+g15.weight);
		g15.purity="18K";
		System.out.println("Purity is "+g15.purity);
		g15.type="Charm";
		System.out.println("Type is "+g15.type);
		g15.colour="Gold";
		System.out.println("Colour is "+g15.colour);
		g15.isHallmarked=true;
		System.out.println("Hallmarked: "+g15.isHallmarked);
		g15.design="Cute";
		System.out.println("Design is "+g15.design);

		Gold g16 = new Gold();
		g16.brand="BlueStone X";
		System.out.println("The brand is "+g16.brand);
		g16.pricePerGram=6400;
		System.out.println("Price per gram is "+g16.pricePerGram);
		g16.weight=17;
		System.out.println("Weight is "+g16.weight);
		g16.purity="22K";
		System.out.println("Purity is "+g16.purity);
		g16.type="Chain";
		System.out.println("Type is "+g16.type);
		g16.colour="White";
		System.out.println("Colour is "+g16.colour);
		g16.isHallmarked=true;
		System.out.println("Hallmarked: "+g16.isHallmarked);
		g16.design="Stylish";
		System.out.println("Design is "+g16.design);

		Gold g17 = new Gold();
		g17.brand="Kalyan X";
		System.out.println("The brand is "+g17.brand);
		g17.pricePerGram=6300;
		System.out.println("Price per gram is "+g17.pricePerGram);
		g17.weight=21;
		System.out.println("Weight is "+g17.weight);
		g17.purity="22K";
		System.out.println("Purity is "+g17.purity);
		g17.type="Bangles";
		System.out.println("Type is "+g17.type);
		g17.colour="Yellow";
		System.out.println("Colour is "+g17.colour);
		g17.isHallmarked=true;
		System.out.println("Hallmarked: "+g17.isHallmarked);
		g17.design="Traditional";
		System.out.println("Design is "+g17.design);

		Gold g18 = new Gold();
		g18.brand="Malabar X";
		System.out.println("The brand is "+g18.brand);
		g18.pricePerGram=6250;
		System.out.println("Price per gram is "+g18.pricePerGram);
		g18.weight=13;
		System.out.println("Weight is "+g18.weight);
		g18.purity="22K";
		System.out.println("Purity is "+g18.purity);
		g18.type="Ring";
		System.out.println("Type is "+g18.type);
		g18.colour="Gold";
		System.out.println("Colour is "+g18.colour);
		g18.isHallmarked=true;
		System.out.println("Hallmarked: "+g18.isHallmarked);
		g18.design="Simple";
		System.out.println("Design is "+g18.design);

		Gold g19 = new Gold();
		g19.brand="Tanishq X";
		System.out.println("The brand is "+g19.brand);
		g19.pricePerGram=6600;
		System.out.println("Price per gram is "+g19.pricePerGram);
		g19.weight=24;
		System.out.println("Weight is "+g19.weight);
		g19.purity="24K";
		System.out.println("Purity is "+g19.purity);
		g19.type="Coin";
		System.out.println("Type is "+g19.type);
		g19.colour="Gold";
		System.out.println("Colour is "+g19.colour);
		g19.isHallmarked=true;
		System.out.println("Hallmarked: "+g19.isHallmarked);
		g19.design="Plain";
		System.out.println("Design is "+g19.design);

		Gold g20 = new Gold();
		g20.brand="Local Shop";
		System.out.println("The brand is "+g20.brand);
		g20.pricePerGram=5800;
		System.out.println("Price per gram is "+g20.pricePerGram);
		g20.weight=10;
		System.out.println("Weight is "+g20.weight);
		g20.purity="20K";
		System.out.println("Purity is "+g20.purity);
		g20.type="Chain";
		System.out.println("Type is "+g20.type);
		g20.colour="Yellow";
		System.out.println("Colour is "+g20.colour);
		g20.isHallmarked=false;
		System.out.println("Hallmarked: "+g20.isHallmarked);
		g20.design="Basic";
		System.out.println("Design is "+g20.design);
		
				Gold g21 = new Gold();
		g21.brand="Street Gold";
		System.out.println("The brand is "+g21.brand);
		g21.pricePerGram=5500;
		System.out.println("Price per gram is "+g21.pricePerGram);
		g21.weight=8;
		System.out.println("Weight is "+g21.weight);
		g21.purity="18K";
		System.out.println("Purity is "+g21.purity);
		g21.type="Ring";
		System.out.println("Type is "+g21.type);
		g21.colour="Rose";
		System.out.println("Colour is "+g21.colour);
		g21.isHallmarked=false;
		System.out.println("Hallmarked: "+g21.isHallmarked);
		g21.design="Modern";
		System.out.println("Design is "+g21.design);

		Gold g22 = new Gold();
		g22.brand="Silver Gold Mix";
		System.out.println("The brand is "+g22.brand);
		g22.pricePerGram=5600;
		System.out.println("Price per gram is "+g22.pricePerGram);
		g22.weight=9;
		System.out.println("Weight is "+g22.weight);
		g22.purity="18K";
		System.out.println("Purity is "+g22.purity);
		g22.type="Pendant";
		System.out.println("Type is "+g22.type);
		g22.colour="White";
		System.out.println("Colour is "+g22.colour);
		g22.isHallmarked=false;
		System.out.println("Hallmarked: "+g22.isHallmarked);
		g22.design="Stylish";
		System.out.println("Design is "+g22.design);

		Gold g23 = new Gold();
		g23.brand="Gold Art";
		System.out.println("The brand is "+g23.brand);
		g23.pricePerGram=6700;
		System.out.println("Price per gram is "+g23.pricePerGram);
		g23.weight=27;
		System.out.println("Weight is "+g23.weight);
		g23.purity="24K";
		System.out.println("Purity is "+g23.purity);
		g23.type="Necklace";
		System.out.println("Type is "+g23.type);
		g23.colour="Gold";
		System.out.println("Colour is "+g23.colour);
		g23.isHallmarked=true;
		System.out.println("Hallmarked: "+g23.isHallmarked);
		g23.design="Designer";
		System.out.println("Design is "+g23.design);

		Gold g24 = new Gold();
		g24.brand="Diamond Hub";
		System.out.println("The brand is "+g24.brand);
		g24.pricePerGram=6900;
		System.out.println("Price per gram is "+g24.pricePerGram);
		g24.weight=12;
		System.out.println("Weight is "+g24.weight);
		g24.purity="22K";
		System.out.println("Purity is "+g24.purity);
		g24.type="Ring";
		System.out.println("Type is "+g24.type);
		g24.colour="White";
		System.out.println("Colour is "+g24.colour);
		g24.isHallmarked=true;
		System.out.println("Hallmarked: "+g24.isHallmarked);
		g24.design="Diamond";
		System.out.println("Design is "+g24.design);

		Gold g25 = new Gold();
		g25.brand="Fashion Gold";
		System.out.println("The brand is "+g25.brand);
		g25.pricePerGram=5400;
		System.out.println("Price per gram is "+g25.pricePerGram);
		g25.weight=7;
		System.out.println("Weight is "+g25.weight);
		g25.purity="18K";
		System.out.println("Purity is "+g25.purity);
		g25.type="Bracelet";
		System.out.println("Type is "+g25.type);
		g25.colour="Rose";
		System.out.println("Colour is "+g25.colour);
		g25.isHallmarked=false;
		System.out.println("Hallmarked: "+g25.isHallmarked);
		g25.design="Trendy";
		System.out.println("Design is "+g25.design);

		Gold g26 = new Gold();
		g26.brand="Classic Gold";
		System.out.println("The brand is "+g26.brand);
		g26.pricePerGram=6200;
		System.out.println("Price per gram is "+g26.pricePerGram);
		g26.weight=16;
		System.out.println("Weight is "+g26.weight);
		g26.purity="22K";
		System.out.println("Purity is "+g26.purity);
		g26.type="Chain";
		System.out.println("Type is "+g26.type);
		g26.colour="Yellow";
		System.out.println("Colour is "+g26.colour);
		g26.isHallmarked=true;
		System.out.println("Hallmarked: "+g26.isHallmarked);
		g26.design="Simple";
		System.out.println("Design is "+g26.design);

		Gold g27 = new Gold();
		g27.brand="Modern Gold";
		System.out.println("The brand is "+g27.brand);
		g27.pricePerGram=6100;
		System.out.println("Price per gram is "+g27.pricePerGram);
		g27.weight=14;
		System.out.println("Weight is "+g27.weight);
		g27.purity="22K";
		System.out.println("Purity is "+g27.purity);
		g27.type="Pendant";
		System.out.println("Type is "+g27.type);
		g27.colour="White";
		System.out.println("Colour is "+g27.colour);
		g27.isHallmarked=true;
		System.out.println("Hallmarked: "+g27.isHallmarked);
		g27.design="Modern";
		System.out.println("Design is "+g27.design);

		Gold g28 = new Gold();
		g28.brand="Royal Gold";
		System.out.println("The brand is "+g28.brand);
		g28.pricePerGram=7000;
		System.out.println("Price per gram is "+g28.pricePerGram);
		g28.weight=28;
		System.out.println("Weight is "+g28.weight);
		g28.purity="24K";
		System.out.println("Purity is "+g28.purity);
		g28.type="Necklace";
		System.out.println("Type is "+g28.type);
		g28.colour="Gold";
		System.out.println("Colour is "+g28.colour);
		g28.isHallmarked=true;
		System.out.println("Hallmarked: "+g28.isHallmarked);
		g28.design="Royal";
		System.out.println("Design is "+g28.design);

		Gold g29 = new Gold();
		g29.brand="Elite Gold";
		System.out.println("The brand is "+g29.brand);
		g29.pricePerGram=6800;
		System.out.println("Price per gram is "+g29.pricePerGram);
		g29.weight=23;
		System.out.println("Weight is "+g29.weight);
		g29.purity="22K";
		System.out.println("Purity is "+g29.purity);
		g29.type="Bangles";
		System.out.println("Type is "+g29.type);
		g29.colour="Yellow";
		System.out.println("Colour is "+g29.colour);
		g29.isHallmarked=true;
		System.out.println("Hallmarked: "+g29.isHallmarked);
		g29.design="Designer";
		System.out.println("Design is "+g29.design);

		Gold g30 = new Gold();
		g30.brand="Simple Gold";
		System.out.println("The brand is "+g30.brand);
		g30.pricePerGram=5500;
		System.out.println("Price per gram is "+g30.pricePerGram);
		g30.weight=10;
		System.out.println("Weight is "+g30.weight);
		g30.purity="20K";
		System.out.println("Purity is "+g30.purity);
		g30.type="Ring";
		System.out.println("Type is "+g30.type);
		g30.colour="Yellow";
		System.out.println("Colour is "+g30.colour);
		g30.isHallmarked=false;
		System.out.println("Hallmarked: "+g30.isHallmarked);
		g30.design="Simple";
		System.out.println("Design is "+g30.design);
	}
}