class LightExec
{
	public static void main(String ref[])
	{
		Light light = new Light();
		light.brand= "AKway";
		System.out.println("The brand of a light is "+light.brand);
		light.cost = 4500;
		System.out.println("the cost of a ight is "+light.cost);
		light.type = "decorative";
		System.out.println("The type of a llight is "+light.type);
		light.colour = "beach";
		System.out.println("The colour of a light is "+light.colour);
		light.powerSource = "Electricity";
		System.out.println("The source of light is "+light.powerSource);
		light.productDimension = "26*26*10";
		System.out.println("The light dimension is "+light.productDimension);
		
				Light light1 = new Light();
		light1.brand="AKway";
		System.out.println("The brand of a light is "+light1.brand);
		light1.cost=4500;
		System.out.println("The cost of a light is "+light1.cost);
		light1.type="decorative";
		System.out.println("The type of a light is "+light1.type);
		light1.colour="beige";
		System.out.println("The colour of a light is "+light1.colour);
		light1.powerSource="Electricity";
		System.out.println("The source of light is "+light1.powerSource);
		light1.productDimension="26*26*10";
		System.out.println("The light dimension is "+light1.productDimension);

		Light light2 = new Light();
		light2.brand="Philips";
		System.out.println("The brand of a light is "+light2.brand);
		light2.cost=3000;
		System.out.println("The cost of a light is "+light2.cost);
		light2.type="LED";
		System.out.println("The type of a light is "+light2.type);
		light2.colour="white";
		System.out.println("The colour of a light is "+light2.colour);
		light2.powerSource="Electricity";
		System.out.println("The source of light is "+light2.powerSource);
		light2.productDimension="20*20*8";
		System.out.println("The light dimension is "+light2.productDimension);

		Light light3 = new Light();
		light3.brand="Havells";
		System.out.println("The brand of a light is "+light3.brand);
		light3.cost=2500;
		System.out.println("The cost of a light is "+light3.cost);
		light3.type="Tube";
		System.out.println("The type of a light is "+light3.type);
		light3.colour="cool white";
		System.out.println("The colour of a light is "+light3.colour);
		light3.powerSource="Electricity";
		System.out.println("The source of light is "+light3.powerSource);
		light3.productDimension="30*5*5";
		System.out.println("The light dimension is "+light3.productDimension);

		Light light4 = new Light();
		light4.brand="Syska";
		System.out.println("The brand of a light is "+light4.brand);
		light4.cost=2000;
		System.out.println("The cost of a light is "+light4.cost);
		light4.type="LED";
		System.out.println("The type of a light is "+light4.type);
		light4.colour="yellow";
		System.out.println("The colour of a light is "+light4.colour);
		light4.powerSource="Battery";
		System.out.println("The source of light is "+light4.powerSource);
		light4.productDimension="15*15*5";
		System.out.println("The light dimension is "+light4.productDimension);

		Light light5 = new Light();
		light5.brand="Wipro";
		System.out.println("The brand of a light is "+light5.brand);
		light5.cost=1800;
		System.out.println("The cost of a light is "+light5.cost);
		light5.type="Bulb";
		System.out.println("The type of a light is "+light5.type);
		light5.colour="white";
		System.out.println("The colour of a light is "+light5.colour);
		light5.powerSource="Electricity";
		System.out.println("The source of light is "+light5.powerSource);
		light5.productDimension="10*10*5";
		System.out.println("The light dimension is "+light5.productDimension);

		Light light6 = new Light();
		light6.brand="Bajaj";
		System.out.println("The brand of a light is "+light6.brand);
		light6.cost=2200;
		System.out.println("The cost of a light is "+light6.cost);
		light6.type="LED";
		System.out.println("The type of a light is "+light6.type);
		light6.colour="blue";
		System.out.println("The colour of a light is "+light6.colour);
		light6.powerSource="Electricity";
		System.out.println("The source of light is "+light6.powerSource);
		light6.productDimension="12*12*6";
		System.out.println("The light dimension is "+light6.productDimension);

		Light light7 = new Light();
		light7.brand="Eveready";
		System.out.println("The brand of a light is "+light7.brand);
		light7.cost=900;
		System.out.println("The cost of a light is "+light7.cost);
		light7.type="Torch";
		System.out.println("The type of a light is "+light7.type);
		light7.colour="black";
		System.out.println("The colour of a light is "+light7.colour);
		light7.powerSource="Battery";
		System.out.println("The source of light is "+light7.powerSource);
		light7.productDimension="8*8*20";
		System.out.println("The light dimension is "+light7.productDimension);

		Light light8 = new Light();
		light8.brand="Orient";
		System.out.println("The brand of a light is "+light8.brand);
		light8.cost=2100;
		System.out.println("The cost of a light is "+light8.cost);
		light8.type="LED";
		System.out.println("The type of a light is "+light8.type);
		light8.colour="white";
		System.out.println("The colour of a light is "+light8.colour);
		light8.powerSource="Electricity";
		System.out.println("The source of light is "+light8.powerSource);
		light8.productDimension="14*14*6";
		System.out.println("The light dimension is "+light8.productDimension);

		Light light9 = new Light();
		light9.brand="Crompton";
		System.out.println("The brand of a light is "+light9.brand);
		light9.cost=2600;
		System.out.println("The cost of a light is "+light9.cost);
		light9.type="Lamp";
		System.out.println("The type of a light is "+light9.type);
		light9.colour="gold";
		System.out.println("The colour of a light is "+light9.colour);
		light9.powerSource="Electricity";
		System.out.println("The source of light is "+light9.powerSource);
		light9.productDimension="18*18*10";
		System.out.println("The light dimension is "+light9.productDimension);

		Light light10 = new Light();
		light10.brand="Surya";
		System.out.println("The brand of a light is "+light10.brand);
		light10.cost=1700;
		System.out.println("The cost of a light is "+light10.cost);
		light10.type="Bulb";
		System.out.println("The type of a light is "+light10.type);
		light10.colour="white";
		System.out.println("The colour of a light is "+light10.colour);
		light10.powerSource="Electricity";
		System.out.println("The source of light is "+light10.powerSource);
		light10.productDimension="9*9*4";
		System.out.println("The light dimension is "+light10.productDimension);

		Light light11 = new Light();
		light11.brand="Panasonic";
		System.out.println("The brand of a light is "+light11.brand);
		light11.cost=2800;
		System.out.println("The cost of a light is "+light11.cost);
		light11.type="LED";
		System.out.println("The type of a light is "+light11.type);
		light11.colour="warm white";
		System.out.println("The colour of a light is "+light11.colour);
		light11.powerSource="Electricity";
		System.out.println("The source of light is "+light11.powerSource);
		light11.productDimension="16*16*7";
		System.out.println("The light dimension is "+light11.productDimension);

		Light light12 = new Light();
		light12.brand="LG";
		System.out.println("The brand of a light is "+light12.brand);
		light12.cost=3200;
		System.out.println("The cost of a light is "+light12.cost);
		light12.type="Smart LED";
		System.out.println("The type of a light is "+light12.type);
		light12.colour="multicolor";
		System.out.println("The colour of a light is "+light12.colour);
		light12.powerSource="Electricity";
		System.out.println("The source of light is "+light12.powerSource);
		light12.productDimension="18*18*8";
		System.out.println("The light dimension is "+light12.productDimension);

		Light light13 = new Light();
		light13.brand="Mi";
		System.out.println("The brand of a light is "+light13.brand);
		light13.cost=1500;
		System.out.println("The cost of a light is "+light13.cost);
		light13.type="LED";
		System.out.println("The type of a light is "+light13.type);
		light13.colour="white";
		System.out.println("The colour of a light is "+light13.colour);
		light13.powerSource="Electricity";
		System.out.println("The source of light is "+light13.powerSource);
		light13.productDimension="12*12*5";
		System.out.println("The light dimension is "+light13.productDimension);

		Light light14 = new Light();
		light14.brand="Realme";
		System.out.println("The brand of a light is "+light14.brand);
		light14.cost=1400;
		System.out.println("The cost of a light is "+light14.cost);
		light14.type="LED";
		System.out.println("The type of a light is "+light14.type);
		light14.colour="white";
		System.out.println("The colour of a light is "+light14.colour);
		light14.powerSource="Electricity";
		System.out.println("The source of light is "+light14.powerSource);
		light14.productDimension="11*11*5";
		System.out.println("The light dimension is "+light14.productDimension);

		Light light15 = new Light();
		light15.brand="Boat";
		System.out.println("The brand of a light is "+light15.brand);
		light15.cost=1200;
		System.out.println("The cost of a light is "+light15.cost);
		light15.type="Portable";
		System.out.println("The type of a light is "+light15.type);
		light15.colour="black";
		System.out.println("The colour of a light is "+light15.colour);
		light15.powerSource="Battery";
		System.out.println("The source of light is "+light15.powerSource);
		light15.productDimension="10*10*6";
		System.out.println("The light dimension is "+light15.productDimension);

		Light light16 = new Light();
		light16.brand="Sony";
		System.out.println("The brand of a light is "+light16.brand);
		light16.cost=3500;
		System.out.println("The cost of a light is "+light16.cost);
		light16.type="LED";
		System.out.println("The type of a light is "+light16.type);
		light16.colour="white";
		System.out.println("The colour of a light is "+light16.colour);
		light16.powerSource="Electricity";
		System.out.println("The source of light is "+light16.powerSource);
		light16.productDimension="17*17*7";
		System.out.println("The light dimension is "+light16.productDimension);

		Light light17 = new Light();
		light17.brand="Samsung";
		System.out.println("The brand of a light is "+light17.brand);
		light17.cost=3600;
		System.out.println("The cost of a light is "+light17.cost);
		light17.type="Smart LED";
		System.out.println("The type of a light is "+light17.type);
		light17.colour="multicolor";
		System.out.println("The colour of a light is "+light17.colour);
		light17.powerSource="Electricity";
		System.out.println("The source of light is "+light17.powerSource);
		light17.productDimension="19*19*9";
		System.out.println("The light dimension is "+light17.productDimension);

		Light light18 = new Light();
		light18.brand="Anchor";
		System.out.println("The brand of a light is "+light18.brand);
		light18.cost=1900;
		System.out.println("The cost of a light is "+light18.cost);
		light18.type="LED";
		System.out.println("The type of a light is "+light18.type);
		light18.colour="white";
		System.out.println("The colour of a light is "+light18.colour);
		light18.powerSource="Electricity";
		System.out.println("The source of light is "+light18.powerSource);
		light18.productDimension="13*13*6";
		System.out.println("The light dimension is "+light18.productDimension);

		Light light19 = new Light();
		light19.brand="Usha";
		System.out.println("The brand of a light is "+light19.brand);
		light19.cost=1600;
		System.out.println("The cost of a light is "+light19.cost);
		light19.type="Bulb";
		System.out.println("The type of a light is "+light19.type);
		light19.colour="yellow";
		System.out.println("The colour of a light is "+light19.colour);
		light19.powerSource="Electricity";
		System.out.println("The source of light is "+light19.powerSource);
		light19.productDimension="9*9*4";
		System.out.println("The light dimension is "+light19.productDimension);

		Light light20 = new Light();
		light20.brand="GE";
		System.out.println("The brand of a light is "+light20.brand);
		light20.cost=3100;
		System.out.println("The cost of a light is "+light20.cost);
		light20.type="LED";
		System.out.println("The type of a light is "+light20.type);
		light20.colour="white";
		System.out.println("The colour of a light is "+light20.colour);
		light20.powerSource="Electricity";
		System.out.println("The source of light is "+light20.powerSource);
		light20.productDimension="18*18*8";
		System.out.println("The light dimension is "+light20.productDimension);

		Light light21 = new Light();
		light21.brand="Halonix";
		System.out.println("The brand of a light is "+light21.brand);
		light21.cost=2100;
		System.out.println("The cost of a light is "+light21.cost);
		light21.type="LED";
		System.out.println("The type of a light is "+light21.type);
		light21.colour="white";
		System.out.println("The colour of a light is "+light21.colour);
		light21.powerSource="Electricity";
		System.out.println("The source of light is "+light21.powerSource);
		light21.productDimension="15*15*7";
		System.out.println("The light dimension is "+light21.productDimension);

		Light light22 = new Light();
		light22.brand="Opple";
		System.out.println("The brand of a light is "+light22.brand);
		light22.cost=2300;
		System.out.println("The cost of a light is "+light22.cost);
		light22.type="LED";
		System.out.println("The type of a light is "+light22.type);
		light22.colour="white";
		System.out.println("The colour of a light is "+light22.colour);
		light22.powerSource="Electricity";
		System.out.println("The source of light is "+light22.powerSource);
		light22.productDimension="16*16*6";
		System.out.println("The light dimension is "+light22.productDimension);

		Light light23 = new Light();
		light23.brand="Syslite";
		System.out.println("The brand of a light is "+light23.brand);
		light23.cost=1400;
		System.out.println("The cost of a light is "+light23.cost);
		light23.type="Bulb";
		System.out.println("The type of a light is "+light23.type);
		light23.colour="yellow";
		System.out.println("The colour of a light is "+light23.colour);
		light23.powerSource="Electricity";
		System.out.println("The source of light is "+light23.powerSource);
		light23.productDimension="10*10*4";
		System.out.println("The light dimension is "+light23.productDimension);

		Light light24 = new Light();
		light24.brand="Impex";
		System.out.println("The brand of a light is "+light24.brand);
		light24.cost=1750;
		System.out.println("The cost of a light is "+light24.cost);
		light24.type="Lamp";
		System.out.println("The type of a light is "+light24.type);
		light24.colour="gold";
		System.out.println("The colour of a light is "+light24.colour);
		light24.powerSource="Electricity";
		System.out.println("The source of light is "+light24.powerSource);
		light24.productDimension="17*17*9";
		System.out.println("The light dimension is "+light24.productDimension);

		Light light25 = new Light();
		light25.brand="Murphy";
		System.out.println("The brand of a light is "+light25.brand);
		light25.cost=2600;
		System.out.println("The cost of a light is "+light25.cost);
		light25.type="LED";
		System.out.println("The type of a light is "+light25.type);
		light25.colour="white";
		System.out.println("The colour of a light is "+light25.colour);
		light25.powerSource="Electricity";
		System.out.println("The source of light is "+light25.powerSource);
		light25.productDimension="18*18*8";
		System.out.println("The light dimension is "+light25.productDimension);

		Light light26 = new Light();
		light26.brand="Everlight";
		System.out.println("The brand of a light is "+light26.brand);
		light26.cost=1900;
		System.out.println("The cost of a light is "+light26.cost);
		light26.type="LED";
		System.out.println("The type of a light is "+light26.type);
		light26.colour="white";
		System.out.println("The colour of a light is "+light26.colour);
		light26.powerSource="Electricity";
		System.out.println("The source of light is "+light26.powerSource);
		light26.productDimension="14*14*6";
		System.out.println("The light dimension is "+light26.productDimension);

		Light light27 = new Light();
		light27.brand="Bright";
		System.out.println("The brand of a light is "+light27.brand);
		light27.cost=1500;
		System.out.println("The cost of a light is "+light27.cost);
		light27.type="Bulb";
		System.out.println("The type of a light is "+light27.type);
		light27.colour="yellow";
		System.out.println("The colour of a light is "+light27.colour);
		light27.powerSource="Electricity";
		System.out.println("The source of light is "+light27.powerSource);
		light27.productDimension="10*10*4";
		System.out.println("The light dimension is "+light27.productDimension);

		Light light28 = new Light();
		light28.brand="Glow";
		System.out.println("The brand of a light is "+light28.brand);
		light28.cost=1700;
		System.out.println("The cost of a light is "+light28.cost);
		light28.type="Lamp";
		System.out.println("The type of a light is "+light28.type);
		light28.colour="white";
		System.out.println("The colour of a light is "+light28.colour);
		light28.powerSource="Electricity";
		System.out.println("The source of light is "+light28.powerSource);
		light28.productDimension="16*16*7";
		System.out.println("The light dimension is "+light28.productDimension);

		Light light29 = new Light();
		light29.brand="Nova";
		System.out.println("The brand of a light is "+light29.brand);
		light29.cost=2000;
		System.out.println("The cost of a light is "+light29.cost);
		light29.type="LED";
		System.out.println("The type of a light is "+light29.type);
		light29.colour="white";
		System.out.println("The colour of a light is "+light29.colour);
		light29.powerSource="Electricity";
		System.out.println("The source of light is "+light29.powerSource);
		light29.productDimension="15*15*6";
		System.out.println("The light dimension is "+light29.productDimension);

		Light light30 = new Light();
		light30.brand="Elite";
		System.out.println("The brand of a light is "+light30.brand);
		light30.cost=2800;
		System.out.println("The cost of a light is "+light30.cost);
		light30.type="LED";
		System.out.println("The type of a light is "+light30.type);
		light30.colour="white";
		System.out.println("The colour of a light is "+light30.colour);
		light30.powerSource="Electricity";
		System.out.println("The source of light is "+light30.powerSource);
		light30.productDimension="18*18*8";
		System.out.println("The light dimension is "+light30.productDimension);
	}
}


