class LipstickExec
{
	public static void main(String[] args)
	{
		Lipstick l1 = new Lipstick();
		l1.brand="Lakme";
		System.out.println("The brand is "+l1.brand);
		l1.cost=299;
		System.out.println("The cost is "+l1.cost);
		l1.shade="Red";
		System.out.println("The shade is "+l1.shade);
		l1.type="Matte";
		System.out.println("The type is "+l1.type);
		l1.finish="Matte";
		System.out.println("The finish is "+l1.finish);
		l1.isWaterproof=true;
		System.out.println("Waterproof: "+l1.isWaterproof);
		l1.weight=4.5;
		System.out.println("The weight is "+l1.weight);
		l1.expiryDate="12/2026";
		System.out.println("The expiry is "+l1.expiryDate);

		Lipstick l2 = new Lipstick();
		l2.brand="Maybelline";
		System.out.println("The brand is "+l2.brand);
		l2.cost=399;
		System.out.println("The cost is "+l2.cost);
		l2.shade="Pink";
		System.out.println("The shade is "+l2.shade);
		l2.type="Liquid";
		System.out.println("The type is "+l2.type);
		l2.finish="Glossy";
		System.out.println("The finish is "+l2.finish);
		l2.isWaterproof=true;
		System.out.println("Waterproof: "+l2.isWaterproof);
		l2.weight=5.0;
		System.out.println("The weight is "+l2.weight);
		l2.expiryDate="10/2026";
		System.out.println("The expiry is "+l2.expiryDate);

		Lipstick l3 = new Lipstick();
		l3.brand="MAC";
		System.out.println("The brand is "+l3.brand);
		l3.cost=1500;
		System.out.println("The cost is "+l3.cost);
		l3.shade="Nude";
		System.out.println("The shade is "+l3.shade);
		l3.type="Matte";
		System.out.println("The type is "+l3.type);
		l3.finish="Matte";
		System.out.println("The finish is "+l3.finish);
		l3.isWaterproof=false;
		System.out.println("Waterproof: "+l3.isWaterproof);
		l3.weight=4.0;
		System.out.println("The weight is "+l3.weight);
		l3.expiryDate="11/2026";
		System.out.println("The expiry is "+l3.expiryDate);

		Lipstick l4 = new Lipstick();
		l4.brand="Nykaa";
		System.out.println("The brand is "+l4.brand);
		l4.cost=499;
		System.out.println("The cost is "+l4.cost);
		l4.shade="Maroon";
		System.out.println("The shade is "+l4.shade);
		l4.type="Crayon";
		System.out.println("The type is "+l4.type);
		l4.finish="Satin";
		System.out.println("The finish is "+l4.finish);
		l4.isWaterproof=true;
		System.out.println("Waterproof: "+l4.isWaterproof);
		l4.weight=3.5;
		System.out.println("The weight is "+l4.weight);
		l4.expiryDate="09/2026";
		System.out.println("The expiry is "+l4.expiryDate);

		Lipstick l5 = new Lipstick();
		l5.brand="Colorbar";
		System.out.println("The brand is "+l5.brand);
		l5.cost=650;
		System.out.println("The cost is "+l5.cost);
		l5.shade="Coral";
		System.out.println("The shade is "+l5.shade);
		l5.type="Matte";
		System.out.println("The type is "+l5.type);
		l5.finish="Matte";
		System.out.println("The finish is "+l5.finish);
		l5.isWaterproof=true;
		System.out.println("Waterproof: "+l5.isWaterproof);
		l5.weight=4.2;
		System.out.println("The weight is "+l5.weight);
		l5.expiryDate="08/2026";
		System.out.println("The expiry is "+l5.expiryDate);

		Lipstick l6 = new Lipstick();
		l6.brand="Faces";
		System.out.println("The brand is "+l6.brand);
		l6.cost=599;
		System.out.println("The cost is "+l6.cost);
		l6.shade="Berry";
		System.out.println("The shade is "+l6.shade);
		l6.type="Liquid";
		System.out.println("The type is "+l6.type);
		l6.finish="Glossy";
		System.out.println("The finish is "+l6.finish);
		l6.isWaterproof=true;
		System.out.println("Waterproof: "+l6.isWaterproof);
		l6.weight=5.1;
		System.out.println("The weight is "+l6.weight);
		l6.expiryDate="07/2026";
		System.out.println("The expiry is "+l6.expiryDate);

		Lipstick l7 = new Lipstick();
		l7.brand="Revlon";
		System.out.println("The brand is "+l7.brand);
		l7.cost=799;
		System.out.println("The cost is "+l7.cost);
		l7.shade="Peach";
		System.out.println("The shade is "+l7.shade);
		l7.type="Cream";
		System.out.println("The type is "+l7.type);
		l7.finish="Satin";
		System.out.println("The finish is "+l7.finish);
		l7.isWaterproof=false;
		System.out.println("Waterproof: "+l7.isWaterproof);
		l7.weight=4.3;
		System.out.println("The weight is "+l7.weight);
		l7.expiryDate="06/2026";
		System.out.println("The expiry is "+l7.expiryDate);

		Lipstick l8 = new Lipstick();
		l8.brand="Huda Beauty";
		System.out.println("The brand is "+l8.brand);
		l8.cost=1800;
		System.out.println("The cost is "+l8.cost);
		l8.shade="Plum";
		System.out.println("The shade is "+l8.shade);
		l8.type="Liquid";
		System.out.println("The type is "+l8.type);
		l8.finish="Matte";
		System.out.println("The finish is "+l8.finish);
		l8.isWaterproof=true;
		System.out.println("Waterproof: "+l8.isWaterproof);
		l8.weight=5.2;
		System.out.println("The weight is "+l8.weight);
		l8.expiryDate="12/2026";
		System.out.println("The expiry is "+l8.expiryDate);

		Lipstick l9 = new Lipstick();
		l9.brand="Sugar";
		System.out.println("The brand is "+l9.brand);
		l9.cost=699;
		System.out.println("The cost is "+l9.cost);
		l9.shade="Wine";
		System.out.println("The shade is "+l9.shade);
		l9.type="Matte";
		System.out.println("The type is "+l9.type);
		l9.finish="Matte";
		System.out.println("The finish is "+l9.finish);
		l9.isWaterproof=true;
		System.out.println("Waterproof: "+l9.isWaterproof);
		l9.weight=4.4;
		System.out.println("The weight is "+l9.weight);
		l9.expiryDate="11/2026";
		System.out.println("The expiry is "+l9.expiryDate);

		Lipstick l10 = new Lipstick();
		l10.brand="Insight";
		System.out.println("The brand is "+l10.brand);
		l10.cost=199;
		System.out.println("The cost is "+l10.cost);
		l10.shade="Orange";
		System.out.println("The shade is "+l10.shade);
		l10.type="Matte";
		System.out.println("The type is "+l10.type);
		l10.finish="Matte";
		System.out.println("The finish is "+l10.finish);
		l10.isWaterproof=false;
		System.out.println("Waterproof: "+l10.isWaterproof);
		l10.weight=3.8;
		System.out.println("The weight is "+l10.weight);
		l10.expiryDate="05/2026";
		System.out.println("The expiry is "+l10.expiryDate);
		
				Lipstick l11 = new Lipstick();
		l11.brand="Elle18";
		System.out.println("The brand is "+l11.brand);
		l11.cost=150;
		System.out.println("The cost is "+l11.cost);
		l11.shade="Pink";
		System.out.println("The shade is "+l11.shade);
		l11.type="Gloss";
		System.out.println("The type is "+l11.type);
		l11.finish="Glossy";
		System.out.println("The finish is "+l11.finish);
		l11.isWaterproof=false;
		System.out.println("Waterproof: "+l11.isWaterproof);
		l11.weight=3.0;
		System.out.println("The weight is "+l11.weight);
		l11.expiryDate="04/2026";
		System.out.println("The expiry is "+l11.expiryDate);

		Lipstick l12 = new Lipstick();
		l12.brand="Lotus";
		System.out.println("The brand is "+l12.brand);
		l12.cost=350;
		System.out.println("The cost is "+l12.cost);
		l12.shade="Brown";
		System.out.println("The shade is "+l12.shade);
		l12.type="Matte";
		System.out.println("The type is "+l12.type);
		l12.finish="Matte";
		System.out.println("The finish is "+l12.finish);
		l12.isWaterproof=true;
		System.out.println("Waterproof: "+l12.isWaterproof);
		l12.weight=4.1;
		System.out.println("The weight is "+l12.weight);
		l12.expiryDate="03/2026";
		System.out.println("The expiry is "+l12.expiryDate);

		Lipstick l13 = new Lipstick();
		l13.brand="Blue Heaven";
		System.out.println("The brand is "+l13.brand);
		l13.cost=120;
		System.out.println("The cost is "+l13.cost);
		l13.shade="Red";
		System.out.println("The shade is "+l13.shade);
		l13.type="Matte";
		System.out.println("The type is "+l13.type);
		l13.finish="Matte";
		System.out.println("The finish is "+l13.finish);
		l13.isWaterproof=false;
		System.out.println("Waterproof: "+l13.isWaterproof);
		l13.weight=3.2;
		System.out.println("The weight is "+l13.weight);
		l13.expiryDate="02/2026";
		System.out.println("The expiry is "+l13.expiryDate);

		Lipstick l14 = new Lipstick();
		l14.brand="Swiss Beauty";
		System.out.println("The brand is "+l14.brand);
		l14.cost=299;
		System.out.println("The cost is "+l14.cost);
		l14.shade="Plum";
		System.out.println("The shade is "+l14.shade);
		l14.type="Liquid";
		System.out.println("The type is "+l14.type);
		l14.finish="Matte";
		System.out.println("The finish is "+l14.finish);
		l14.isWaterproof=true;
		System.out.println("Waterproof: "+l14.isWaterproof);
		l14.weight=4.6;
		System.out.println("The weight is "+l14.weight);
		l14.expiryDate="01/2026";
		System.out.println("The expiry is "+l14.expiryDate);

		Lipstick l15 = new Lipstick();
		l15.brand="Faces Canada";
		System.out.println("The brand is "+l15.brand);
		l15.cost=550;
		System.out.println("The cost is "+l15.cost);
		l15.shade="Coral";
		System.out.println("The shade is "+l15.shade);
		l15.type="Crayon";
		System.out.println("The type is "+l15.type);
		l15.finish="Satin";
		System.out.println("The finish is "+l15.finish);
		l15.isWaterproof=true;
		System.out.println("Waterproof: "+l15.isWaterproof);
		l15.weight=3.9;
		System.out.println("The weight is "+l15.weight);
		l15.expiryDate="12/2025";
		System.out.println("The expiry is "+l15.expiryDate);

		Lipstick l16 = new Lipstick();
		l16.brand="Nyx";
		System.out.println("The brand is "+l16.brand);
		l16.cost=900;
		System.out.println("The cost is "+l16.cost);
		l16.shade="Nude";
		System.out.println("The shade is "+l16.shade);
		l16.type="Liquid";
		System.out.println("The type is "+l16.type);
		l16.finish="Matte";
		System.out.println("The finish is "+l16.finish);
		l16.isWaterproof=true;
		System.out.println("Waterproof: "+l16.isWaterproof);
		l16.weight=5.0;
		System.out.println("The weight is "+l16.weight);
		l16.expiryDate="11/2025";
		System.out.println("The expiry is "+l16.expiryDate);

		Lipstick l17 = new Lipstick();
		l17.brand="Chambor";
		System.out.println("The brand is "+l17.brand);
		l17.cost=850;
		System.out.println("The cost is "+l17.cost);
		l17.shade="Wine";
		System.out.println("The shade is "+l17.shade);
		l17.type="Cream";
		System.out.println("The type is "+l17.type);
		l17.finish="Glossy";
		System.out.println("The finish is "+l17.finish);
		l17.isWaterproof=false;
		System.out.println("Waterproof: "+l17.isWaterproof);
		l17.weight=4.7;
		System.out.println("The weight is "+l17.weight);
		l17.expiryDate="10/2025";
		System.out.println("The expiry is "+l17.expiryDate);

		Lipstick l18 = new Lipstick();
		l18.brand="Color Essence";
		System.out.println("The brand is "+l18.brand);
		l18.cost=200;
		System.out.println("The cost is "+l18.cost);
		l18.shade="Pink";
		System.out.println("The shade is "+l18.shade);
		l18.type="Gloss";
		System.out.println("The type is "+l18.type);
		l18.finish="Glossy";
		System.out.println("The finish is "+l18.finish);
		l18.isWaterproof=false;
		System.out.println("Waterproof: "+l18.isWaterproof);
		l18.weight=3.3;
		System.out.println("The weight is "+l18.weight);
		l18.expiryDate="09/2025";
		System.out.println("The expiry is "+l18.expiryDate);

		Lipstick l19 = new Lipstick();
		l19.brand="Milani";
		System.out.println("The brand is "+l19.brand);
		l19.cost=1200;
		System.out.println("The cost is "+l19.cost);
		l19.shade="Berry";
		System.out.println("The shade is "+l19.shade);
		l19.type="Matte";
		System.out.println("The type is "+l19.type);
		l19.finish="Matte";
		System.out.println("The finish is "+l19.finish);
		l19.isWaterproof=true;
		System.out.println("Waterproof: "+l19.isWaterproof);
		l19.weight=4.8;
		System.out.println("The weight is "+l19.weight);
		l19.expiryDate="08/2025";
		System.out.println("The expiry is "+l19.expiryDate);

		Lipstick l20 = new Lipstick();
		l20.brand="L'Oreal";
		System.out.println("The brand is "+l20.brand);
		l20.cost=999;
		System.out.println("The cost is "+l20.cost);
		l20.shade="Red";
		System.out.println("The shade is "+l20.shade);
		l20.type="Liquid";
		System.out.println("The type is "+l20.type);
		l20.finish="Matte";
		System.out.println("The finish is "+l20.finish);
		l20.isWaterproof=true;
		System.out.println("Waterproof: "+l20.isWaterproof);
		l20.weight=5.3;
		System.out.println("The weight is "+l20.weight);
		l20.expiryDate="07/2025";
		System.out.println("The expiry is "+l20.expiryDate);
		
				Lipstick l21 = new Lipstick();
		l21.brand="Dior";
		System.out.println("The brand is "+l21.brand);
		l21.cost=2500;
		System.out.println("The cost is "+l21.cost);
		l21.shade="Rose";
		System.out.println("The shade is "+l21.shade);
		l21.type="Cream";
		System.out.println("The type is "+l21.type);
		l21.finish="Satin";
		System.out.println("The finish is "+l21.finish);
		l21.isWaterproof=false;
		System.out.println("Waterproof: "+l21.isWaterproof);
		l21.weight=4.9;
		System.out.println("The weight is "+l21.weight);
		l21.expiryDate="06/2025";
		System.out.println("The expiry is "+l21.expiryDate);

		Lipstick l22 = new Lipstick();
		l22.brand="Chanel";
		System.out.println("The brand is "+l22.brand);
		l22.cost=3000;
		System.out.println("The cost is "+l22.cost);
		l22.shade="Coral";
		System.out.println("The shade is "+l22.shade);
		l22.type="Matte";
		System.out.println("The type is "+l22.type);
		l22.finish="Matte";
		System.out.println("The finish is "+l22.finish);
		l22.isWaterproof=true;
		System.out.println("Waterproof: "+l22.isWaterproof);
		l22.weight=5.0;
		System.out.println("The weight is "+l22.weight);
		l22.expiryDate="05/2025";
		System.out.println("The expiry is "+l22.expiryDate);

		Lipstick l23 = new Lipstick();
		l23.brand="Estee Lauder";
		System.out.println("The brand is "+l23.brand);
		l23.cost=2800;
		System.out.println("The cost is "+l23.cost);
		l23.shade="Plum";
		System.out.println("The shade is "+l23.shade);
		l23.type="Cream";
		System.out.println("The type is "+l23.type);
		l23.finish="Glossy";
		System.out.println("The finish is "+l23.finish);
		l23.isWaterproof=false;
		System.out.println("Waterproof: "+l23.isWaterproof);
		l23.weight=4.6;
		System.out.println("The weight is "+l23.weight);
		l23.expiryDate="04/2025";
		System.out.println("The expiry is "+l23.expiryDate);

		Lipstick l24 = new Lipstick();
		l24.brand="Bobbi Brown";
		System.out.println("The brand is "+l24.brand);
		l24.cost=2700;
		System.out.println("The cost is "+l24.cost);
		l24.shade="Nude";
		System.out.println("The shade is "+l24.shade);
		l24.type="Matte";
		System.out.println("The type is "+l24.type);
		l24.finish="Matte";
		System.out.println("The finish is "+l24.finish);
		l24.isWaterproof=true;
		System.out.println("Waterproof: "+l24.isWaterproof);
		l24.weight=4.5;
		System.out.println("The weight is "+l24.weight);
		l24.expiryDate="03/2025";
		System.out.println("The expiry is "+l24.expiryDate);

		Lipstick l25 = new Lipstick();
		l25.brand="Street Wear";
		System.out.println("The brand is "+l25.brand);
		l25.cost=180;
		System.out.println("The cost is "+l25.cost);
		l25.shade="Pink";
		System.out.println("The shade is "+l25.shade);
		l25.type="Gloss";
		System.out.println("The type is "+l25.type);
		l25.finish="Glossy";
		System.out.println("The finish is "+l25.finish);
		l25.isWaterproof=false;
		System.out.println("Waterproof: "+l25.isWaterproof);
		l25.weight=3.2;
		System.out.println("The weight is "+l25.weight);
		l25.expiryDate="02/2025";
		System.out.println("The expiry is "+l25.expiryDate);

		Lipstick l26 = new Lipstick();
		l26.brand="Faces Mini";
		System.out.println("The brand is "+l26.brand);
		l26.cost=250;
		System.out.println("The cost is "+l26.cost);
		l26.shade="Orange";
		System.out.println("The shade is "+l26.shade);
		l26.type="Crayon";
		System.out.println("The type is "+l26.type);
		l26.finish="Satin";
		System.out.println("The finish is "+l26.finish);
		l26.isWaterproof=true;
		System.out.println("Waterproof: "+l26.isWaterproof);
		l26.weight=3.5;
		System.out.println("The weight is "+l26.weight);
		l26.expiryDate="01/2025";
		System.out.println("The expiry is "+l26.expiryDate);

		Lipstick l27 = new Lipstick();
		l27.brand="NY Bae";
		System.out.println("The brand is "+l27.brand);
		l27.cost=199;
		System.out.println("The cost is "+l27.cost);
		l27.shade="Wine";
		System.out.println("The shade is "+l27.shade);
		l27.type="Matte";
		System.out.println("The type is "+l27.type);
		l27.finish="Matte";
		System.out.println("The finish is "+l27.finish);
		l27.isWaterproof=true;
		System.out.println("Waterproof: "+l27.isWaterproof);
		l27.weight=4.0;
		System.out.println("The weight is "+l27.weight);
		l27.expiryDate="12/2024";
		System.out.println("The expiry is "+l27.expiryDate);

		Lipstick l28 = new Lipstick();
		l28.brand="Mars";
		System.out.println("The brand is "+l28.brand);
		l28.cost=150;
		System.out.println("The cost is "+l28.cost);
		l28.shade="Red";
		System.out.println("The shade is "+l28.shade);
		l28.type="Matte";
		System.out.println("The type is "+l28.type);
		l28.finish="Matte";
		System.out.println("The finish is "+l28.finish);
		l28.isWaterproof=false;
		System.out.println("Waterproof: "+l28.isWaterproof);
		l28.weight=3.6;
		System.out.println("The weight is "+l28.weight);
		l28.expiryDate="11/2024";
		System.out.println("The expiry is "+l28.expiryDate);

		Lipstick l29 = new Lipstick();
		l29.brand="Plum Goodness";
		System.out.println("The brand is "+l29.brand);
		l29.cost=699;
		System.out.println("The cost is "+l29.cost);
		l29.shade="Berry";
		System.out.println("The shade is "+l29.shade);
		l29.type="Liquid";
		System.out.println("The type is "+l29.type);
		l29.finish="Matte";
		System.out.println("The finish is "+l29.finish);
		l29.isWaterproof=true;
		System.out.println("Waterproof: "+l29.isWaterproof);
		l29.weight=4.7;
		System.out.println("The weight is "+l29.weight);
		l29.expiryDate="10/2024";
		System.out.println("The expiry is "+l29.expiryDate);

		Lipstick l30 = new Lipstick();
		l30.brand="Simple Beauty";
		System.out.println("The brand is "+l30.brand);
		l30.cost=120;
		System.out.println("The cost is "+l30.cost);
		l30.shade="Nude";
		System.out.println("The shade is "+l30.shade);
		l30.type="Cream";
		System.out.println("The type is "+l30.type);
		l30.finish="Satin";
		System.out.println("The finish is "+l30.finish);
		l30.isWaterproof=false;
		System.out.println("Waterproof: "+l30.isWaterproof);
		l30.weight=3.3;
		System.out.println("The weight is "+l30.weight);
		l30.expiryDate="09/2024";
		System.out.println("The expiry is "+l30.expiryDate);
	}
}