class MascraExec
{
    public static void main(String[] args)
    {
        Mascra mascra1=new Mascra();
        mascra1.brand="Maybelline";
        System.out.println("The brand is "+mascra1.brand);
        mascra1.type="Volumizing";
        System.out.println("The type is "+mascra1.type);
        mascra1.color="Black";
        System.out.println("The color is "+mascra1.color);
        mascra1.price=399;
        System.out.println("The price is "+mascra1.price);
        mascra1.weight=10;
        System.out.println("The weight is "+mascra1.weight);
        mascra1.waterproof="Yes";
        System.out.println("Waterproof "+mascra1.waterproof);
        mascra1.finish="Matte";
        System.out.println("Finish is "+mascra1.finish);
        mascra1.quantity=1;
        System.out.println("Quantity "+mascra1.quantity);

        Mascra mascra2=new Mascra();
        mascra2.brand="Lakme";
        System.out.println("The brand is "+mascra2.brand);
        mascra2.type="Lengthening";
        System.out.println("The type is "+mascra2.type);
        mascra2.color="Black";
        System.out.println("The color is "+mascra2.color);
        mascra2.price=299;
        System.out.println("The price is "+mascra2.price);
        mascra2.weight=8;
        System.out.println("The weight is "+mascra2.weight);
        mascra2.waterproof="No";
        System.out.println("Waterproof "+mascra2.waterproof);
        mascra2.finish="Glossy";
        System.out.println("Finish is "+mascra2.finish);
        mascra2.quantity=1;
        System.out.println("Quantity "+mascra2.quantity);

        Mascra mascra3=new Mascra();
        mascra3.brand="Loreal";
        System.out.println("The brand is "+mascra3.brand);
        mascra3.type="Curling";
        System.out.println("The type is "+mascra3.type);
        mascra3.color="Black";
        System.out.println("The color is "+mascra3.color);
        mascra3.price=499;
        System.out.println("The price is "+mascra3.price);
        mascra3.weight=9;
        System.out.println("The weight is "+mascra3.weight);
        mascra3.waterproof="Yes";
        System.out.println("Waterproof "+mascra3.waterproof);
        mascra3.finish="Matte";
        System.out.println("Finish is "+mascra3.finish);
        mascra3.quantity=2;
        System.out.println("Quantity "+mascra3.quantity);

        Mascra mascra4=new Mascra();
        mascra4.brand="FacesCanada";
        System.out.println("The brand is "+mascra4.brand);
        mascra4.type="Volumizing";
        System.out.println("The type is "+mascra4.type);
        mascra4.color="Black";
        System.out.println("The color is "+mascra4.color);
        mascra4.price=349;
        System.out.println("The price is "+mascra4.price);
        mascra4.weight=10;
        System.out.println("The weight is "+mascra4.weight);
        mascra4.waterproof="Yes";
        System.out.println("Waterproof "+mascra4.waterproof);
        mascra4.finish="Glossy";
        System.out.println("Finish is "+mascra4.finish);
        mascra4.quantity=1;
        System.out.println("Quantity "+mascra4.quantity);

        Mascra mascra5=new Mascra();
        mascra5.brand="Colorbar";
        System.out.println("The brand is "+mascra5.brand);
        mascra5.type="Lengthening";
        System.out.println("The type is "+mascra5.type);
        mascra5.color="Black";
        System.out.println("The color is "+mascra5.color);
        mascra5.price=599;
        System.out.println("The price is "+mascra5.price);
        mascra5.weight=11;
        System.out.println("The weight is "+mascra5.weight);
        mascra5.waterproof="No";
        System.out.println("Waterproof "+mascra5.waterproof);
        mascra5.finish="Matte";
        System.out.println("Finish is "+mascra5.finish);
        mascra5.quantity=2;
        System.out.println("Quantity "+mascra5.quantity);

        Mascra mascra6=new Mascra();
        mascra6.brand="Nykaa";
        System.out.println("The brand is "+mascra6.brand);
        mascra6.type="Curling";
        System.out.println("The type is "+mascra6.type);
        mascra6.color="Black";
        System.out.println("The color is "+mascra6.color);
        mascra6.price=399;
        System.out.println("The price is "+mascra6.price);
        mascra6.weight=9;
        System.out.println("The weight is "+mascra6.weight);
        mascra6.waterproof="Yes";
        System.out.println("Waterproof "+mascra6.waterproof);
        mascra6.finish="Glossy";
        System.out.println("Finish is "+mascra6.finish);
        mascra6.quantity=1;
        System.out.println("Quantity "+mascra6.quantity);

        Mascra mascra7=new Mascra();
        mascra7.brand="Revlon";
        System.out.println("The brand is "+mascra7.brand);
        mascra7.type="Volumizing";
        System.out.println("The type is "+mascra7.type);
        mascra7.color="Black";
        System.out.println("The color is "+mascra7.color);
        mascra7.price=699;
        System.out.println("The price is "+mascra7.price);
        mascra7.weight=12;
        System.out.println("The weight is "+mascra7.weight);
        mascra7.waterproof="Yes";
        System.out.println("Waterproof "+mascra7.waterproof);
        mascra7.finish="Matte";
        System.out.println("Finish is "+mascra7.finish);
        mascra7.quantity=1;
        System.out.println("Quantity "+mascra7.quantity);

        Mascra mascra8=new Mascra();
        mascra8.brand="Sugar";
        System.out.println("The brand is "+mascra8.brand);
        mascra8.type="Lengthening";
        System.out.println("The type is "+mascra8.type);
        mascra8.color="Black";
        System.out.println("The color is "+mascra8.color);
        mascra8.price=799;
        System.out.println("The price is "+mascra8.price);
        mascra8.weight=10;
        System.out.println("The weight is "+mascra8.weight);
        mascra8.waterproof="Yes";
        System.out.println("Waterproof "+mascra8.waterproof);
        mascra8.finish="Matte";
        System.out.println("Finish is "+mascra8.finish);
        mascra8.quantity=2;
        System.out.println("Quantity "+mascra8.quantity);

        Mascra mascra9=new Mascra();
        mascra9.brand="Elle18";
        System.out.println("The brand is "+mascra9.brand);
        mascra9.type="Curling";
        System.out.println("The type is "+mascra9.type);
        mascra9.color="Black";
        System.out.println("The color is "+mascra9.color);
        mascra9.price=199;
        System.out.println("The price is "+mascra9.price);
        mascra9.weight=7;
        System.out.println("The weight is "+mascra9.weight);
        mascra9.waterproof="No";
        System.out.println("Waterproof "+mascra9.waterproof);
        mascra9.finish="Glossy";
        System.out.println("Finish is "+mascra9.finish);
        mascra9.quantity=1;
        System.out.println("Quantity "+mascra9.quantity);

        Mascra mascra10=new Mascra();
        mascra10.brand="BlueHeaven";
        System.out.println("The brand is "+mascra10.brand);
        mascra10.type="Volumizing";
        System.out.println("The type is "+mascra10.type);
        mascra10.color="Black";
        System.out.println("The color is "+mascra10.color);
        mascra10.price=249;
        System.out.println("The price is "+mascra10.price);
        mascra10.weight=8;
        System.out.println("The weight is "+mascra10.weight);
        mascra10.waterproof="No";
        System.out.println("Waterproof "+mascra10.waterproof);
        mascra10.finish="Matte";
        System.out.println("Finish is "+mascra10.finish);
        mascra10.quantity=1;
        System.out.println("Quantity "+mascra10.quantity);
		
		        Mascra mascra11=new Mascra();
        mascra11.brand="SwissBeauty";
        System.out.println("The brand is "+mascra11.brand);
        mascra11.type="Volumizing";
        System.out.println("The type is "+mascra11.type);
        mascra11.color="Black";
        System.out.println("The color is "+mascra11.color);
        mascra11.price=299;
        System.out.println("The price is "+mascra11.price);
        mascra11.weight=9;
        System.out.println("The weight is "+mascra11.weight);
        mascra11.waterproof="Yes";
        System.out.println("Waterproof "+mascra11.waterproof);
        mascra11.finish="Matte";
        System.out.println("Finish is "+mascra11.finish);
        mascra11.quantity=1;
        System.out.println("Quantity "+mascra11.quantity);

        Mascra mascra12=new Mascra();
        mascra12.brand="Insight";
        System.out.println("The brand is "+mascra12.brand);
        mascra12.type="Lengthening";
        System.out.println("The type is "+mascra12.type);
        mascra12.color="Black";
        System.out.println("The color is "+mascra12.color);
        mascra12.price=199;
        System.out.println("The price is "+mascra12.price);
        mascra12.weight=8;
        System.out.println("The weight is "+mascra12.weight);
        mascra12.waterproof="No";
        System.out.println("Waterproof "+mascra12.waterproof);
        mascra12.finish="Glossy";
        System.out.println("Finish is "+mascra12.finish);
        mascra12.quantity=2;
        System.out.println("Quantity "+mascra12.quantity);

        Mascra mascra13=new Mascra();
        mascra13.brand="MAC";
        System.out.println("The brand is "+mascra13.brand);
        mascra13.type="Curling";
        System.out.println("The type is "+mascra13.type);
        mascra13.color="Black";
        System.out.println("The color is "+mascra13.color);
        mascra13.price=1499;
        System.out.println("The price is "+mascra13.price);
        mascra13.weight=12;
        System.out.println("The weight is "+mascra13.weight);
        mascra13.waterproof="Yes";
        System.out.println("Waterproof "+mascra13.waterproof);
        mascra13.finish="Matte";
        System.out.println("Finish is "+mascra13.finish);
        mascra13.quantity=1;
        System.out.println("Quantity "+mascra13.quantity);

        Mascra mascra14=new Mascra();
        mascra14.brand="Chambor";
        System.out.println("The brand is "+mascra14.brand);
        mascra14.type="Volumizing";
        System.out.println("The type is "+mascra14.type);
        mascra14.color="Black";
        System.out.println("The color is "+mascra14.color);
        mascra14.price=899;
        System.out.println("The price is "+mascra14.price);
        mascra14.weight=11;
        System.out.println("The weight is "+mascra14.weight);
        mascra14.waterproof="Yes";
        System.out.println("Waterproof "+mascra14.waterproof);
        mascra14.finish="Glossy";
        System.out.println("Finish is "+mascra14.finish);
        mascra14.quantity=1;
        System.out.println("Quantity "+mascra14.quantity);

        Mascra mascra15=new Mascra();
        mascra15.brand="Lotus";
        System.out.println("The brand is "+mascra15.brand);
        mascra15.type="Lengthening";
        System.out.println("The type is "+mascra15.type);
        mascra15.color="Black";
        System.out.println("The color is "+mascra15.color);
        mascra15.price=499;
        System.out.println("The price is "+mascra15.price);
        mascra15.weight=9;
        System.out.println("The weight is "+mascra15.weight);
        mascra15.waterproof="No";
        System.out.println("Waterproof "+mascra15.waterproof);
        mascra15.finish="Matte";
        System.out.println("Finish is "+mascra15.finish);
        mascra15.quantity=2;
        System.out.println("Quantity "+mascra15.quantity);

        Mascra mascra16=new Mascra();
        mascra16.brand="Faces";
        System.out.println("The brand is "+mascra16.brand);
        mascra16.type="Curling";
        System.out.println("The type is "+mascra16.type);
        mascra16.color="Black";
        System.out.println("The color is "+mascra16.color);
        mascra16.price=549;
        System.out.println("The price is "+mascra16.price);
        mascra16.weight=10;
        System.out.println("The weight is "+mascra16.weight);
        mascra16.waterproof="Yes";
        System.out.println("Waterproof "+mascra16.waterproof);
        mascra16.finish="Glossy";
        System.out.println("Finish is "+mascra16.finish);
        mascra16.quantity=1;
        System.out.println("Quantity "+mascra16.quantity);

        Mascra mascra17=new Mascra();
        mascra17.brand="Plum";
        System.out.println("The brand is "+mascra17.brand);
        mascra17.type="Volumizing";
        System.out.println("The type is "+mascra17.type);
        mascra17.color="Black";
        System.out.println("The color is "+mascra17.color);
        mascra17.price=699;
        System.out.println("The price is "+mascra17.price);
        mascra17.weight=11;
        System.out.println("The weight is "+mascra17.weight);
        mascra17.waterproof="Yes";
        System.out.println("Waterproof "+mascra17.waterproof);
        mascra17.finish="Matte";
        System.out.println("Finish is "+mascra17.finish);
        mascra17.quantity=1;
        System.out.println("Quantity "+mascra17.quantity);

        Mascra mascra18=new Mascra();
        mascra18.brand="SugarPop";
        System.out.println("The brand is "+mascra18.brand);
        mascra18.type="Lengthening";
        System.out.println("The type is "+mascra18.type);
        mascra18.color="Black";
        System.out.println("The color is "+mascra18.color);
        mascra18.price=349;
        System.out.println("The price is "+mascra18.price);
        mascra18.weight=8;
        System.out.println("The weight is "+mascra18.weight);
        mascra18.waterproof="No";
        System.out.println("Waterproof "+mascra18.waterproof);
        mascra18.finish="Glossy";
        System.out.println("Finish is "+mascra18.finish);
        mascra18.quantity=2;
        System.out.println("Quantity "+mascra18.quantity);

        Mascra mascra19=new Mascra();
        mascra19.brand="KayBeauty";
        System.out.println("The brand is "+mascra19.brand);
        mascra19.type="Curling";
        System.out.println("The type is "+mascra19.type);
        mascra19.color="Black";
        System.out.println("The color is "+mascra19.color);
        mascra19.price=799;
        System.out.println("The price is "+mascra19.price);
        mascra19.weight=10;
        System.out.println("The weight is "+mascra19.weight);
        mascra19.waterproof="Yes";
        System.out.println("Waterproof "+mascra19.waterproof);
        mascra19.finish="Matte";
        System.out.println("Finish is "+mascra19.finish);
        mascra19.quantity=1;
        System.out.println("Quantity "+mascra19.quantity);

        Mascra mascra20=new Mascra();
        mascra20.brand="BobbiBrown";
        System.out.println("The brand is "+mascra20.brand);
        mascra20.type="Volumizing";
        System.out.println("The type is "+mascra20.type);
        mascra20.color="Black";
        System.out.println("The color is "+mascra20.color);
        mascra20.price=1999;
        System.out.println("The price is "+mascra20.price);
        mascra20.weight=12;
        System.out.println("The weight is "+mascra20.weight);
        mascra20.waterproof="Yes";
        System.out.println("Waterproof "+mascra20.waterproof);
        mascra20.finish="Glossy";
        System.out.println("Finish is "+mascra20.finish);
        mascra20.quantity=1;
        System.out.println("Quantity "+mascra20.quantity);
		
		        Mascra mascra21=new Mascra();
        mascra21.brand="Dior";
        System.out.println("The brand is "+mascra21.brand);
        mascra21.type="Luxury";
        System.out.println("The type is "+mascra21.type);
        mascra21.color="Black";
        System.out.println("The color is "+mascra21.color);
        mascra21.price=2499;
        System.out.println("The price is "+mascra21.price);
        mascra21.weight=12;
        System.out.println("The weight is "+mascra21.weight);
        mascra21.waterproof="Yes";
        System.out.println("Waterproof "+mascra21.waterproof);
        mascra21.finish="Matte";
        System.out.println("Finish is "+mascra21.finish);
        mascra21.quantity=1;
        System.out.println("Quantity "+mascra21.quantity);

        Mascra mascra22=new Mascra();
        mascra22.brand="Chanel";
        System.out.println("The brand is "+mascra22.brand);
        mascra22.type="Luxury";
        System.out.println("The type is "+mascra22.type);
        mascra22.color="Black";
        System.out.println("The color is "+mascra22.color);
        mascra22.price=2799;
        System.out.println("The price is "+mascra22.price);
        mascra22.weight=13;
        System.out.println("The weight is "+mascra22.weight);
        mascra22.waterproof="Yes";
        System.out.println("Waterproof "+mascra22.waterproof);
        mascra22.finish="Glossy";
        System.out.println("Finish is "+mascra22.finish);
        mascra22.quantity=1;
        System.out.println("Quantity "+mascra22.quantity);

        Mascra mascra23=new Mascra();
        mascra23.brand="EsteeLauder";
        System.out.println("The brand is "+mascra23.brand);
        mascra23.type="Volumizing";
        System.out.println("The type is "+mascra23.type);
        mascra23.color="Black";
        System.out.println("The color is "+mascra23.color);
        mascra23.price=2199;
        System.out.println("The price is "+mascra23.price);
        mascra23.weight=12;
        System.out.println("The weight is "+mascra23.weight);
        mascra23.waterproof="Yes";
        System.out.println("Waterproof "+mascra23.waterproof);
        mascra23.finish="Matte";
        System.out.println("Finish is "+mascra23.finish);
        mascra23.quantity=2;
        System.out.println("Quantity "+mascra23.quantity);

        Mascra mascra24=new Mascra();
        mascra24.brand="Clinique";
        System.out.println("The brand is "+mascra24.brand);
        mascra24.type="Lengthening";
        System.out.println("The type is "+mascra24.type);
        mascra24.color="Black";
        System.out.println("The color is "+mascra24.color);
        mascra24.price=1999;
        System.out.println("The price is "+mascra24.price);
        mascra24.weight=11;
        System.out.println("The weight is "+mascra24.weight);
        mascra24.waterproof="No";
        System.out.println("Waterproof "+mascra24.waterproof);
        mascra24.finish="Glossy";
        System.out.println("Finish is "+mascra24.finish);
        mascra24.quantity=1;
        System.out.println("Quantity "+mascra24.quantity);

        Mascra mascra25=new Mascra();
        mascra25.brand="Lancome";
        System.out.println("The brand is "+mascra25.brand);
        mascra25.type="Curling";
        System.out.println("The type is "+mascra25.type);
        mascra25.color="Black";
        System.out.println("The color is "+mascra25.color);
        mascra25.price=2299;
        System.out.println("The price is "+mascra25.price);
        mascra25.weight=12;
        System.out.println("The weight is "+mascra25.weight);
        mascra25.waterproof="Yes";
        System.out.println("Waterproof "+mascra25.waterproof);
        mascra25.finish="Matte";
        System.out.println("Finish is "+mascra25.finish);
        mascra25.quantity=1;
        System.out.println("Quantity "+mascra25.quantity);

        Mascra mascra26=new Mascra();
        mascra26.brand="HudaBeauty";
        System.out.println("The brand is "+mascra26.brand);
        mascra26.type="Volumizing";
        System.out.println("The type is "+mascra26.type);
        mascra26.color="Black";
        System.out.println("The color is "+mascra26.color);
        mascra26.price=1999;
        System.out.println("The price is "+mascra26.price);
        mascra26.weight=11;
        System.out.println("The weight is "+mascra26.weight);
        mascra26.waterproof="Yes";
        System.out.println("Waterproof "+mascra26.waterproof);
        mascra26.finish="Glossy";
        System.out.println("Finish is "+mascra26.finish);
        mascra26.quantity=2;
        System.out.println("Quantity "+mascra26.quantity);

        Mascra mascra27=new Mascra();
        mascra27.brand="Benefit";
        System.out.println("The brand is "+mascra27.brand);
        mascra27.type="Lengthening";
        System.out.println("The type is "+mascra27.type);
        mascra27.color="Black";
        System.out.println("The color is "+mascra27.color);
        mascra27.price=1899;
        System.out.println("The price is "+mascra27.price);
        mascra27.weight=10;
        System.out.println("The weight is "+mascra27.weight);
        mascra27.waterproof="Yes";
        System.out.println("Waterproof "+mascra27.waterproof);
        mascra27.finish="Matte";
        System.out.println("Finish is "+mascra27.finish);
        mascra27.quantity=1;
        System.out.println("Quantity "+mascra27.quantity);

        Mascra mascra28=new Mascra();
        mascra28.brand="TooFaced";
        System.out.println("The brand is "+mascra28.brand);
        mascra28.type="Curling";
        System.out.println("The type is "+mascra28.type);
        mascra28.color="Black";
        System.out.println("The color is "+mascra28.color);
        mascra28.price=2099;
        System.out.println("The price is "+mascra28.price);
        mascra28.weight=11;
        System.out.println("The weight is "+mascra28.weight);
        mascra28.waterproof="Yes";
        System.out.println("Waterproof "+mascra28.waterproof);
        mascra28.finish="Glossy";
        System.out.println("Finish is "+mascra28.finish);
        mascra28.quantity=1;
        System.out.println("Quantity "+mascra28.quantity);

        Mascra mascra29=new Mascra();
        mascra29.brand="NYX";
        System.out.println("The brand is "+mascra29.brand);
        mascra29.type="Volumizing";
        System.out.println("The type is "+mascra29.type);
        mascra29.color="Black";
        System.out.println("The color is "+mascra29.color);
        mascra29.price=999;
        System.out.println("The price is "+mascra29.price);
        mascra29.weight=10;
        System.out.println("The weight is "+mascra29.weight);
        mascra29.waterproof="No";
        System.out.println("Waterproof "+mascra29.waterproof);
        mascra29.finish="Matte";
        System.out.println("Finish is "+mascra29.finish);
        mascra29.quantity=2;
        System.out.println("Quantity "+mascra29.quantity);

        Mascra mascra30=new Mascra();
        mascra30.brand="Sephora";
        System.out.println("The brand is "+mascra30.brand);
        mascra30.type="Lengthening";
        System.out.println("The type is "+mascra30.type);
        mascra30.color="Black";
        System.out.println("The color is "+mascra30.color);
        mascra30.price=1499;
        System.out.println("The price is "+mascra30.price);
        mascra30.weight=11;
        System.out.println("The weight is "+mascra30.weight);
        mascra30.waterproof="Yes";
        System.out.println("Waterproof "+mascra30.waterproof);
        mascra30.finish="Glossy";
        System.out.println("Finish is "+mascra30.finish);
        mascra30.quantity=1;
        System.out.println("Quantity "+mascra30.quantity);
    }
}