class MedicineExec
{
	public static void main(String[] args)
	{
		Medicine m1 = new Medicine();
		m1.name="Paracetamol";
		System.out.println("The name is "+m1.name);
		m1.brand="Dolo";
		System.out.println("Brand is "+m1.brand);
		m1.price=20;
		System.out.println("Price is "+m1.price);
		m1.type="Tablet";
		System.out.println("Type is "+m1.type);
		m1.expiryDate="12/2026";
		System.out.println("Expiry "+m1.expiryDate);
		m1.manufactureDate="01/2024";
		System.out.println("MFD "+m1.manufactureDate);
		m1.dosage="1-0-1";
		System.out.println("Dosage "+m1.dosage);
		m1.isPrescriptionRequired=false;
		System.out.println("Prescription "+m1.isPrescriptionRequired);

		Medicine m2 = new Medicine();
		m2.name="Amoxicillin";
		System.out.println("The name is "+m2.name);
		m2.brand="Mox";
		System.out.println("Brand is "+m2.brand);
		m2.price=55;
		System.out.println("Price is "+m2.price);
		m2.type="Capsule";
		System.out.println("Type is "+m2.type);
		m2.expiryDate="08/2026";
		System.out.println("Expiry "+m2.expiryDate);
		m2.manufactureDate="02/2024";
		System.out.println("MFD "+m2.manufactureDate);
		m2.dosage="1-1-1";
		System.out.println("Dosage "+m2.dosage);
		m2.isPrescriptionRequired=true;
		System.out.println("Prescription "+m2.isPrescriptionRequired);

		Medicine m3 = new Medicine();
		m3.name="Cetirizine";
		System.out.println("The name is "+m3.name);
		m3.brand="Cetzine";
		System.out.println("Brand is "+m3.brand);
		m3.price=15;
		System.out.println("Price is "+m3.price);
		m3.type="Tablet";
		System.out.println("Type is "+m3.type);
		m3.expiryDate="11/2025";
		System.out.println("Expiry "+m3.expiryDate);
		m3.manufactureDate="03/2024";
		System.out.println("MFD "+m3.manufactureDate);
		m3.dosage="0-0-1";
		System.out.println("Dosage "+m3.dosage);
		m3.isPrescriptionRequired=false;
		System.out.println("Prescription "+m3.isPrescriptionRequired);

		Medicine m4 = new Medicine();
		m4.name="Azithromycin";
		System.out.println("The name is "+m4.name);
		m4.brand="Azee";
		System.out.println("Brand is "+m4.brand);
		m4.price=120;
		System.out.println("Price is "+m4.price);
		m4.type="Tablet";
		System.out.println("Type is "+m4.type);
		m4.expiryDate="09/2026";
		System.out.println("Expiry "+m4.expiryDate);
		m4.manufactureDate="04/2024";
		System.out.println("MFD "+m4.manufactureDate);
		m4.dosage="1-0-0";
		System.out.println("Dosage "+m4.dosage);
		m4.isPrescriptionRequired=true;
		System.out.println("Prescription "+m4.isPrescriptionRequired);

		Medicine m5 = new Medicine();
		m5.name="Ibuprofen";
		System.out.println("The name is "+m5.name);
		m5.brand="Brufen";
		System.out.println("Brand is "+m5.brand);
		m5.price=30;
		System.out.println("Price is "+m5.price);
		m5.type="Tablet";
		System.out.println("Type is "+m5.type);
		m5.expiryDate="07/2026";
		System.out.println("Expiry "+m5.expiryDate);
		m5.manufactureDate="01/2024";
		System.out.println("MFD "+m5.manufactureDate);
		m5.dosage="1-0-1";
		System.out.println("Dosage "+m5.dosage);
		m5.isPrescriptionRequired=false;
		System.out.println("Prescription "+m5.isPrescriptionRequired);

		Medicine m6 = new Medicine();
		m6.name="Metformin";
		System.out.println("The name is "+m6.name);
		m6.brand="Glycomet";
		System.out.println("Brand is "+m6.brand);
		m6.price=80;
		System.out.println("Price is "+m6.price);
		m6.type="Tablet";
		System.out.println("Type is "+m6.type);
		m6.expiryDate="10/2026";
		System.out.println("Expiry "+m6.expiryDate);
		m6.manufactureDate="05/2024";
		System.out.println("MFD "+m6.manufactureDate);
		m6.dosage="1-0-1";
		System.out.println("Dosage "+m6.dosage);
		m6.isPrescriptionRequired=true;
		System.out.println("Prescription "+m6.isPrescriptionRequired);

		Medicine m7 = new Medicine();
		m7.name="Omeprazole";
		System.out.println("The name is "+m7.name);
		m7.brand="Omez";
		System.out.println("Brand is "+m7.brand);
		m7.price=40;
		System.out.println("Price is "+m7.price);
		m7.type="Capsule";
		System.out.println("Type is "+m7.type);
		m7.expiryDate="06/2026";
		System.out.println("Expiry "+m7.expiryDate);
		m7.manufactureDate="03/2024";
		System.out.println("MFD "+m7.manufactureDate);
		m7.dosage="1-0-0";
		System.out.println("Dosage "+m7.dosage);
		m7.isPrescriptionRequired=false;
		System.out.println("Prescription "+m7.isPrescriptionRequired);

		Medicine m8 = new Medicine();
		m8.name="Cough Syrup";
		System.out.println("The name is "+m8.name);
		m8.brand="Benadryl";
		System.out.println("Brand is "+m8.brand);
		m8.price=90;
		System.out.println("Price is "+m8.price);
		m8.type="Syrup";
		System.out.println("Type is "+m8.type);
		m8.expiryDate="12/2025";
		System.out.println("Expiry "+m8.expiryDate);
		m8.manufactureDate="02/2024";
		System.out.println("MFD "+m8.manufactureDate);
		m8.dosage="2 spoons/day";
		System.out.println("Dosage "+m8.dosage);
		m8.isPrescriptionRequired=false;
		System.out.println("Prescription "+m8.isPrescriptionRequired);

		Medicine m9 = new Medicine();
		m9.name="Vitamin D";
		System.out.println("The name is "+m9.name);
		m9.brand="Uprise";
		System.out.println("Brand is "+m9.brand);
		m9.price=60;
		System.out.println("Price is "+m9.price);
		m9.type="Tablet";
		System.out.println("Type is "+m9.type);
		m9.expiryDate="11/2026";
		System.out.println("Expiry "+m9.expiryDate);
		m9.manufactureDate="01/2024";
		System.out.println("MFD "+m9.manufactureDate);
		m9.dosage="1/week";
		System.out.println("Dosage "+m9.dosage);
		m9.isPrescriptionRequired=false;
		System.out.println("Prescription "+m9.isPrescriptionRequired);

		Medicine m10 = new Medicine();
		m10.name="Insulin";
		System.out.println("The name is "+m10.name);
		m10.brand="Novorapid";
		System.out.println("Brand is "+m10.brand);
		m10.price=500;
		System.out.println("Price is "+m10.price);
		m10.type="Injection";
		System.out.println("Type is "+m10.type);
		m10.expiryDate="05/2026";
		System.out.println("Expiry "+m10.expiryDate);
		m10.manufactureDate="06/2024";
		System.out.println("MFD "+m10.manufactureDate);
		m10.dosage="As prescribed";
		System.out.println("Dosage "+m10.dosage);
		m10.isPrescriptionRequired=true;
		System.out.println("Prescription "+m10.isPrescriptionRequired);
		
				Medicine m11 = new Medicine();
		m11.name="Aspirin";
		System.out.println("The name is "+m11.name);
		m11.brand="Ecosprin";
		System.out.println("Brand is "+m11.brand);
		m11.price=25;
		System.out.println("Price is "+m11.price);
		m11.type="Tablet";
		System.out.println("Type is "+m11.type);
		m11.expiryDate="08/2026";
		System.out.println("Expiry "+m11.expiryDate);
		m11.manufactureDate="02/2024";
		System.out.println("MFD "+m11.manufactureDate);
		m11.dosage="1-0-0";
		System.out.println("Dosage "+m11.dosage);
		m11.isPrescriptionRequired=false;
		System.out.println("Prescription "+m11.isPrescriptionRequired);

		Medicine m12 = new Medicine();
		m12.name="Pantoprazole";
		System.out.println("The name is "+m12.name);
		m12.brand="Pantocid";
		System.out.println("Brand is "+m12.brand);
		m12.price=45;
		System.out.println("Price is "+m12.price);
		m12.type="Tablet";
		System.out.println("Type is "+m12.type);
		m12.expiryDate="09/2026";
		System.out.println("Expiry "+m12.expiryDate);
		m12.manufactureDate="03/2024";
		System.out.println("MFD "+m12.manufactureDate);
		m12.dosage="1-0-0";
		System.out.println("Dosage "+m12.dosage);
		m12.isPrescriptionRequired=false;
		System.out.println("Prescription "+m12.isPrescriptionRequired);

		Medicine m13 = new Medicine();
		m13.name="Calcium";
		System.out.println("The name is "+m13.name);
		m13.brand="Shelcal";
		System.out.println("Brand is "+m13.brand);
		m13.price=70;
		System.out.println("Price is "+m13.price);
		m13.type="Tablet";
		System.out.println("Type is "+m13.type);
		m13.expiryDate="12/2026";
		System.out.println("Expiry "+m13.expiryDate);
		m13.manufactureDate="01/2024";
		System.out.println("MFD "+m13.manufactureDate);
		m13.dosage="1/day";
		System.out.println("Dosage "+m13.dosage);
		m13.isPrescriptionRequired=false;
		System.out.println("Prescription "+m13.isPrescriptionRequired);

		Medicine m14 = new Medicine();
		m14.name="ORS";
		System.out.println("The name is "+m14.name);
		m14.brand="Electral";
		System.out.println("Brand is "+m14.brand);
		m14.price=20;
		System.out.println("Price is "+m14.price);
		m14.type="Powder";
		System.out.println("Type is "+m14.type);
		m14.expiryDate="07/2025";
		System.out.println("Expiry "+m14.expiryDate);
		m14.manufactureDate="04/2024";
		System.out.println("MFD "+m14.manufactureDate);
		m14.dosage="As needed";
		System.out.println("Dosage "+m14.dosage);
		m14.isPrescriptionRequired=false;
		System.out.println("Prescription "+m14.isPrescriptionRequired);

		Medicine m15 = new Medicine();
		m15.name="Crocin";
		System.out.println("The name is "+m15.name);
		m15.brand="GSK";
		System.out.println("Brand is "+m15.brand);
		m15.price=18;
		System.out.println("Price is "+m15.price);
		m15.type="Tablet";
		System.out.println("Type is "+m15.type);
		m15.expiryDate="10/2026";
		System.out.println("Expiry "+m15.expiryDate);
		m15.manufactureDate="02/2024";
		System.out.println("MFD "+m15.manufactureDate);
		m15.dosage="1-0-1";
		System.out.println("Dosage "+m15.dosage);
		m15.isPrescriptionRequired=false;
		System.out.println("Prescription "+m15.isPrescriptionRequired);

		Medicine m16 = new Medicine();
		m16.name="Antacid";
		System.out.println("The name is "+m16.name);
		m16.brand="Gelusil";
		System.out.println("Brand is "+m16.brand);
		m16.price=35;
		System.out.println("Price is "+m16.price);
		m16.type="Syrup";
		System.out.println("Type is "+m16.type);
		m16.expiryDate="11/2025";
		System.out.println("Expiry "+m16.expiryDate);
		m16.manufactureDate="03/2024";
		System.out.println("MFD "+m16.manufactureDate);
		m16.dosage="2 spoons";
		System.out.println("Dosage "+m16.dosage);
		m16.isPrescriptionRequired=false;
		System.out.println("Prescription "+m16.isPrescriptionRequired);

		Medicine m17 = new Medicine();
		m17.name="Pain Relief";
		System.out.println("The name is "+m17.name);
		m17.brand="Volini";
		System.out.println("Brand is "+m17.brand);
		m17.price=120;
		System.out.println("Price is "+m17.price);
		m17.type="Gel";
		System.out.println("Type is "+m17.type);
		m17.expiryDate="09/2026";
		System.out.println("Expiry "+m17.expiryDate);
		m17.manufactureDate="05/2024";
		System.out.println("MFD "+m17.manufactureDate);
		m17.dosage="Apply twice";
		System.out.println("Dosage "+m17.dosage);
		m17.isPrescriptionRequired=false;
		System.out.println("Prescription "+m17.isPrescriptionRequired);

		Medicine m18 = new Medicine();
		m18.name="Eye Drops";
		System.out.println("The name is "+m18.name);
		m18.brand="Refresh";
		System.out.println("Brand is "+m18.brand);
		m18.price=150;
		System.out.println("Price is "+m18.price);
		m18.type="Drops";
		System.out.println("Type is "+m18.type);
		m18.expiryDate="08/2025";
		System.out.println("Expiry "+m18.expiryDate);
		m18.manufactureDate="04/2024";
		System.out.println("MFD "+m18.manufactureDate);
		m18.dosage="2 drops";
		System.out.println("Dosage "+m18.dosage);
		m18.isPrescriptionRequired=false;
		System.out.println("Prescription "+m18.isPrescriptionRequired);

		Medicine m19 = new Medicine();
		m19.name="Multivitamin";
		System.out.println("The name is "+m19.name);
		m19.brand="Zincovit";
		System.out.println("Brand is "+m19.brand);
		m19.price=95;
		System.out.println("Price is "+m19.price);
		m19.type="Tablet";
		System.out.println("Type is "+m19.type);
		m19.expiryDate="12/2026";
		System.out.println("Expiry "+m19.expiryDate);
		m19.manufactureDate="01/2024";
		System.out.println("MFD "+m19.manufactureDate);
		m19.dosage="1/day";
		System.out.println("Dosage "+m19.dosage);
		m19.isPrescriptionRequired=false;
		System.out.println("Prescription "+m19.isPrescriptionRequired);

		Medicine m20 = new Medicine();
		m20.name="Antibiotic Syrup";
		System.out.println("The name is "+m20.name);
		m20.brand="Augmentin";
		System.out.println("Brand is "+m20.brand);
		m20.price=140;
		System.out.println("Price is "+m20.price);
		m20.type="Syrup";
		System.out.println("Type is "+m20.type);
		m20.expiryDate="07/2026";
		System.out.println("Expiry "+m20.expiryDate);
		m20.manufactureDate="02/2024";
		System.out.println("MFD "+m20.manufactureDate);
		m20.dosage="2 times";
		System.out.println("Dosage "+m20.dosage);
		m20.isPrescriptionRequired=true;
		System.out.println("Prescription "+m20.isPrescriptionRequired);
		
				Medicine m21 = new Medicine();
		m21.name="Diclofenac";
		System.out.println("The name is "+m21.name);
		m21.brand="Voveran";
		System.out.println("Brand is "+m21.brand);
		m21.price=60;
		System.out.println("Price is "+m21.price);
		m21.type="Tablet";
		System.out.println("Type is "+m21.type);
		m21.expiryDate="10/2026";
		System.out.println("Expiry "+m21.expiryDate);
		m21.manufactureDate="03/2024";
		System.out.println("MFD "+m21.manufactureDate);
		m21.dosage="1-0-1";
		System.out.println("Dosage "+m21.dosage);
		m21.isPrescriptionRequired=true;
		System.out.println("Prescription "+m21.isPrescriptionRequired);

		Medicine m22 = new Medicine();
		m22.name="Loperamide";
		System.out.println("The name is "+m22.name);
		m22.brand="Imodium";
		System.out.println("Brand is "+m22.brand);
		m22.price=35;
		System.out.println("Price is "+m22.price);
		m22.type="Tablet";
		System.out.println("Type is "+m22.type);
		m22.expiryDate="09/2025";
		System.out.println("Expiry "+m22.expiryDate);
		m22.manufactureDate="04/2024";
		System.out.println("MFD "+m22.manufactureDate);
		m22.dosage="As needed";
		System.out.println("Dosage "+m22.dosage);
		m22.isPrescriptionRequired=false;
		System.out.println("Prescription "+m22.isPrescriptionRequired);

		Medicine m23 = new Medicine();
		m23.name="Insulin Pen";
		System.out.println("The name is "+m23.name);
		m23.brand="Lantus";
		System.out.println("Brand is "+m23.brand);
		m23.price=1200;
		System.out.println("Price is "+m23.price);
		m23.type="Injection";
		System.out.println("Type is "+m23.type);
		m23.expiryDate="06/2026";
		System.out.println("Expiry "+m23.expiryDate);
		m23.manufactureDate="05/2024";
		System.out.println("MFD "+m23.manufactureDate);
		m23.dosage="As prescribed";
		System.out.println("Dosage "+m23.dosage);
		m23.isPrescriptionRequired=true;
		System.out.println("Prescription "+m23.isPrescriptionRequired);

		Medicine m24 = new Medicine();
		m24.name="Cold Tablet";
		System.out.println("The name is "+m24.name);
		m24.brand="Sinarest";
		System.out.println("Brand is "+m24.brand);
		m24.price=40;
		System.out.println("Price is "+m24.price);
		m24.type="Tablet";
		System.out.println("Type is "+m24.type);
		m24.expiryDate="11/2026";
		System.out.println("Expiry "+m24.expiryDate);
		m24.manufactureDate="02/2024";
		System.out.println("MFD "+m24.manufactureDate);
		m24.dosage="1-0-1";
		System.out.println("Dosage "+m24.dosage);
		m24.isPrescriptionRequired=false;
		System.out.println("Prescription "+m24.isPrescriptionRequired);

		Medicine m25 = new Medicine();
		m25.name="Allergy Syrup";
		System.out.println("The name is "+m25.name);
		m25.brand="Allegra";
		System.out.println("Brand is "+m25.brand);
		m25.price=110;
		System.out.println("Price is "+m25.price);
		m25.type="Syrup";
		System.out.println("Type is "+m25.type);
		m25.expiryDate="08/2026";
		System.out.println("Expiry "+m25.expiryDate);
		m25.manufactureDate="03/2024";
		System.out.println("MFD "+m25.manufactureDate);
		m25.dosage="2 spoons";
		System.out.println("Dosage "+m25.dosage);
		m25.isPrescriptionRequired=false;
		System.out.println("Prescription "+m25.isPrescriptionRequired);

		Medicine m26 = new Medicine();
		m26.name="Pain Tablet";
		System.out.println("The name is "+m26.name);
		m26.brand="Combiflam";
		System.out.println("Brand is "+m26.brand);
		m26.price=35;
		System.out.println("Price is "+m26.price);
		m26.type="Tablet";
		System.out.println("Type is "+m26.type);
		m26.expiryDate="10/2026";
		System.out.println("Expiry "+m26.expiryDate);
		m26.manufactureDate="04/2024";
		System.out.println("MFD "+m26.manufactureDate);
		m26.dosage="1-0-1";
		System.out.println("Dosage "+m26.dosage);
		m26.isPrescriptionRequired=false;
		System.out.println("Prescription "+m26.isPrescriptionRequired);

		Medicine m27 = new Medicine();
		m27.name="Antifungal Cream";
		System.out.println("The name is "+m27.name);
		m27.brand="Candid";
		System.out.println("Brand is "+m27.brand);
		m27.price=90;
		System.out.println("Price is "+m27.price);
		m27.type="Cream";
		System.out.println("Type is "+m27.type);
		m27.expiryDate="07/2026";
		System.out.println("Expiry "+m27.expiryDate);
		m27.manufactureDate="03/2024";
		System.out.println("MFD "+m27.manufactureDate);
		m27.dosage="Apply twice";
		System.out.println("Dosage "+m27.dosage);
		m27.isPrescriptionRequired=false;
		System.out.println("Prescription "+m27.isPrescriptionRequired);

		Medicine m28 = new Medicine();
		m28.name="Nasal Spray";
		System.out.println("The name is "+m28.name);
		m28.brand="Otrivin";
		System.out.println("Brand is "+m28.brand);
		m28.price=120;
		System.out.println("Price is "+m28.price);
		m28.type="Spray";
		System.out.println("Type is "+m28.type);
		m28.expiryDate="09/2025";
		System.out.println("Expiry "+m28.expiryDate);
		m28.manufactureDate="02/2024";
		System.out.println("MFD "+m28.manufactureDate);
		m28.dosage="2 sprays";
		System.out.println("Dosage "+m28.dosage);
		m28.isPrescriptionRequired=false;
		System.out.println("Prescription "+m28.isPrescriptionRequired);

		Medicine m29 = new Medicine();
		m29.name="Energy Drink";
		System.out.println("The name is "+m29.name);
		m29.brand="ORS Plus";
		System.out.println("Brand is "+m29.brand);
		m29.price=50;
		System.out.println("Price is "+m29.price);
		m29.type="Liquid";
		System.out.println("Type is "+m29.type);
		m29.expiryDate="06/2025";
		System.out.println("Expiry "+m29.expiryDate);
		m29.manufactureDate="01/2024";
		System.out.println("MFD "+m29.manufactureDate);
		m29.dosage="As needed";
		System.out.println("Dosage "+m29.dosage);
		m29.isPrescriptionRequired=false;
		System.out.println("Prescription "+m29.isPrescriptionRequired);

		Medicine m30 = new Medicine();
		m30.name="Antiseptic Liquid";
		System.out.println("The name is "+m30.name);
		m30.brand="Dettol";
		System.out.println("Brand is "+m30.brand);
		m30.price=85;
		System.out.println("Price is "+m30.price);
		m30.type="Liquid";
		System.out.println("Type is "+m30.type);
		m30.expiryDate="12/2026";
		System.out.println("Expiry "+m30.expiryDate);
		m30.manufactureDate="05/2024";
		System.out.println("MFD "+m30.manufactureDate);
		m30.dosage="External use";
		System.out.println("Dosage "+m30.dosage);
		m30.isPrescriptionRequired=false;
		System.out.println("Prescription "+m30.isPrescriptionRequired);
	}
}