class PowerbankExec
{
	public static void main(String ref[])
	{
		Powerbank powerbank11=new Powerbank();
		powerbank11.brand="HP";
		System.out.println("The brand is "+powerbank11.brand);
		powerbank11.capacity=10000;
		System.out.println("The capacity is "+powerbank11.capacity);
		powerbank11.outputPower=15;
		System.out.println("The output power is "+powerbank11.outputPower);
		powerbank11.inputPower=10;
		System.out.println("The input power is "+powerbank11.inputPower);
		powerbank11.weight=260;
		System.out.println("The weight is "+powerbank11.weight);
		powerbank11.color="Black";
		System.out.println("The color is "+powerbank11.color);
		powerbank11.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank11.numberOfPorts);
		powerbank11.type="Li-Ion";
		System.out.println("Type is "+powerbank11.type);

		Powerbank powerbank12=new Powerbank();
		powerbank12.brand="Dell";
		System.out.println("The brand is "+powerbank12.brand);
		powerbank12.capacity=20000;
		System.out.println("The capacity is "+powerbank12.capacity);
		powerbank12.outputPower=25;
		System.out.println("The output power is "+powerbank12.outputPower);
		powerbank12.inputPower=18;
		System.out.println("The input power is "+powerbank12.inputPower);
		powerbank12.weight=480;
		System.out.println("The weight is "+powerbank12.weight);
		powerbank12.color="Grey";
		System.out.println("The color is "+powerbank12.color);
		powerbank12.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank12.numberOfPorts);
		powerbank12.type="Li-Polymer";
		System.out.println("Type is "+powerbank12.type);

		Powerbank powerbank13=new Powerbank();
		powerbank13.brand="Lenovo";
		System.out.println("The brand is "+powerbank13.brand);
		powerbank13.capacity=15000;
		System.out.println("The capacity is "+powerbank13.capacity);
		powerbank13.outputPower=20;
		System.out.println("The output power is "+powerbank13.outputPower);
		powerbank13.inputPower=12;
		System.out.println("The input power is "+powerbank13.inputPower);
		powerbank13.weight=350;
		System.out.println("The weight is "+powerbank13.weight);
		powerbank13.color="Black";
		System.out.println("The color is "+powerbank13.color);
		powerbank13.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank13.numberOfPorts);
		powerbank13.type="Li-Ion";
		System.out.println("Type is "+powerbank13.type);

		Powerbank powerbank14=new Powerbank();
		powerbank14.brand="Asus";
		System.out.println("The brand is "+powerbank14.brand);
		powerbank14.capacity=20000;
		System.out.println("The capacity is "+powerbank14.capacity);
		powerbank14.outputPower=30;
		System.out.println("The output power is "+powerbank14.outputPower);
		powerbank14.inputPower=18;
		System.out.println("The input power is "+powerbank14.inputPower);
		powerbank14.weight=500;
		System.out.println("The weight is "+powerbank14.weight);
		powerbank14.color="Blue";
		System.out.println("The color is "+powerbank14.color);
		powerbank14.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank14.numberOfPorts);
		powerbank14.type="Li-Polymer";
		System.out.println("Type is "+powerbank14.type);

		Powerbank powerbank15=new Powerbank();
		powerbank15.brand="Acer";
		System.out.println("The brand is "+powerbank15.brand);
		powerbank15.capacity=10000;
		System.out.println("The capacity is "+powerbank15.capacity);
		powerbank15.outputPower=15;
		System.out.println("The output power is "+powerbank15.outputPower);
		powerbank15.inputPower=10;
		System.out.println("The input power is "+powerbank15.inputPower);
		powerbank15.weight=270;
		System.out.println("The weight is "+powerbank15.weight);
		powerbank15.color="White";
		System.out.println("The color is "+powerbank15.color);
		powerbank15.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank15.numberOfPorts);
		powerbank15.type="Li-Ion";
		System.out.println("Type is "+powerbank15.type);

		Powerbank powerbank16=new Powerbank();
		powerbank16.brand="Zebronics";
		System.out.println("The brand is "+powerbank16.brand);
		powerbank16.capacity=20000;
		System.out.println("The capacity is "+powerbank16.capacity);
		powerbank16.outputPower=22;
		System.out.println("The output power is "+powerbank16.outputPower);
		powerbank16.inputPower=15;
		System.out.println("The input power is "+powerbank16.inputPower);
		powerbank16.weight=420;
		System.out.println("The weight is "+powerbank16.weight);
		powerbank16.color="Black";
		System.out.println("The color is "+powerbank16.color);
		powerbank16.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank16.numberOfPorts);
		powerbank16.type="Li-Polymer";
		System.out.println("Type is "+powerbank16.type);

		Powerbank powerbank17=new Powerbank();
		powerbank17.brand="Portronics";
		System.out.println("The brand is "+powerbank17.brand);
		powerbank17.capacity=10000;
		System.out.println("The capacity is "+powerbank17.capacity);
		powerbank17.outputPower=18;
		System.out.println("The output power is "+powerbank17.outputPower);
		powerbank17.inputPower=12;
		System.out.println("The input power is "+powerbank17.inputPower);
		powerbank17.weight=260;
		System.out.println("The weight is "+powerbank17.weight);
		powerbank17.color="Grey";
		System.out.println("The color is "+powerbank17.color);
		powerbank17.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank17.numberOfPorts);
		powerbank17.type="Li-Ion";
		System.out.println("Type is "+powerbank17.type);

		Powerbank powerbank18=new Powerbank();
		powerbank18.brand="Intex";
		System.out.println("The brand is "+powerbank18.brand);
		powerbank18.capacity=15000;
		System.out.println("The capacity is "+powerbank18.capacity);
		powerbank18.outputPower=20;
		System.out.println("The output power is "+powerbank18.outputPower);
		powerbank18.inputPower=12;
		System.out.println("The input power is "+powerbank18.inputPower);
		powerbank18.weight=300;
		System.out.println("The weight is "+powerbank18.weight);
		powerbank18.color="White";
		System.out.println("The color is "+powerbank18.color);
		powerbank18.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank18.numberOfPorts);
		powerbank18.type="Li-Polymer";
		System.out.println("Type is "+powerbank18.type);

		Powerbank powerbank19=new Powerbank();
		powerbank19.brand="Micromax";
		System.out.println("The brand is "+powerbank19.brand);
		powerbank19.capacity=10000;
		System.out.println("The capacity is "+powerbank19.capacity);
		powerbank19.outputPower=15;
		System.out.println("The output power is "+powerbank19.outputPower);
		powerbank19.inputPower=10;
		System.out.println("The input power is "+powerbank19.inputPower);
		powerbank19.weight=250;
		System.out.println("The weight is "+powerbank19.weight);
		powerbank19.color="Black";
		System.out.println("The color is "+powerbank19.color);
		powerbank19.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank19.numberOfPorts);
		powerbank19.type="Li-Ion";
		System.out.println("Type is "+powerbank19.type);

		Powerbank powerbank20=new Powerbank();
		powerbank20.brand="iBall";
		System.out.println("The brand is "+powerbank20.brand);
		powerbank20.capacity=20000;
		System.out.println("The capacity is "+powerbank20.capacity);
		powerbank20.outputPower=25;
		System.out.println("The output power is "+powerbank20.outputPower);
		powerbank20.inputPower=18;
		System.out.println("The input power is "+powerbank20.inputPower);
		powerbank20.weight=450;
		System.out.println("The weight is "+powerbank20.weight);
		powerbank20.color="Blue";
		System.out.println("The color is "+powerbank20.color);
		powerbank20.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank20.numberOfPorts);
		powerbank20.type="Li-Polymer";
		System.out.println("Type is "+powerbank20.type);

		Powerbank powerbank21=new Powerbank();
		powerbank21.brand="Ambrane";
		System.out.println("The brand is "+powerbank21.brand);
		powerbank21.capacity=10000;
		System.out.println("The capacity is "+powerbank21.capacity);
		powerbank21.outputPower=18;
		System.out.println("The output power is "+powerbank21.outputPower);
		powerbank21.inputPower=10;
		System.out.println("The input power is "+powerbank21.inputPower);
		powerbank21.weight=260;
		System.out.println("The weight is "+powerbank21.weight);
		powerbank21.color="Black";
		System.out.println("The color is "+powerbank21.color);
		powerbank21.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank21.numberOfPorts);
		powerbank21.type="Li-Ion";
		System.out.println("Type is "+powerbank21.type);

		Powerbank powerbank22=new Powerbank();
		powerbank22.brand="Syska";
		System.out.println("The brand is "+powerbank22.brand);
		powerbank22.capacity=20000;
		System.out.println("The capacity is "+powerbank22.capacity);
		powerbank22.outputPower=22;
		System.out.println("The output power is "+powerbank22.outputPower);
		powerbank22.inputPower=15;
		System.out.println("The input power is "+powerbank22.inputPower);
		powerbank22.weight=420;
		System.out.println("The weight is "+powerbank22.weight);
		powerbank22.color="Grey";
		System.out.println("The color is "+powerbank22.color);
		powerbank22.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank22.numberOfPorts);
		powerbank22.type="Li-Polymer";
		System.out.println("Type is "+powerbank22.type);

		Powerbank powerbank23=new Powerbank();
		powerbank23.brand="Boat";
		System.out.println("The brand is "+powerbank23.brand);
		powerbank23.capacity=10000;
		System.out.println("The capacity is "+powerbank23.capacity);
		powerbank23.outputPower=15;
		System.out.println("The output power is "+powerbank23.outputPower);
		powerbank23.inputPower=10;
		System.out.println("The input power is "+powerbank23.inputPower);
		powerbank23.weight=250;
		System.out.println("The weight is "+powerbank23.weight);
		powerbank23.color="Red";
		System.out.println("The color is "+powerbank23.color);
		powerbank23.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank23.numberOfPorts);
		powerbank23.type="Li-Ion";
		System.out.println("Type is "+powerbank23.type);

		Powerbank powerbank24=new Powerbank();
		powerbank24.brand="Anker";
		System.out.println("The brand is "+powerbank24.brand);
		powerbank24.capacity=20000;
		System.out.println("The capacity is "+powerbank24.capacity);
		powerbank24.outputPower=30;
		System.out.println("The output power is "+powerbank24.outputPower);
		powerbank24.inputPower=18;
		System.out.println("The input power is "+powerbank24.inputPower);
		powerbank24.weight=500;
		System.out.println("The weight is "+powerbank24.weight);
		powerbank24.color="Black";
		System.out.println("The color is "+powerbank24.color);
		powerbank24.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank24.numberOfPorts);
		powerbank24.type="Li-Polymer";
		System.out.println("Type is "+powerbank24.type);

		Powerbank powerbank25=new Powerbank();
		powerbank25.brand="Sony";
		System.out.println("The brand is "+powerbank25.brand);
		powerbank25.capacity=15000;
		System.out.println("The capacity is "+powerbank25.capacity);
		powerbank25.outputPower=20;
		System.out.println("The output power is "+powerbank25.outputPower);
		powerbank25.inputPower=12;
		System.out.println("The input power is "+powerbank25.inputPower);
		powerbank25.weight=340;
		System.out.println("The weight is "+powerbank25.weight);
		powerbank25.color="White";
		System.out.println("The color is "+powerbank25.color);
		powerbank25.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank25.numberOfPorts);
		powerbank25.type="Li-Ion";
		System.out.println("Type is "+powerbank25.type);

		Powerbank powerbank26=new Powerbank();
		powerbank26.brand="Oppo";
		System.out.println("The brand is "+powerbank26.brand);
		powerbank26.capacity=10000;
		System.out.println("The capacity is "+powerbank26.capacity);
		powerbank26.outputPower=18;
		System.out.println("The output power is "+powerbank26.outputPower);
		powerbank26.inputPower=10;
		System.out.println("The input power is "+powerbank26.inputPower);
		powerbank26.weight=270;
		System.out.println("The weight is "+powerbank26.weight);
		powerbank26.color="Green";
		System.out.println("The color is "+powerbank26.color);
		powerbank26.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank26.numberOfPorts);
		powerbank26.type="Li-Polymer";
		System.out.println("Type is "+powerbank26.type);

		Powerbank powerbank27=new Powerbank();
		powerbank27.brand="Vivo";
		System.out.println("The brand is "+powerbank27.brand);
		powerbank27.capacity=20000;
		System.out.println("The capacity is "+powerbank27.capacity);
		powerbank27.outputPower=22;
		System.out.println("The output power is "+powerbank27.outputPower);
		powerbank27.inputPower=15;
		System.out.println("The input power is "+powerbank27.inputPower);
		powerbank27.weight=450;
		System.out.println("The weight is "+powerbank27.weight);
		powerbank27.color="Blue";
		System.out.println("The color is "+powerbank27.color);
		powerbank27.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank27.numberOfPorts);
		powerbank27.type="Li-Ion";
		System.out.println("Type is "+powerbank27.type);

		Powerbank powerbank28=new Powerbank();
		powerbank28.brand="OnePlus";
		System.out.println("The brand is "+powerbank28.brand);
		powerbank28.capacity=10000;
		System.out.println("The capacity is "+powerbank28.capacity);
		powerbank28.outputPower=18;
		System.out.println("The output power is "+powerbank28.outputPower);
		powerbank28.inputPower=10;
		System.out.println("The input power is "+powerbank28.inputPower);
		powerbank28.weight=260;
		System.out.println("The weight is "+powerbank28.weight);
		powerbank28.color="Black";
		System.out.println("The color is "+powerbank28.color);
		powerbank28.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank28.numberOfPorts);
		powerbank28.type="Li-Polymer";
		System.out.println("Type is "+powerbank28.type);

		Powerbank powerbank29=new Powerbank();
		powerbank29.brand="Honor";
		System.out.println("The brand is "+powerbank29.brand);
		powerbank29.capacity=15000;
		System.out.println("The capacity is "+powerbank29.capacity);
		powerbank29.outputPower=20;
		System.out.println("The output power is "+powerbank29.outputPower);
		powerbank29.inputPower=12;
		System.out.println("The input power is "+powerbank29.inputPower);
		powerbank29.weight=330;
		System.out.println("The weight is "+powerbank29.weight);
		powerbank29.color="Grey";
		System.out.println("The color is "+powerbank29.color);
		powerbank29.numberOfPorts=2;
		System.out.println("Number of ports "+powerbank29.numberOfPorts);
		powerbank29.type="Li-Ion";
		System.out.println("Type is "+powerbank29.type);

		Powerbank powerbank30=new Powerbank();
		powerbank30.brand="Nothing";
		System.out.println("The brand is "+powerbank30.brand);
		powerbank30.capacity=20000;
		System.out.println("The capacity is "+powerbank30.capacity);
		powerbank30.outputPower=25;
		System.out.println("The output power is "+powerbank30.outputPower);
		powerbank30.inputPower=18;
		System.out.println("The input power is "+powerbank30.inputPower);
		powerbank30.weight=460;
		System.out.println("The weight is "+powerbank30.weight);
		powerbank30.color="White";
		System.out.println("The color is "+powerbank30.color);
		powerbank30.numberOfPorts=3;
		System.out.println("Number of ports "+powerbank30.numberOfPorts);
		powerbank30.type="Li-Polymer";
		System.out.println("Type is "+powerbank30.type);
	}

}