class RingExec
{
	public static void main(String[] args)
	{
		Ring r1 = new Ring();
		r1.brand="Tanishq";
		System.out.println("The brand is "+r1.brand);
		r1.cost=15000;
		System.out.println("The cost is "+r1.cost);
		r1.colour="Gold";
		System.out.println("The colour is "+r1.colour);
		r1.material="Gold";
		System.out.println("The material is "+r1.material);
		r1.type="Wedding";
		System.out.println("The type is "+r1.type);
		r1.size=16;
		System.out.println("The size is "+r1.size);
		r1.isAdjustable=false;
		System.out.println("Adjustable: "+r1.isAdjustable);
		r1.design="Plain";
		System.out.println("The design is "+r1.design);

		Ring r2 = new Ring();
		r2.brand="Malabar";
		System.out.println("The brand is "+r2.brand);
		r2.cost=12000;
		System.out.println("The cost is "+r2.cost);
		r2.colour="Gold";
		System.out.println("The colour is "+r2.colour);
		r2.material="Gold";
		System.out.println("The material is "+r2.material);
		r2.type="Casual";
		System.out.println("The type is "+r2.type);
		r2.size=15;
		System.out.println("The size is "+r2.size);
		r2.isAdjustable=true;
		System.out.println("Adjustable: "+r2.isAdjustable);
		r2.design="Stone";
		System.out.println("The design is "+r2.design);

		Ring r3 = new Ring();
		r3.brand="Kalyan";
		System.out.println("The brand is "+r3.brand);
		r3.cost=18000;
		System.out.println("The cost is "+r3.cost);
		r3.colour="Gold";
		System.out.println("The colour is "+r3.colour);
		r3.material="Gold";
		System.out.println("The material is "+r3.material);
		r3.type="Engagement";
		System.out.println("The type is "+r3.type);
		r3.size=17;
		System.out.println("The size is "+r3.size);
		r3.isAdjustable=false;
		System.out.println("Adjustable: "+r3.isAdjustable);
		r3.design="Diamond";
		System.out.println("The design is "+r3.design);

		Ring r4 = new Ring();
		r4.brand="PC Jeweller";
		System.out.println("The brand is "+r4.brand);
		r4.cost=14000;
		System.out.println("The cost is "+r4.cost);
		r4.colour="Silver";
		System.out.println("The colour is "+r4.colour);
		r4.material="Silver";
		System.out.println("The material is "+r4.material);
		r4.type="Casual";
		System.out.println("The type is "+r4.type);
		r4.size=14;
		System.out.println("The size is "+r4.size);
		r4.isAdjustable=true;
		System.out.println("Adjustable: "+r4.isAdjustable);
		r4.design="Plain";
		System.out.println("The design is "+r4.design);

		Ring r5 = new Ring();
		r5.brand="Bluestone";
		System.out.println("The brand is "+r5.brand);
		r5.cost=20000;
		System.out.println("The cost is "+r5.cost);
		r5.colour="Gold";
		System.out.println("The colour is "+r5.colour);
		r5.material="Gold";
		System.out.println("The material is "+r5.material);
		r5.type="Engagement";
		System.out.println("The type is "+r5.type);
		r5.size=16;
		System.out.println("The size is "+r5.size);
		r5.isAdjustable=false;
		System.out.println("Adjustable: "+r5.isAdjustable);
		r5.design="Diamond";
		System.out.println("The design is "+r5.design);

		Ring r6 = new Ring();
		r6.brand="CaratLane";
		System.out.println("The brand is "+r6.brand);
		r6.cost=22000;
		System.out.println("The cost is "+r6.cost);
		r6.colour="Gold";
		System.out.println("The colour is "+r6.colour);
		r6.material="Gold";
		System.out.println("The material is "+r6.material);
		r6.type="Wedding";
		System.out.println("The type is "+r6.type);
		r6.size=18;
		System.out.println("The size is "+r6.size);
		r6.isAdjustable=false;
		System.out.println("Adjustable: "+r6.isAdjustable);
		r6.design="Diamond";
		System.out.println("The design is "+r6.design);

		Ring r7 = new Ring();
		r7.brand="Joyalukkas";
		System.out.println("The brand is "+r7.brand);
		r7.cost=16000;
		System.out.println("The cost is "+r7.cost);
		r7.colour="Gold";
		System.out.println("The colour is "+r7.colour);
		r7.material="Gold";
		System.out.println("The material is "+r7.material);
		r7.type="Casual";
		System.out.println("The type is "+r7.type);
		r7.size=15;
		System.out.println("The size is "+r7.size);
		r7.isAdjustable=true;
		System.out.println("Adjustable: "+r7.isAdjustable);
		r7.design="Stone";
		System.out.println("The design is "+r7.design);

		Ring r8 = new Ring();
		r8.brand="GRT";
		System.out.println("The brand is "+r8.brand);
		r8.cost=17000;
		System.out.println("The cost is "+r8.cost);
		r8.colour="Gold";
		System.out.println("The colour is "+r8.colour);
		r8.material="Gold";
		System.out.println("The material is "+r8.material);
		r8.type="Wedding";
		System.out.println("The type is "+r8.type);
		r8.size=16;
		System.out.println("The size is "+r8.size);
		r8.isAdjustable=false;
		System.out.println("Adjustable: "+r8.isAdjustable);
		r8.design="Plain";
		System.out.println("The design is "+r8.design);

		Ring r9 = new Ring();
		r9.brand="Reliance Jewels";
		System.out.println("The brand is "+r9.brand);
		r9.cost=13000;
		System.out.println("The cost is "+r9.cost);
		r9.colour="Silver";
		System.out.println("The colour is "+r9.colour);
		r9.material="Silver";
		System.out.println("The material is "+r9.material);
		r9.type="Casual";
		System.out.println("The type is "+r9.type);
		r9.size=14;
		System.out.println("The size is "+r9.size);
		r9.isAdjustable=true;
		System.out.println("Adjustable: "+r9.isAdjustable);
		r9.design="Plain";
		System.out.println("The design is "+r9.design);

		Ring r10 = new Ring();
		r10.brand="Senco";
		System.out.println("The brand is "+r10.brand);
		r10.cost=19000;
		System.out.println("The cost is "+r10.cost);
		r10.colour="Gold";
		System.out.println("The colour is "+r10.colour);
		r10.material="Gold";
		System.out.println("The material is "+r10.material);
		r10.type="Engagement";
		System.out.println("The type is "+r10.type);
		r10.size=17;
		System.out.println("The size is "+r10.size);
		r10.isAdjustable=false;
		System.out.println("Adjustable: "+r10.isAdjustable);
		r10.design="Diamond";
		System.out.println("The design is "+r10.design);
		
				Ring r11 = new Ring();
		r11.brand="TBZ";
		System.out.println("The brand is "+r11.brand);
		r11.cost=21000;
		System.out.println("The cost is "+r11.cost);
		r11.colour="Gold";
		System.out.println("The colour is "+r11.colour);
		r11.material="Gold";
		System.out.println("The material is "+r11.material);
		r11.type="Wedding";
		System.out.println("The type is "+r11.type);
		r11.size=18;
		System.out.println("The size is "+r11.size);
		r11.isAdjustable=false;
		System.out.println("Adjustable: "+r11.isAdjustable);
		r11.design="Diamond";
		System.out.println("The design is "+r11.design);

		Ring r12 = new Ring();
		r12.brand="Amrapali";
		System.out.println("The brand is "+r12.brand);
		r12.cost=14000;
		System.out.println("The cost is "+r12.cost);
		r12.colour="Silver";
		System.out.println("The colour is "+r12.colour);
		r12.material="Silver";
		System.out.println("The material is "+r12.material);
		r12.type="Casual";
		System.out.println("The type is "+r12.type);
		r12.size=14;
		System.out.println("The size is "+r12.size);
		r12.isAdjustable=true;
		System.out.println("Adjustable: "+r12.isAdjustable);
		r12.design="Stone";
		System.out.println("The design is "+r12.design);

		Ring r13 = new Ring();
		r13.brand="Orra";
		System.out.println("The brand is "+r13.brand);
		r13.cost=23000;
		System.out.println("The cost is "+r13.cost);
		r13.colour="Gold";
		System.out.println("The colour is "+r13.colour);
		r13.material="Gold";
		System.out.println("The material is "+r13.material);
		r13.type="Engagement";
		System.out.println("The type is "+r13.type);
		r13.size=17;
		System.out.println("The size is "+r13.size);
		r13.isAdjustable=false;
		System.out.println("Adjustable: "+r13.isAdjustable);
		r13.design="Diamond";
		System.out.println("The design is "+r13.design);

		Ring r14 = new Ring();
		r14.brand="Zoya";
		System.out.println("The brand is "+r14.brand);
		r14.cost=25000;
		System.out.println("The cost is "+r14.cost);
		r14.colour="Gold";
		System.out.println("The colour is "+r14.colour);
		r14.material="Gold";
		System.out.println("The material is "+r14.material);
		r14.type="Wedding";
		System.out.println("The type is "+r14.type);
		r14.size=18;
		System.out.println("The size is "+r14.size);
		r14.isAdjustable=false;
		System.out.println("Adjustable: "+r14.isAdjustable);
		r14.design="Designer";
		System.out.println("The design is "+r14.design);

		Ring r15 = new Ring();
		r15.brand="Mejuri";
		System.out.println("The brand is "+r15.brand);
		r15.cost=12000;
		System.out.println("The cost is "+r15.cost);
		r15.colour="Gold";
		System.out.println("The colour is "+r15.colour);
		r15.material="Gold";
		System.out.println("The material is "+r15.material);
		r15.type="Casual";
		System.out.println("The type is "+r15.type);
		r15.size=15;
		System.out.println("The size is "+r15.size);
		r15.isAdjustable=true;
		System.out.println("Adjustable: "+r15.isAdjustable);
		r15.design="Plain";
		System.out.println("The design is "+r15.design);

		Ring r16 = new Ring();
		r16.brand="Pandora";
		System.out.println("The brand is "+r16.brand);
		r16.cost=18000;
		System.out.println("The cost is "+r16.cost);
		r16.colour="Silver";
		System.out.println("The colour is "+r16.colour);
		r16.material="Silver";
		System.out.println("The material is "+r16.material);
		r16.type="Casual";
		System.out.println("The type is "+r16.type);
		r16.size=14;
		System.out.println("The size is "+r16.size);
		r16.isAdjustable=true;
		System.out.println("Adjustable: "+r16.isAdjustable);
		r16.design="Stone";
		System.out.println("The design is "+r16.design);

		Ring r17 = new Ring();
		r17.brand="BlueStone X";
		System.out.println("The brand is "+r17.brand);
		r17.cost=21000;
		System.out.println("The cost is "+r17.cost);
		r17.colour="Gold";
		System.out.println("The colour is "+r17.colour);
		r17.material="Gold";
		System.out.println("The material is "+r17.material);
		r17.type="Engagement";
		System.out.println("The type is "+r17.type);
		r17.size=17;
		System.out.println("The size is "+r17.size);
		r17.isAdjustable=false;
		System.out.println("Adjustable: "+r17.isAdjustable);
		r17.design="Diamond";
		System.out.println("The design is "+r17.design);

		Ring r18 = new Ring();
		r18.brand="Kalyan X";
		System.out.println("The brand is "+r18.brand);
		r18.cost=20000;
		System.out.println("The cost is "+r18.cost);
		r18.colour="Gold";
		System.out.println("The colour is "+r18.colour);
		r18.material="Gold";
		System.out.println("The material is "+r18.material);
		r18.type="Wedding";
		System.out.println("The type is "+r18.type);
		r18.size=18;
		System.out.println("The size is "+r18.size);
		r18.isAdjustable=false;
		System.out.println("Adjustable: "+r18.isAdjustable);
		r18.design="Designer";
		System.out.println("The design is "+r18.design);

		Ring r19 = new Ring();
		r19.brand="Malabar X";
		System.out.println("The brand is "+r19.brand);
		r19.cost=15000;
		System.out.println("The cost is "+r19.cost);
		r19.colour="Silver";
		System.out.println("The colour is "+r19.colour);
		r19.material="Silver";
		System.out.println("The material is "+r19.material);
		r19.type="Casual";
		System.out.println("The type is "+r19.type);
		r19.size=15;
		System.out.println("The size is "+r19.size);
		r19.isAdjustable=true;
		System.out.println("Adjustable: "+r19.isAdjustable);
		r19.design="Plain";
		System.out.println("The design is "+r19.design);

		Ring r20 = new Ring();
		r20.brand="Tanishq X";
		System.out.println("The brand is "+r20.brand);
		r20.cost=26000;
		System.out.println("The cost is "+r20.cost);
		r20.colour="Gold";
		System.out.println("The colour is "+r20.colour);
		r20.material="Gold";
		System.out.println("The material is "+r20.material);
		r20.type="Wedding";
		System.out.println("The type is "+r20.type);
		r20.size=19;
		System.out.println("The size is "+r20.size);
		r20.isAdjustable=false;
		System.out.println("Adjustable: "+r20.isAdjustable);
		r20.design="Diamond";
		System.out.println("The design is "+r20.design);
		
				Ring r21 = new Ring();
		r21.brand="Local Brand";
		System.out.println("The brand is "+r21.brand);
		r21.cost=5000;
		System.out.println("The cost is "+r21.cost);
		r21.colour="Silver";
		System.out.println("The colour is "+r21.colour);
		r21.material="Silver";
		System.out.println("The material is "+r21.material);
		r21.type="Casual";
		System.out.println("The type is "+r21.type);
		r21.size=13;
		System.out.println("The size is "+r21.size);
		r21.isAdjustable=true;
		System.out.println("Adjustable: "+r21.isAdjustable);
		r21.design="Plain";
		System.out.println("The design is "+r21.design);

		Ring r22 = new Ring();
		r22.brand="Street Style";
		System.out.println("The brand is "+r22.brand);
		r22.cost=3000;
		System.out.println("The cost is "+r22.cost);
		r22.colour="Black";
		System.out.println("The colour is "+r22.colour);
		r22.material="Alloy";
		System.out.println("The material is "+r22.material);
		r22.type="Casual";
		System.out.println("The type is "+r22.type);
		r22.size=14;
		System.out.println("The size is "+r22.size);
		r22.isAdjustable=true;
		System.out.println("Adjustable: "+r22.isAdjustable);
		r22.design="Modern";
		System.out.println("The design is "+r22.design);

		Ring r23 = new Ring();
		r23.brand="Silver Shine";
		System.out.println("The brand is "+r23.brand);
		r23.cost=6000;
		System.out.println("The cost is "+r23.cost);
		r23.colour="Silver";
		System.out.println("The colour is "+r23.colour);
		r23.material="Silver";
		System.out.println("The material is "+r23.material);
		r23.type="Casual";
		System.out.println("The type is "+r23.type);
		r23.size=15;
		System.out.println("The size is "+r23.size);
		r23.isAdjustable=true;
		System.out.println("Adjustable: "+r23.isAdjustable);
		r23.design="Stone";
		System.out.println("The design is "+r23.design);

		Ring r24 = new Ring();
		r24.brand="Gold Art";
		System.out.println("The brand is "+r24.brand);
		r24.cost=15000;
		System.out.println("The cost is "+r24.cost);
		r24.colour="Gold";
		System.out.println("The colour is "+r24.colour);
		r24.material="Gold";
		System.out.println("The material is "+r24.material);
		r24.type="Wedding";
		System.out.println("The type is "+r24.type);
		r24.size=16;
		System.out.println("The size is "+r24.size);
		r24.isAdjustable=false;
		System.out.println("Adjustable: "+r24.isAdjustable);
		r24.design="Designer";
		System.out.println("The design is "+r24.design);

		Ring r25 = new Ring();
		r25.brand="Diamond Hub";
		System.out.println("The brand is "+r25.brand);
		r25.cost=30000;
		System.out.println("The cost is "+r25.cost);
		r25.colour="Gold";
		System.out.println("The colour is "+r25.colour);
		r25.material="Gold";
		System.out.println("The material is "+r25.material);
		r25.type="Engagement";
		System.out.println("The type is "+r25.type);
		r25.size=18;
		System.out.println("The size is "+r25.size);
		r25.isAdjustable=false;
		System.out.println("Adjustable: "+r25.isAdjustable);
		r25.design="Diamond";
		System.out.println("The design is "+r25.design);

		Ring r26 = new Ring();
		r26.brand="Fashion Ring";
		System.out.println("The brand is "+r26.brand);
		r26.cost=2000;
		System.out.println("The cost is "+r26.cost);
		r26.colour="Pink";
		System.out.println("The colour is "+r26.colour);
		r26.material="Alloy";
		System.out.println("The material is "+r26.material);
		r26.type="Casual";
		System.out.println("The type is "+r26.type);
		r26.size=13;
		System.out.println("The size is "+r26.size);
		r26.isAdjustable=true;
		System.out.println("Adjustable: "+r26.isAdjustable);
		r26.design="Modern";
		System.out.println("The design is "+r26.design);

		Ring r27 = new Ring();
		r27.brand="Classic Gold";
		System.out.println("The brand is "+r27.brand);
		r27.cost=18000;
		System.out.println("The cost is "+r27.cost);
		r27.colour="Gold";
		System.out.println("The colour is "+r27.colour);
		r27.material="Gold";
		System.out.println("The material is "+r27.material);
		r27.type="Wedding";
		System.out.println("The type is "+r27.type);
		r27.size=17;
		System.out.println("The size is "+r27.size);
		r27.isAdjustable=false;
		System.out.println("Adjustable: "+r27.isAdjustable);
		r27.design="Plain";
		System.out.println("The design is "+r27.design);

		Ring r28 = new Ring();
		r28.brand="Modern Style";
		System.out.println("The brand is "+r28.brand);
		r28.cost=4000;
		System.out.println("The cost is "+r28.cost);
		r28.colour="Black";
		System.out.println("The colour is "+r28.colour);
		r28.material="Alloy";
		System.out.println("The material is "+r28.material);
		r28.type="Casual";
		System.out.println("The type is "+r28.type);
		r28.size=14;
		System.out.println("The size is "+r28.size);
		r28.isAdjustable=true;
		System.out.println("Adjustable: "+r28.isAdjustable);
		r28.design="Trendy";
		System.out.println("The design is "+r28.design);

		Ring r29 = new Ring();
		r29.brand="Royal Gold";
		System.out.println("The brand is "+r29.brand);
		r29.cost=27000;
		System.out.println("The cost is "+r29.cost);
		r29.colour="Gold";
		System.out.println("The colour is "+r29.colour);
		r29.material="Gold";
		System.out.println("The material is "+r29.material);
		r29.type="Engagement";
		System.out.println("The type is "+r29.type);
		r29.size=18;
		System.out.println("The size is "+r29.size);
		r29.isAdjustable=false;
		System.out.println("Adjustable: "+r29.isAdjustable);
		r29.design="Diamond";
		System.out.println("The design is "+r29.design);

		Ring r30 = new Ring();
		r30.brand="Elite Rings";
		System.out.println("The brand is "+r30.brand);
		r30.cost=22000;
		System.out.println("The cost is "+r30.cost);
		r30.colour="Gold";
		System.out.println("The colour is "+r30.colour);
		r30.material="Gold";
		System.out.println("The material is "+r30.material);
		r30.type="Wedding";
		System.out.println("The type is "+r30.type);
		r30.size=17;
		System.out.println("The size is "+r30.size);
		r30.isAdjustable=false;
		System.out.println("Adjustable: "+r30.isAdjustable);
		r30.design="Designer";
		System.out.println("The design is "+r30.design);
	}
}