class ShoeExec
{
	public static void main(String[] ref)
	{
		Shoe shoe = new Shoe();
		shoe.brand = "Nike";
		System.out.println("The brand of a shoe is "+shoe.brand);
		shoe.cost = 2540;
		System.out.println("The cost of the shoe is "+shoe.cost);
		shoe.weight = 350;
		System.out.println("The weight of a shoe is "+shoe.weight);
		shoe.material = "Leather";
		System.out.println("The shoe material is "+shoe.material);
		shoe.type = "formals";
		System.out.println("The type of a shoe is "+shoe.type);
		shoe.countryOfOrigin = "India";
		System.out.println("The shoe is manufactured in "+shoe.countryOfOrigin);
		shoe.manufracturer = "HIMANSHI FASHION";
		System.out.println("the manufracturer of shoe is "+shoe.manufracturer);
		shoe.quantity =1;
		System.out.println("The quantity of a shoe is "+shoe.quantity+" pair");		
		
		Shoe shoe1 = new Shoe();
		shoe1.brand = "Nike";
		System.out.println("The shoe brand is "+shoe1.brand);
		shoe1.cost = 3500;
		System.out.println("The cost of a shoe is "+shoe1.cost);
		shoe1.weight = 500;
		System.out.println("The weight of a shoe is "+shoe1.weight +" gm");
		shoe1.material = "";
		System.out.println("The material of a shoe is "+shoe1.material);
		shoe1.type = "Sports shoe";
		System.out.println("The type of shoe is "+shoe1.type);
		shoe1.countryOfOrigin = "India";
		System.out.println("The shoe is manufactured in "+shoe1.countryOfOrigin);
		shoe1.manufracturer = "HIMANSHI FASHION";
		System.out.println("The manufracturer is "+shoe1.manufracturer);
		shoe1.quantity = 1;
		System.out.println("the quantity of a shoe is "+shoe1.quantity);
	
		Shoe shoe2=new Shoe();
		shoe2.brand="Reebok";
		System.out.println("The brand of a shoe is "+shoe2.brand);
		shoe2.cost=2599;
		System.out.println("The cost of the shoe is "+shoe2.cost);
		shoe2.weight=400;
		System.out.println("The weight of a shoe is "+shoe2.weight);
		shoe2.material="Synthetic";
		System.out.println("The shoe material is "+shoe2.material);
		shoe2.type="Running";
		System.out.println("The type of a shoe is "+shoe2.type);
		shoe2.countryOfOrigin="USA";
		System.out.println("The shoe is manufactured in "+shoe2.countryOfOrigin);
		shoe2.manufracturer="Reebok Ltd";
		System.out.println("the manufracturer of shoe is "+shoe2.manufracturer);
		shoe2.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe2.quantity+" pair");
		Shoe shoe3=new Shoe();
		shoe3.brand="Woodland";
		System.out.println("The brand of a shoe is "+shoe3.brand);
		shoe3.cost=3499;
		System.out.println("The cost of the shoe is "+shoe3.cost);
		shoe3.weight=500;
		System.out.println("The weight of a shoe is "+shoe3.weight);
		shoe3.material="Leather";
		System.out.println("The shoe material is "+shoe3.material);
		shoe3.type="Boots";
		System.out.println("The type of a shoe is "+shoe3.type);
		shoe3.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe3.countryOfOrigin);
		shoe3.manufracturer="Woodland India";
		System.out.println("the manufracturer of shoe is "+shoe3.manufracturer);
		shoe3.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe3.quantity+" pair");
		Shoe shoe4=new Shoe();
		shoe4.brand="Bata";
		System.out.println("The brand of a shoe is "+shoe4.brand);
		shoe4.cost=1999;
		System.out.println("The cost of the shoe is "+shoe4.cost);
		shoe4.weight=450;
		System.out.println("The weight of a shoe is "+shoe4.weight);
		shoe4.material="Rubber";
		System.out.println("The shoe material is "+shoe4.material);
		shoe4.type="Formal";
		System.out.println("The type of a shoe is "+shoe4.type);
		shoe4.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe4.countryOfOrigin);
		shoe4.manufracturer="Bata India";
		System.out.println("the manufracturer of shoe is "+shoe4.manufracturer);
		shoe4.quantity=3;
		System.out.println("The quantity of a shoe is "+shoe4.quantity+" pair");
		Shoe shoe5=new Shoe();
		shoe5.brand="Sparx";
		System.out.println("The brand of a shoe is "+shoe5.brand);
		shoe5.cost=1499;
		System.out.println("The cost of the shoe is "+shoe5.cost);
		shoe5.weight=350;
		System.out.println("The weight of a shoe is "+shoe5.weight);
		shoe5.material="Mesh";
		System.out.println("The shoe material is "+shoe5.material);
		shoe5.type="Casual";
		System.out.println("The type of a shoe is "+shoe5.type);
		shoe5.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe5.countryOfOrigin);
		shoe5.manufracturer="Relaxo";
		System.out.println("the manufracturer of shoe is "+shoe5.manufracturer);
		shoe5.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe5.quantity+" pair");
		Shoe shoe6=new Shoe();
		shoe6.brand="Nike";
		System.out.println("The brand of a shoe is "+shoe6.brand);
		shoe6.cost=4999;
		System.out.println("The cost of the shoe is "+shoe6.cost);
		shoe6.weight=420;
		System.out.println("The weight of a shoe is "+shoe6.weight);
		shoe6.material="Flyknit";
		System.out.println("The shoe material is "+shoe6.material);
		shoe6.type="Sports";
		System.out.println("The type of a shoe is "+shoe6.type);
		shoe6.countryOfOrigin="USA";
		System.out.println("The shoe is manufactured in "+shoe6.countryOfOrigin);
		shoe6.manufracturer="Nike Inc";
		System.out.println("the manufracturer of shoe is "+shoe6.manufracturer);
		shoe6.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe6.quantity+" pair");
		Shoe shoe7=new Shoe();
		shoe7.brand="Adidas";
		System.out.println("The brand of a shoe is "+shoe7.brand);
		shoe7.cost=4599;
		System.out.println("The cost of the shoe is "+shoe7.cost);
		shoe7.weight=410;
		System.out.println("The weight of a shoe is "+shoe7.weight);
		shoe7.material="Primeknit";
		System.out.println("The shoe material is "+shoe7.material);
		shoe7.type="Running";
		System.out.println("The type of a shoe is "+shoe7.type);
		shoe7.countryOfOrigin="Germany";
		System.out.println("The shoe is manufactured in "+shoe7.countryOfOrigin);
		shoe7.manufracturer="Adidas AG";
		System.out.println("the manufracturer of shoe is "+shoe7.manufracturer);
		shoe7.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe7.quantity+" pair");
		Shoe shoe8=new Shoe();
		shoe8.brand="Fila";
		System.out.println("The brand of a shoe is "+shoe8.brand);
		shoe8.cost=2799;
		System.out.println("The cost of the shoe is "+shoe8.cost);
		shoe8.weight=390;
		System.out.println("The weight of a shoe is "+shoe8.weight);
		shoe8.material="Canvas";
		System.out.println("The shoe material is "+shoe8.material);
		shoe8.type="Casual";
		System.out.println("The type of a shoe is "+shoe8.type);
		shoe8.countryOfOrigin="Italy";
		System.out.println("The shoe is manufactured in "+shoe8.countryOfOrigin);
		shoe8.manufracturer="Fila Ltd";
		System.out.println("the manufracturer of shoe is "+shoe8.manufracturer);
		shoe8.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe8.quantity+" pair");
		Shoe shoe9=new Shoe();
		shoe9.brand="Crocs";
		System.out.println("The brand of a shoe is "+shoe9.brand);
		shoe9.cost=1999;
		System.out.println("The cost of the shoe is "+shoe9.cost);
		shoe9.weight=300;
		System.out.println("The weight of a shoe is "+shoe9.weight);
		shoe9.material="Foam";
		System.out.println("The shoe material is "+shoe9.material);
		shoe9.type="Slippers";
		System.out.println("The type of a shoe is "+shoe9.type);
		shoe9.countryOfOrigin="USA";
		System.out.println("The shoe is manufactured in "+shoe9.countryOfOrigin);
		shoe9.manufracturer="Crocs Inc";
		System.out.println("the manufracturer of shoe is "+shoe9.manufracturer);
		shoe9.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe9.quantity+" pair");
		Shoe shoe10=new Shoe();
		shoe10.brand="Campus";
		System.out.println("The brand of a shoe is "+shoe10.brand);
		shoe10.cost=1299;
		System.out.println("The cost of the shoe is "+shoe10.cost);
		shoe10.weight=340;
		System.out.println("The weight of a shoe is "+shoe10.weight);
		shoe10.material="Mesh";
		System.out.println("The shoe material is "+shoe10.material);
		shoe10.type="Sports";
		System.out.println("The type of a shoe is "+shoe10.type);
		shoe10.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe10.countryOfOrigin);
		shoe10.manufracturer="Campus Activewear";
		System.out.println("the manufracturer of shoe is "+shoe10.manufracturer);
		shoe10.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe10.quantity+" pair");

		Shoe shoe11=new Shoe();
		shoe11.brand="Liberty";
		System.out.println("The brand of a shoe is "+shoe11.brand);
		shoe11.cost=1899;
		System.out.println("The cost of the shoe is "+shoe11.cost);
		shoe11.weight=430;
		System.out.println("The weight of a shoe is "+shoe11.weight);
		shoe11.material="Leather";
		System.out.println("The shoe material is "+shoe11.material);
		shoe11.type="Formal";
		System.out.println("The type of a shoe is "+shoe11.type);
		shoe11.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe11.countryOfOrigin);
		shoe11.manufracturer="Liberty Shoes";
		System.out.println("the manufracturer of shoe is "+shoe11.manufracturer);
		shoe11.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe11.quantity+" pair");
		
		Shoe shoe12=new Shoe();
		shoe12.brand="RedTape";
		System.out.println("The brand of a shoe is "+shoe12.brand);
		shoe12.cost=3299;
		System.out.println("The cost of the shoe is "+shoe12.cost);
		shoe12.weight=460;
		System.out.println("The weight of a shoe is "+shoe12.weight);
		shoe12.material="Leather";
		System.out.println("The shoe material is "+shoe12.material);
		shoe12.type="Boots";
		System.out.println("The type of a shoe is "+shoe12.type);
		shoe12.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe12.countryOfOrigin);
		shoe12.manufracturer="RedTape Ltd";
		System.out.println("the manufracturer of shoe is "+shoe12.manufracturer);
		shoe12.quantity=2;System.out.println("The quantity of a shoe is "+shoe12.quantity+" pair");
		
		Shoe shoe13=new Shoe();
		shoe13.brand="Asics";
		System.out.println("The brand of a shoe is "+shoe13.brand);
		shoe13.cost=5599;
		System.out.println("The cost of the shoe is "+shoe13.cost);
		shoe13.weight=370;
		System.out.println("The weight of a shoe is "+shoe13.weight);
		shoe13.material="Synthetic";
		System.out.println("The shoe material is "+shoe13.material);
		shoe13.type="Running";
		System.out.println("The type of a shoe is "+shoe13.type);
		shoe13.countryOfOrigin="Japan";
		System.out.println("The shoe is manufactured in "+shoe13.countryOfOrigin);
		shoe13.manufracturer="Asics Corp";
		System.out.println("the manufracturer of shoe is "+shoe13.manufracturer);
		shoe13.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe13.quantity+" pair");
		
		
		Shoe shoe14=new Shoe();
		shoe14.brand="NewBalance";
		System.out.println("The brand of a shoe is "+shoe14.brand);
		shoe14.cost=4899;
		System.out.println("The cost of the shoe is "+shoe14.cost);
		shoe14.weight=390;
		System.out.println("The weight of a shoe is "+shoe14.weight);
		shoe14.material="Mesh";
		System.out.println("The shoe material is "+shoe14.material);
		shoe14.type="Sports";
		System.out.println("The type of a shoe is "+shoe14.type);
		shoe14.countryOfOrigin="USA";
		System.out.println("The shoe is manufactured in "+shoe14.countryOfOrigin);
		shoe14.manufracturer="NB Ltd";
		System.out.println("the manufracturer of shoe is "+shoe14.manufracturer);
		shoe14.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe14.quantity+" pair");
		
		
		Shoe shoe15=new Shoe();
		shoe15.brand="Skechers";
		System.out.println("The brand of a shoe is "+shoe15.brand);
		shoe15.cost=3799;
		System.out.println("The cost of the shoe is "+shoe15.cost);
		shoe15.weight=360;
		System.out.println("The weight of a shoe is "+shoe15.weight);
		shoe15.material="Foam";
		System.out.println("The shoe material is "+shoe15.material);
		shoe15.type="Casual";
		System.out.println("The type of a shoe is "+shoe15.type);
		shoe15.countryOfOrigin="USA";
		System.out.println("The shoe is manufactured in "+shoe15.countryOfOrigin);
		shoe15.manufracturer="Skechers Inc";
		System.out.println("the manufracturer of shoe is "+shoe15.manufracturer);
		shoe15.quantity=1;

		Shoe shoe16=new Shoe();
		shoe16.brand="HRX";
		System.out.println("The brand of a shoe is "+shoe16.brand);
		shoe16.cost=2299;
		System.out.println("The cost of the shoe is "+shoe16.cost);
		shoe16.weight=350;
		System.out.println("The weight of a shoe is "+shoe16.weight);
		shoe16.material="Mesh";
		System.out.println("The shoe material is "+shoe16.material);
		shoe16.type="Sports";
		System.out.println("The type of a shoe is "+shoe16.type);
		shoe16.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe16.countryOfOrigin);
		shoe16.manufracturer="HRX Brand";
		System.out.println("the manufracturer of shoe is "+shoe16.manufracturer);
		shoe16.quantity=2;System.out.println("The quantity of a shoe is "+shoe16.quantity+" pair");
		
		Shoe shoe17=new Shoe();
		shoe17.brand="LeeCooper";
		System.out.println("The brand of a shoe is "+shoe17.brand);
		shoe17.cost=2799;
		System.out.println("The cost of the shoe is "+shoe17.cost);
		shoe17.weight=420;
		System.out.println("The weight of a shoe is "+shoe17.weight);
		shoe17.material="Leather";
		System.out.println("The shoe material is "+shoe17.material);
		shoe17.type="Casual";
		System.out.println("The type of a shoe is "+shoe17.type);
		shoe17.countryOfOrigin="UK";
		System.out.println("The shoe is manufactured in "+shoe17.countryOfOrigin);
		shoe17.manufracturer="Lee Cooper";
		System.out.println("the manufracturer of shoe is "+shoe17.manufracturer);
		shoe17.quantity=1;System.out.println("The quantity of a shoe is "+shoe17.quantity+" pair");
		
		Shoe shoe18=new Shoe();
		shoe18.brand="HushPuppies";
		System.out.println("The brand of a shoe is "+shoe18.brand);
		shoe18.cost=3999;
		System.out.println("The cost of the shoe is "+shoe18.cost);
		shoe18.weight=440;
		System.out.println("The weight of a shoe is "+shoe18.weight);
		shoe18.material="Leather";
		System.out.println("The shoe material is "+shoe18.material);
		shoe18.type="Formal";
		System.out.println("The type of a shoe is "+shoe18.type);
		shoe18.countryOfOrigin="USA";
		System.out.println("The shoe is manufactured in "+shoe18.countryOfOrigin);
		shoe18.manufracturer="Hush Puppies";
		System.out.println("the manufracturer of shoe is "+shoe18.manufracturer);
		shoe18.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe18.quantity+" pair");
		
		
		
				Shoe shoe19=new Shoe();
		shoe19.brand="Clarks";
		System.out.println("The brand of a shoe is "+shoe19.brand);
		shoe19.cost=5999;
		System.out.println("The cost of the shoe is "+shoe19.cost);
		shoe19.weight=450;
		System.out.println("The weight of a shoe is "+shoe19.weight);
		shoe19.material="Leather";
		System.out.println("The shoe material is "+shoe19.material);
		shoe19.type="Formal";
		System.out.println("The type of a shoe is "+shoe19.type);
		shoe19.countryOfOrigin="UK";
		System.out.println("The shoe is manufactured in "+shoe19.countryOfOrigin);
		shoe19.manufracturer="Clarks Ltd";
		System.out.println("the manufracturer of shoe is "+shoe19.manufracturer);
		shoe19.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe19.quantity+" pair");

		Shoe shoe20=new Shoe();
		shoe20.brand="Metro";
		System.out.println("The brand of a shoe is "+shoe20.brand);
		shoe20.cost=2599;
		System.out.println("The cost of the shoe is "+shoe20.cost);
		shoe20.weight=430;
		System.out.println("The weight of a shoe is "+shoe20.weight);
		shoe20.material="Synthetic";
		System.out.println("The shoe material is "+shoe20.material);
		shoe20.type="Formal";
		System.out.println("The type of a shoe is "+shoe20.type);
		shoe20.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe20.countryOfOrigin);
		shoe20.manufracturer="Metro Shoes";
		System.out.println("the manufracturer of shoe is "+shoe20.manufracturer);
		shoe20.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe20.quantity+" pair");

		Shoe shoe21=new Shoe();
		shoe21.brand="AllenSolly";
		System.out.println("The brand of a shoe is "+shoe21.brand);
		shoe21.cost=3499;
		System.out.println("The cost of the shoe is "+shoe21.cost);
		shoe21.weight=410;
		System.out.println("The weight of a shoe is "+shoe21.weight);
		shoe21.material="Leather";
		System.out.println("The shoe material is "+shoe21.material);
		shoe21.type="Formal";
		System.out.println("The type of a shoe is "+shoe21.type);
		shoe21.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe21.countryOfOrigin);
		shoe21.manufracturer="Allen Solly";
		System.out.println("the manufracturer of shoe is "+shoe21.manufracturer);
		shoe21.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe21.quantity+" pair");

		Shoe shoe22=new Shoe();
		shoe22.brand="Paragon";
		System.out.println("The brand of a shoe is "+shoe22.brand);
		shoe22.cost=999;
		System.out.println("The cost of the shoe is "+shoe22.cost);
		shoe22.weight=300;
		System.out.println("The weight of a shoe is "+shoe22.weight);
		shoe22.material="Rubber";
		System.out.println("The shoe material is "+shoe22.material);
		shoe22.type="Slippers";
		System.out.println("The type of a shoe is "+shoe22.type);
		shoe22.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe22.countryOfOrigin);
		shoe22.manufracturer="Paragon";
		System.out.println("the manufracturer of shoe is "+shoe22.manufracturer);
		shoe22.quantity=3;
		System.out.println("The quantity of a shoe is "+shoe22.quantity+" pair");

		Shoe shoe23=new Shoe();
		shoe23.brand="Relaxo";
		System.out.println("The brand of a shoe is "+shoe23.brand);
		shoe23.cost=899;
		System.out.println("The cost of the shoe is "+shoe23.cost);
		shoe23.weight=280;
		System.out.println("The weight of a shoe is "+shoe23.weight);
		shoe23.material="Rubber";
		System.out.println("The shoe material is "+shoe23.material);
		shoe23.type="Slippers";
		System.out.println("The type of a shoe is "+shoe23.type);
		shoe23.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe23.countryOfOrigin);
		shoe23.manufracturer="Relaxo Ltd";
		System.out.println("the manufracturer of shoe is "+shoe23.manufracturer);
		shoe23.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe23.quantity+" pair");

		Shoe shoe24=new Shoe();
		shoe24.brand="Action";
		System.out.println("The brand of a shoe is "+shoe24.brand);
		shoe24.cost=1199;
		System.out.println("The cost of the shoe is "+shoe24.cost);
		shoe24.weight=330;
		System.out.println("The weight of a shoe is "+shoe24.weight);
		shoe24.material="Synthetic";
		System.out.println("The shoe material is "+shoe24.material);
		shoe24.type="Casual";
		System.out.println("The type of a shoe is "+shoe24.type);
		shoe24.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe24.countryOfOrigin);
		shoe24.manufracturer="Action Shoes";
		System.out.println("the manufracturer of shoe is "+shoe24.manufracturer);
		shoe24.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe24.quantity+" pair");

		Shoe shoe25=new Shoe();
		shoe25.brand="Power";
		System.out.println("The brand of a shoe is "+shoe25.brand);
		shoe25.cost=1599;
		System.out.println("The cost of the shoe is "+shoe25.cost);
		shoe25.weight=360;
		System.out.println("The weight of a shoe is "+shoe25.weight);
		shoe25.material="Mesh";
		System.out.println("The shoe material is "+shoe25.material);
		shoe25.type="Sports";
		System.out.println("The type of a shoe is "+shoe25.type);
		shoe25.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe25.countryOfOrigin);
		shoe25.manufracturer="Power Shoes";
		System.out.println("the manufracturer of shoe is "+shoe25.manufracturer);
		shoe25.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe25.quantity+" pair");

		Shoe shoe26=new Shoe();
		shoe26.brand="Khadims";
		System.out.println("The brand of a shoe is "+shoe26.brand);
		shoe26.cost=1399;
		System.out.println("The cost of the shoe is "+shoe26.cost);
		shoe26.weight=350;
		System.out.println("The weight of a shoe is "+shoe26.weight);
		shoe26.material="Synthetic";
		System.out.println("The shoe material is "+shoe26.material);
		shoe26.type="Casual";
		System.out.println("The type of a shoe is "+shoe26.type);
		shoe26.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe26.countryOfOrigin);
		shoe26.manufracturer="Khadims";
		System.out.println("the manufracturer of shoe is "+shoe26.manufracturer);
		shoe26.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe26.quantity+" pair");

		Shoe shoe27=new Shoe();
		shoe27.brand="Mochi";
		System.out.println("The brand of a shoe is "+shoe27.brand);
		shoe27.cost=2499;
		System.out.println("The cost of the shoe is "+shoe27.cost);
		shoe27.weight=420;
		System.out.println("The weight of a shoe is "+shoe27.weight);
		shoe27.material="Leather";
		System.out.println("The shoe material is "+shoe27.material);
		shoe27.type="Formal";
		System.out.println("The type of a shoe is "+shoe27.type);
		shoe27.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe27.countryOfOrigin);
		shoe27.manufracturer="Mochi Shoes";
		System.out.println("the manufracturer of shoe is "+shoe27.manufracturer);
		shoe27.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe27.quantity+" pair");

		Shoe shoe28=new Shoe();
		shoe28.brand="Inc5";
		System.out.println("The brand of a shoe is "+shoe28.brand);
		shoe28.cost=1999;
		System.out.println("The cost of the shoe is "+shoe28.cost);
		shoe28.weight=390;
		System.out.println("The weight of a shoe is "+shoe28.weight);
		shoe28.material="Synthetic";
		System.out.println("The shoe material is "+shoe28.material);
		shoe28.type="Casual";
		System.out.println("The type of a shoe is "+shoe28.type);
		shoe28.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe28.countryOfOrigin);
		shoe28.manufracturer="Inc5";
		System.out.println("the manufracturer of shoe is "+shoe28.manufracturer);
		shoe28.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe28.quantity+" pair");

		Shoe shoe29=new Shoe();
		shoe29.brand="Lavie";
		System.out.println("The brand of a shoe is "+shoe29.brand);
		shoe29.cost=1799;
		System.out.println("The cost of the shoe is "+shoe29.cost);
		shoe29.weight=370;
		System.out.println("The weight of a shoe is "+shoe29.weight);
		shoe29.material="Synthetic";
		System.out.println("The shoe material is "+shoe29.material);
		shoe29.type="Casual";
		System.out.println("The type of a shoe is "+shoe29.type);
		shoe29.countryOfOrigin="India";
		System.out.println("The shoe is manufactured in "+shoe29.countryOfOrigin);
		shoe29.manufracturer="Lavie";
		System.out.println("the manufracturer of shoe is "+shoe29.manufracturer);
		shoe29.quantity=2;
		System.out.println("The quantity of a shoe is "+shoe29.quantity+" pair");

		Shoe shoe30=new Shoe();
		shoe30.brand="Gucci";
		System.out.println("The brand of a shoe is "+shoe30.brand);
		shoe30.cost=15999;
		System.out.println("The cost of the shoe is "+shoe30.cost);
		shoe30.weight=450;
		System.out.println("The weight of a shoe is "+shoe30.weight);
		shoe30.material="PremiumLeather";
		System.out.println("The shoe material is "+shoe30.material);
		shoe30.type="Luxury";
		System.out.println("The type of a shoe is "+shoe30.type);
		shoe30.countryOfOrigin="Italy";
		System.out.println("The shoe is manufactured in "+shoe30.countryOfOrigin);
		shoe30.manufracturer="Gucci";
		System.out.println("the manufracturer of shoe is "+shoe30.manufracturer);
		shoe30.quantity=1;
		System.out.println("The quantity of a shoe is "+shoe30.quantity+" pair");
	}
}

	