class StudyTableExec
{
	public static void main(String[] args)
	{
		StudyTable s1 = new StudyTable();
		s1.brand="Nilkamal";
		System.out.println("The brand is "+s1.brand);
		s1.cost=5000;
		System.out.println("The cost is "+s1.cost);
		s1.material="Wood";
		System.out.println("The material is "+s1.material);
		s1.colour="Brown";
		System.out.println("The colour is "+s1.colour);
		s1.type="Study";
		System.out.println("The type is "+s1.type);
		s1.numberOfDrawers=2;
		System.out.println("Drawers: "+s1.numberOfDrawers);
		s1.isFoldable=false;
		System.out.println("Foldable: "+s1.isFoldable);
		s1.size="Medium";
		System.out.println("The size is "+s1.size);

		StudyTable s2 = new StudyTable();
		s2.brand="Godrej";
		System.out.println("The brand is "+s2.brand);
		s2.cost=7000;
		System.out.println("The cost is "+s2.cost);
		s2.material="Wood";
		System.out.println("The material is "+s2.material);
		s2.colour="Black";
		System.out.println("The colour is "+s2.colour);
		s2.type="Computer";
		System.out.println("The type is "+s2.type);
		s2.numberOfDrawers=3;
		System.out.println("Drawers: "+s2.numberOfDrawers);
		s2.isFoldable=false;
		System.out.println("Foldable: "+s2.isFoldable);
		s2.size="Large";
		System.out.println("The size is "+s2.size);

		StudyTable s3 = new StudyTable();
		s3.brand="Ikea";
		System.out.println("The brand is "+s3.brand);
		s3.cost=6000;
		System.out.println("The cost is "+s3.cost);
		s3.material="Engineered Wood";
		System.out.println("The material is "+s3.material);
		s3.colour="White";
		System.out.println("The colour is "+s3.colour);
		s3.type="Writing";
		System.out.println("The type is "+s3.type);
		s3.numberOfDrawers=1;
		System.out.println("Drawers: "+s3.numberOfDrawers);
		s3.isFoldable=true;
		System.out.println("Foldable: "+s3.isFoldable);
		s3.size="Medium";
		System.out.println("The size is "+s3.size);

		StudyTable s4 = new StudyTable();
		s4.brand="Urban Ladder";
		System.out.println("The brand is "+s4.brand);
		s4.cost=8000;
		System.out.println("The cost is "+s4.cost);
		s4.material="Wood";
		System.out.println("The material is "+s4.material);
		s4.colour="Brown";
		System.out.println("The colour is "+s4.colour);
		s4.type="Study";
		System.out.println("The type is "+s4.type);
		s4.numberOfDrawers=2;
		System.out.println("Drawers: "+s4.numberOfDrawers);
		s4.isFoldable=false;
		System.out.println("Foldable: "+s4.isFoldable);
		s4.size="Large";
		System.out.println("The size is "+s4.size);

		StudyTable s5 = new StudyTable();
		s5.brand="HomeTown";
		System.out.println("The brand is "+s5.brand);
		s5.cost=5500;
		System.out.println("The cost is "+s5.cost);
		s5.material="Plastic";
		System.out.println("The material is "+s5.material);
		s5.colour="Blue";
		System.out.println("The colour is "+s5.colour);
		s5.type="Study";
		System.out.println("The type is "+s5.type);
		s5.numberOfDrawers=1;
		System.out.println("Drawers: "+s5.numberOfDrawers);
		s5.isFoldable=true;
		System.out.println("Foldable: "+s5.isFoldable);
		s5.size="Small";
		System.out.println("The size is "+s5.size);

		StudyTable s6 = new StudyTable();
		s6.brand="Durian";
		System.out.println("The brand is "+s6.brand);
		s6.cost=9000;
		System.out.println("The cost is "+s6.cost);
		s6.material="Wood";
		System.out.println("The material is "+s6.material);
		s6.colour="Brown";
		System.out.println("The colour is "+s6.colour);
		s6.type="Computer";
		System.out.println("The type is "+s6.type);
		s6.numberOfDrawers=3;
		System.out.println("Drawers: "+s6.numberOfDrawers);
		s6.isFoldable=false;
		System.out.println("Foldable: "+s6.isFoldable);
		s6.size="Large";
		System.out.println("The size is "+s6.size);

		StudyTable s7 = new StudyTable();
		s7.brand="Pepperfry";
		System.out.println("The brand is "+s7.brand);
		s7.cost=6500;
		System.out.println("The cost is "+s7.cost);
		s7.material="Engineered Wood";
		System.out.println("The material is "+s7.material);
		s7.colour="White";
		System.out.println("The colour is "+s7.colour);
		s7.type="Writing";
		System.out.println("The type is "+s7.type);
		s7.numberOfDrawers=2;
		System.out.println("Drawers: "+s7.numberOfDrawers);
		s7.isFoldable=true;
		System.out.println("Foldable: "+s7.isFoldable);
		s7.size="Medium";
		System.out.println("The size is "+s7.size);

		StudyTable s8 = new StudyTable();
		s8.brand="Cello";
		System.out.println("The brand is "+s8.brand);
		s8.cost=4000;
		System.out.println("The cost is "+s8.cost);
		s8.material="Plastic";
		System.out.println("The material is "+s8.material);
		s8.colour="Red";
		System.out.println("The colour is "+s8.colour);
		s8.type="Study";
		System.out.println("The type is "+s8.type);
		s8.numberOfDrawers=1;
		System.out.println("Drawers: "+s8.numberOfDrawers);
		s8.isFoldable=true;
		System.out.println("Foldable: "+s8.isFoldable);
		s8.size="Small";
		System.out.println("The size is "+s8.size);

		StudyTable s9 = new StudyTable();
		s9.brand="Nilkamal Pro";
		System.out.println("The brand is "+s9.brand);
		s9.cost=7500;
		System.out.println("The cost is "+s9.cost);
		s9.material="Wood";
		System.out.println("The material is "+s9.material);
		s9.colour="Black";
		System.out.println("The colour is "+s9.colour);
		s9.type="Computer";
		System.out.println("The type is "+s9.type);
		s9.numberOfDrawers=2;
		System.out.println("Drawers: "+s9.numberOfDrawers);
		s9.isFoldable=false;
		System.out.println("Foldable: "+s9.isFoldable);
		s9.size="Large";
		System.out.println("The size is "+s9.size);

		StudyTable s10 = new StudyTable();
		s10.brand="Urban Desk";
		System.out.println("The brand is "+s10.brand);
		s10.cost=6800;
		System.out.println("The cost is "+s10.cost);
		s10.material="Engineered Wood";
		System.out.println("The material is "+s10.material);
		s10.colour="Brown";
		System.out.println("The colour is "+s10.colour);
		s10.type="Study";
		System.out.println("The type is "+s10.type);
		s10.numberOfDrawers=2;
		System.out.println("Drawers: "+s10.numberOfDrawers);
		s10.isFoldable=false;
		System.out.println("Foldable: "+s10.isFoldable);
		s10.size="Medium";
		System.out.println("The size is "+s10.size);
		
				StudyTable s11 = new StudyTable();
		s11.brand="Featherlite";
		System.out.println("The brand is "+s11.brand);
		s11.cost=8200;
		System.out.println("The cost is "+s11.cost);
		s11.material="Metal";
		System.out.println("The material is "+s11.material);
		s11.colour="Grey";
		System.out.println("The colour is "+s11.colour);
		s11.type="Computer";
		System.out.println("The type is "+s11.type);
		s11.numberOfDrawers=2;
		System.out.println("Drawers: "+s11.numberOfDrawers);
		s11.isFoldable=false;
		System.out.println("Foldable: "+s11.isFoldable);
		s11.size="Large";
		System.out.println("The size is "+s11.size);

		StudyTable s12 = new StudyTable();
		s12.brand="GreenSoul";
		System.out.println("The brand is "+s12.brand);
		s12.cost=9000;
		System.out.println("The cost is "+s12.cost);
		s12.material="Wood";
		System.out.println("The material is "+s12.material);
		s12.colour="Black";
		System.out.println("The colour is "+s12.colour);
		s12.type="Gaming";
		System.out.println("The type is "+s12.type);
		s12.numberOfDrawers=1;
		System.out.println("Drawers: "+s12.numberOfDrawers);
		s12.isFoldable=false;
		System.out.println("Foldable: "+s12.isFoldable);
		s12.size="Large";
		System.out.println("The size is "+s12.size);

		StudyTable s13 = new StudyTable();
		s13.brand="Amazon Basics";
		System.out.println("The brand is "+s13.brand);
		s13.cost=4500;
		System.out.println("The cost is "+s13.cost);
		s13.material="Engineered Wood";
		System.out.println("The material is "+s13.material);
		s13.colour="Brown";
		System.out.println("The colour is "+s13.colour);
		s13.type="Study";
		System.out.println("The type is "+s13.type);
		s13.numberOfDrawers=1;
		System.out.println("Drawers: "+s13.numberOfDrawers);
		s13.isFoldable=true;
		System.out.println("Foldable: "+s13.isFoldable);
		s13.size="Medium";
		System.out.println("The size is "+s13.size);

		StudyTable s14 = new StudyTable();
		s14.brand="Flipkart Perfect";
		System.out.println("The brand is "+s14.brand);
		s14.cost=4800;
		System.out.println("The cost is "+s14.cost);
		s14.material="Wood";
		System.out.println("The material is "+s14.material);
		s14.colour="White";
		System.out.println("The colour is "+s14.colour);
		s14.type="Study";
		System.out.println("The type is "+s14.type);
		s14.numberOfDrawers=2;
		System.out.println("Drawers: "+s14.numberOfDrawers);
		s14.isFoldable=true;
		System.out.println("Foldable: "+s14.isFoldable);
		s14.size="Medium";
		System.out.println("The size is "+s14.size);

		StudyTable s15 = new StudyTable();
		s15.brand="WoodLand";
		System.out.println("The brand is "+s15.brand);
		s15.cost=7500;
		System.out.println("The cost is "+s15.cost);
		s15.material="Wood";
		System.out.println("The material is "+s15.material);
		s15.colour="Brown";
		System.out.println("The colour is "+s15.colour);
		s15.type="Writing";
		System.out.println("The type is "+s15.type);
		s15.numberOfDrawers=2;
		System.out.println("Drawers: "+s15.numberOfDrawers);
		s15.isFoldable=false;
		System.out.println("Foldable: "+s15.isFoldable);
		s15.size="Large";
		System.out.println("The size is "+s15.size);

		StudyTable s16 = new StudyTable();
		s16.brand="Modern Home";
		System.out.println("The brand is "+s16.brand);
		s16.cost=6200;
		System.out.println("The cost is "+s16.cost);
		s16.material="Engineered Wood";
		System.out.println("The material is "+s16.material);
		s16.colour="Grey";
		System.out.println("The colour is "+s16.colour);
		s16.type="Study";
		System.out.println("The type is "+s16.type);
		s16.numberOfDrawers=1;
		System.out.println("Drawers: "+s16.numberOfDrawers);
		s16.isFoldable=true;
		System.out.println("Foldable: "+s16.isFoldable);
		s16.size="Medium";
		System.out.println("The size is "+s16.size);

		StudyTable s17 = new StudyTable();
		s17.brand="Classic Desk";
		System.out.println("The brand is "+s17.brand);
		s17.cost=8800;
		System.out.println("The cost is "+s17.cost);
		s17.material="Wood";
		System.out.println("The material is "+s17.material);
		s17.colour="Brown";
		System.out.println("The colour is "+s17.colour);
		s17.type="Study";
		System.out.println("The type is "+s17.type);
		s17.numberOfDrawers=3;
		System.out.println("Drawers: "+s17.numberOfDrawers);
		s17.isFoldable=false;
		System.out.println("Foldable: "+s17.isFoldable);
		s17.size="Large";
		System.out.println("The size is "+s17.size);

		StudyTable s18 = new StudyTable();
		s18.brand="Compact Table";
		System.out.println("The brand is "+s18.brand);
		s18.cost=3500;
		System.out.println("The cost is "+s18.cost);
		s18.material="Plastic";
		System.out.println("The material is "+s18.material);
		s18.colour="Blue";
		System.out.println("The colour is "+s18.colour);
		s18.type="Study";
		System.out.println("The type is "+s18.type);
		s18.numberOfDrawers=0;
		System.out.println("Drawers: "+s18.numberOfDrawers);
		s18.isFoldable=true;
		System.out.println("Foldable: "+s18.isFoldable);
		s18.size="Small";
		System.out.println("The size is "+s18.size);

		StudyTable s19 = new StudyTable();
		s19.brand="Office Mate";
		System.out.println("The brand is "+s19.brand);
		s19.cost=9200;
		System.out.println("The cost is "+s19.cost);
		s19.material="Metal";
		System.out.println("The material is "+s19.material);
		s19.colour="Black";
		System.out.println("The colour is "+s19.colour);
		s19.type="Office";
		System.out.println("The type is "+s19.type);
		s19.numberOfDrawers=2;
		System.out.println("Drawers: "+s19.numberOfDrawers);
		s19.isFoldable=false;
		System.out.println("Foldable: "+s19.isFoldable);
		s19.size="Large";
		System.out.println("The size is "+s19.size);

		StudyTable s20 = new StudyTable();
		s20.brand="Student Desk";
		System.out.println("The brand is "+s20.brand);
		s20.cost=3000;
		System.out.println("The cost is "+s20.cost);
		s20.material="Plastic";
		System.out.println("The material is "+s20.material);
		s20.colour="Pink";
		System.out.println("The colour is "+s20.colour);
		s20.type="Study";
		System.out.println("The type is "+s20.type);
		s20.numberOfDrawers=1;
		System.out.println("Drawers: "+s20.numberOfDrawers);
		s20.isFoldable=true;
		System.out.println("Foldable: "+s20.isFoldable);
		s20.size="Small";
		System.out.println("The size is "+s20.size);
		
				StudyTable s21 = new StudyTable();
		s21.brand="Elite Desk";
		System.out.println("The brand is "+s21.brand);
		s21.cost=10000;
		System.out.println("The cost is "+s21.cost);
		s21.material="Wood";
		System.out.println("The material is "+s21.material);
		s21.colour="Brown";
		System.out.println("The colour is "+s21.colour);
		s21.type="Office";
		System.out.println("The type is "+s21.type);
		s21.numberOfDrawers=3;
		System.out.println("Drawers: "+s21.numberOfDrawers);
		s21.isFoldable=false;
		System.out.println("Foldable: "+s21.isFoldable);
		s21.size="Large";
		System.out.println("The size is "+s21.size);

		StudyTable s22 = new StudyTable();
		s22.brand="Mini Desk";
		System.out.println("The brand is "+s22.brand);
		s22.cost=2500;
		System.out.println("The cost is "+s22.cost);
		s22.material="Plastic";
		System.out.println("The material is "+s22.material);
		s22.colour="Yellow";
		System.out.println("The colour is "+s22.colour);
		s22.type="Study";
		System.out.println("The type is "+s22.type);
		s22.numberOfDrawers=0;
		System.out.println("Drawers: "+s22.numberOfDrawers);
		s22.isFoldable=true;
		System.out.println("Foldable: "+s22.isFoldable);
		s22.size="Small";
		System.out.println("The size is "+s22.size);

		StudyTable s23 = new StudyTable();
		s23.brand="Luxury Desk";
		System.out.println("The brand is "+s23.brand);
		s23.cost=15000;
		System.out.println("The cost is "+s23.cost);
		s23.material="Wood";
		System.out.println("The material is "+s23.material);
		s23.colour="Black";
		System.out.println("The colour is "+s23.colour);
		s23.type="Office";
		System.out.println("The type is "+s23.type);
		s23.numberOfDrawers=4;
		System.out.println("Drawers: "+s23.numberOfDrawers);
		s23.isFoldable=false;
		System.out.println("Foldable: "+s23.isFoldable);
		s23.size="Large";
		System.out.println("The size is "+s23.size);

		StudyTable s24 = new StudyTable();
		s24.brand="Eco Desk";
		System.out.println("The brand is "+s24.brand);
		s24.cost=5500;
		System.out.println("The cost is "+s24.cost);
		s24.material="Bamboo";
		System.out.println("The material is "+s24.material);
		s24.colour="Light Brown";
		System.out.println("The colour is "+s24.colour);
		s24.type="Study";
		System.out.println("The type is "+s24.type);
		s24.numberOfDrawers=1;
		System.out.println("Drawers: "+s24.numberOfDrawers);
		s24.isFoldable=true;
		System.out.println("Foldable: "+s24.isFoldable);
		s24.size="Medium";
		System.out.println("The size is "+s24.size);

		StudyTable s25 = new StudyTable();
		s25.brand="Smart Desk";
		System.out.println("The brand is "+s25.brand);
		s25.cost=12000;
		System.out.println("The cost is "+s25.cost);
		s25.material="Wood";
		System.out.println("The material is "+s25.material);
		s25.colour="White";
		System.out.println("The colour is "+s25.colour);
		s25.type="Computer";
		System.out.println("The type is "+s25.type);
		s25.numberOfDrawers=2;
		System.out.println("Drawers: "+s25.numberOfDrawers);
		s25.isFoldable=false;
		System.out.println("Foldable: "+s25.isFoldable);
		s25.size="Large";
		System.out.println("The size is "+s25.size);

		StudyTable s26 = new StudyTable();
		s26.brand="Simple Desk";
		System.out.println("The brand is "+s26.brand);
		s26.cost=4000;
		System.out.println("The cost is "+s26.cost);
		s26.material="Plastic";
		System.out.println("The material is "+s26.material);
		s26.colour="Blue";
		System.out.println("The colour is "+s26.colour);
		s26.type="Study";
		System.out.println("The type is "+s26.type);
		s26.numberOfDrawers=1;
		System.out.println("Drawers: "+s26.numberOfDrawers);
		s26.isFoldable=true;
		System.out.println("Foldable: "+s26.isFoldable);
		s26.size="Small";
		System.out.println("The size is "+s26.size);

		StudyTable s27 = new StudyTable();
		s27.brand="Classic Wood";
		System.out.println("The brand is "+s27.brand);
		s27.cost=9500;
		System.out.println("The cost is "+s27.cost);
		s27.material="Wood";
		System.out.println("The material is "+s27.material);
		s27.colour="Dark Brown";
		System.out.println("The colour is "+s27.colour);
		s27.type="Office";
		System.out.println("The type is "+s27.type);
		s27.numberOfDrawers=3;
		System.out.println("Drawers: "+s27.numberOfDrawers);
		s27.isFoldable=false;
		System.out.println("Foldable: "+s27.isFoldable);
		s27.size="Large";
		System.out.println("The size is "+s27.size);

		StudyTable s28 = new StudyTable();
		s28.brand="Fold Desk";
		System.out.println("The brand is "+s28.brand);
		s28.cost=3000;
		System.out.println("The cost is "+s28.cost);
		s28.material="Metal";
		System.out.println("The material is "+s28.material);
		s28.colour="Grey";
		System.out.println("The colour is "+s28.colour);
		s28.type="Study";
		System.out.println("The type is "+s28.type);
		s28.numberOfDrawers=0;
		System.out.println("Drawers: "+s28.numberOfDrawers);
		s28.isFoldable=true;
		System.out.println("Foldable: "+s28.isFoldable);
		s28.size="Small";
		System.out.println("The size is "+s28.size);

		StudyTable s29 = new StudyTable();
		s29.brand="Office Pro";
		System.out.println("The brand is "+s29.brand);
		s29.cost=11000;
		System.out.println("The cost is "+s29.cost);
		s29.material="Wood";
		System.out.println("The material is "+s29.material);
		s29.colour="Black";
		System.out.println("The colour is "+s29.colour);
		s29.type="Office";
		System.out.println("The type is "+s29.type);
		s29.numberOfDrawers=3;
		System.out.println("Drawers: "+s29.numberOfDrawers);
		s29.isFoldable=false;
		System.out.println("Foldable: "+s29.isFoldable);
		s29.size="Large";
		System.out.println("The size is "+s29.size);

		StudyTable s30 = new StudyTable();
		s30.brand="Student Pro";
		System.out.println("The brand is "+s30.brand);
		s30.cost=3500;
		System.out.println("The cost is "+s30.cost);
		s30.material="Plastic";
		System.out.println("The material is "+s30.material);
		s30.colour="Green";
		System.out.println("The colour is "+s30.colour);
		s30.type="Study";
		System.out.println("The type is "+s30.type);
		s30.numberOfDrawers=1;
		System.out.println("Drawers: "+s30.numberOfDrawers);
		s30.isFoldable=true;
		System.out.println("Foldable: "+s30.isFoldable);
		s30.size="Small";
		System.out.println("The size is "+s30.size);
	}
}