class SunscreenExec
{
	public static void main(String[] args)
	{
		Sunscreen s1 = new Sunscreen();
		s1.brand="Lakme";
		System.out.println("The brand is "+s1.brand);
		s1.spf=30;
		System.out.println("SPF is "+s1.spf);
		s1.price=250;
		System.out.println("Price is "+s1.price);
		s1.type="Cream";
		System.out.println("Type is "+s1.type);
		s1.skinType="Normal";
		System.out.println("Skin type "+s1.skinType);
		s1.isWaterResistant=true;
		System.out.println("Water resistant "+s1.isWaterResistant);
		s1.expiryDate="12/2026";
		System.out.println("Expiry "+s1.expiryDate);
		s1.quantity="100ml";
		System.out.println("Quantity "+s1.quantity);

		Sunscreen s2 = new Sunscreen();
		s2.brand="Nivea";
		System.out.println("The brand is "+s2.brand);
		s2.spf=50;
		System.out.println("SPF is "+s2.spf);
		s2.price=350;
		System.out.println("Price is "+s2.price);
		s2.type="Lotion";
		System.out.println("Type is "+s2.type);
		s2.skinType="Dry";
		System.out.println("Skin type "+s2.skinType);
		s2.isWaterResistant=true;
		System.out.println("Water resistant "+s2.isWaterResistant);
		s2.expiryDate="11/2026";
		System.out.println("Expiry "+s2.expiryDate);
		s2.quantity="120ml";
		System.out.println("Quantity "+s2.quantity);

		Sunscreen s3 = new Sunscreen();
		s3.brand="Lotus";
		System.out.println("The brand is "+s3.brand);
		s3.spf=40;
		System.out.println("SPF is "+s3.spf);
		s3.price=300;
		System.out.println("Price is "+s3.price);
		s3.type="Gel";
		System.out.println("Type is "+s3.type);
		s3.skinType="Oily";
		System.out.println("Skin type "+s3.skinType);
		s3.isWaterResistant=false;
		System.out.println("Water resistant "+s3.isWaterResistant);
		s3.expiryDate="10/2026";
		System.out.println("Expiry "+s3.expiryDate);
		s3.quantity="100ml";
		System.out.println("Quantity "+s3.quantity);

		Sunscreen s4 = new Sunscreen();
		s4.brand="Neutrogena";
		System.out.println("The brand is "+s4.brand);
		s4.spf=50;
		System.out.println("SPF is "+s4.spf);
		s4.price=450;
		System.out.println("Price is "+s4.price);
		s4.type="Cream";
		System.out.println("Type is "+s4.type);
		s4.skinType="Sensitive";
		System.out.println("Skin type "+s4.skinType);
		s4.isWaterResistant=true;
		System.out.println("Water resistant "+s4.isWaterResistant);
		s4.expiryDate="09/2026";
		System.out.println("Expiry "+s4.expiryDate);
		s4.quantity="80ml";
		System.out.println("Quantity "+s4.quantity);

		Sunscreen s5 = new Sunscreen();
		s5.brand="Biotique";
		System.out.println("The brand is "+s5.brand);
		s5.spf=30;
		System.out.println("SPF is "+s5.spf);
		s5.price=200;
		System.out.println("Price is "+s5.price);
		s5.type="Lotion";
		System.out.println("Type is "+s5.type);
		s5.skinType="All";
		System.out.println("Skin type "+s5.skinType);
		s5.isWaterResistant=false;
		System.out.println("Water resistant "+s5.isWaterResistant);
		s5.expiryDate="12/2025";
		System.out.println("Expiry "+s5.expiryDate);
		s5.quantity="100ml";
		System.out.println("Quantity "+s5.quantity);

		Sunscreen s6 = new Sunscreen();
		s6.brand="Himalaya";
		System.out.println("The brand is "+s6.brand);
		s6.spf=25;
		System.out.println("SPF is "+s6.spf);
		s6.price=180;
		System.out.println("Price is "+s6.price);
		s6.type="Cream";
		System.out.println("Type is "+s6.type);
		s6.skinType="Normal";
		System.out.println("Skin type "+s6.skinType);
		s6.isWaterResistant=false;
		System.out.println("Water resistant "+s6.isWaterResistant);
		s6.expiryDate="08/2026";
		System.out.println("Expiry "+s6.expiryDate);
		s6.quantity="75ml";
		System.out.println("Quantity "+s6.quantity);

		Sunscreen s7 = new Sunscreen();
		s7.brand="Mamaearth";
		System.out.println("The brand is "+s7.brand);
		s7.spf=50;
		System.out.println("SPF is "+s7.spf);
		s7.price=399;
		System.out.println("Price is "+s7.price);
		s7.type="Gel";
		System.out.println("Type is "+s7.type);
		s7.skinType="Oily";
		System.out.println("Skin type "+s7.skinType);
		s7.isWaterResistant=true;
		System.out.println("Water resistant "+s7.isWaterResistant);
		s7.expiryDate="07/2026";
		System.out.println("Expiry "+s7.expiryDate);
		s7.quantity="100ml";
		System.out.println("Quantity "+s7.quantity);

		Sunscreen s8 = new Sunscreen();
		s8.brand="VLCC";
		System.out.println("The brand is "+s8.brand);
		s8.spf=40;
		System.out.println("SPF is "+s8.spf);
		s8.price=270;
		System.out.println("Price is "+s8.price);
		s8.type="Cream";
		System.out.println("Type is "+s8.type);
		s8.skinType="Dry";
		System.out.println("Skin type "+s8.skinType);
		s8.isWaterResistant=true;
		System.out.println("Water resistant "+s8.isWaterResistant);
		s8.expiryDate="11/2025";
		System.out.println("Expiry "+s8.expiryDate);
		s8.quantity="100ml";
		System.out.println("Quantity "+s8.quantity);

		Sunscreen s9 = new Sunscreen();
		s9.brand="WOW";
		System.out.println("The brand is "+s9.brand);
		s9.spf=30;
		System.out.println("SPF is "+s9.spf);
		s9.price=320;
		System.out.println("Price is "+s9.price);
		s9.type="Lotion";
		System.out.println("Type is "+s9.type);
		s9.skinType="Normal";
		System.out.println("Skin type "+s9.skinType);
		s9.isWaterResistant=false;
		System.out.println("Water resistant "+s9.isWaterResistant);
		s9.expiryDate="10/2026";
		System.out.println("Expiry "+s9.expiryDate);
		s9.quantity="120ml";
		System.out.println("Quantity "+s9.quantity);

		Sunscreen s10 = new Sunscreen();
		s10.brand="Ponds";
		System.out.println("The brand is "+s10.brand);
		s10.spf=35;
		System.out.println("SPF is "+s10.spf);
		s10.price=260;
		System.out.println("Price is "+s10.price);
		s10.type="Cream";
		System.out.println("Type is "+s10.type);
		s10.skinType="All";
		System.out.println("Skin type "+s10.skinType);
		s10.isWaterResistant=true;
		System.out.println("Water resistant "+s10.isWaterResistant);
		s10.expiryDate="12/2026";
		System.out.println("Expiry "+s10.expiryDate);
		s10.quantity="100ml";
		System.out.println("Quantity "+s10.quantity);
		
				Sunscreen s11 = new Sunscreen();
		s11.brand="LactoCalamine";
		System.out.println("The brand is "+s11.brand);
		s11.spf=50;
		System.out.println("SPF is "+s11.spf);
		s11.price=350;
		System.out.println("Price is "+s11.price);
		s11.type="Lotion";
		System.out.println("Type is "+s11.type);
		s11.skinType="Oily";
		System.out.println("Skin type "+s11.skinType);
		s11.isWaterResistant=true;
		System.out.println("Water resistant "+s11.isWaterResistant);
		s11.expiryDate="09/2026";
		System.out.println("Expiry "+s11.expiryDate);
		s11.quantity="120ml";
		System.out.println("Quantity "+s11.quantity);

		Sunscreen s12 = new Sunscreen();
		s12.brand="AromaMagic";
		System.out.println("The brand is "+s12.brand);
		s12.spf=30;
		System.out.println("SPF is "+s12.spf);
		s12.price=280;
		System.out.println("Price is "+s12.price);
		s12.type="Cream";
		System.out.println("Type is "+s12.type);
		s12.skinType="Sensitive";
		System.out.println("Skin type "+s12.skinType);
		s12.isWaterResistant=false;
		System.out.println("Water resistant "+s12.isWaterResistant);
		s12.expiryDate="08/2025";
		System.out.println("Expiry "+s12.expiryDate);
		s12.quantity="100ml";
		System.out.println("Quantity "+s12.quantity);

		Sunscreen s13 = new Sunscreen();
		s13.brand="Reequil";
		System.out.println("The brand is "+s13.brand);
		s13.spf=50;
		System.out.println("SPF is "+s13.spf);
		s13.price=450;
		System.out.println("Price is "+s13.price);
		s13.type="Gel";
		System.out.println("Type is "+s13.type);
		s13.skinType="Oily";
		System.out.println("Skin type "+s13.skinType);
		s13.isWaterResistant=true;
		System.out.println("Water resistant "+s13.isWaterResistant);
		s13.expiryDate="07/2026";
		System.out.println("Expiry "+s13.expiryDate);
		s13.quantity="50ml";
		System.out.println("Quantity "+s13.quantity);

		Sunscreen s14 = new Sunscreen();
		s14.brand="Minimalist";
		System.out.println("The brand is "+s14.brand);
		s14.spf=60;
		System.out.println("SPF is "+s14.spf);
		s14.price=499;
		System.out.println("Price is "+s14.price);
		s14.type="Serum";
		System.out.println("Type is "+s14.type);
		s14.skinType="All";
		System.out.println("Skin type "+s14.skinType);
		s14.isWaterResistant=true;
		System.out.println("Water resistant "+s14.isWaterResistant);
		s14.expiryDate="12/2026";
		System.out.println("Expiry "+s14.expiryDate);
		s14.quantity="50ml";
		System.out.println("Quantity "+s14.quantity);

		Sunscreen s15 = new Sunscreen();
		s15.brand="DermaCo";
		System.out.println("The brand is "+s15.brand);
		s15.spf=50;
		System.out.println("SPF is "+s15.spf);
		s15.price=420;
		System.out.println("Price is "+s15.price);
		s15.type="Gel";
		System.out.println("Type is "+s15.type);
		s15.skinType="Sensitive";
		System.out.println("Skin type "+s15.skinType);
		s15.isWaterResistant=true;
		System.out.println("Water resistant "+s15.isWaterResistant);
		s15.expiryDate="11/2026";
		System.out.println("Expiry "+s15.expiryDate);
		s15.quantity="80ml";
		System.out.println("Quantity "+s15.quantity);

		Sunscreen s16 = new Sunscreen();
		s16.brand="Cetaphil";
		System.out.println("The brand is "+s16.brand);
		s16.spf=50;
		System.out.println("SPF is "+s16.spf);
		s16.price=550;
		System.out.println("Price is "+s16.price);
		s16.type="Lotion";
		System.out.println("Type is "+s16.type);
		s16.skinType="Dry";
		System.out.println("Skin type "+s16.skinType);
		s16.isWaterResistant=true;
		System.out.println("Water resistant "+s16.isWaterResistant);
		s16.expiryDate="10/2026";
		System.out.println("Expiry "+s16.expiryDate);
		s16.quantity="100ml";
		System.out.println("Quantity "+s16.quantity);

		Sunscreen s17 = new Sunscreen();
		s17.brand="Fixderma";
		System.out.println("The brand is "+s17.brand);
		s17.spf=30;
		System.out.println("SPF is "+s17.spf);
		s17.price=350;
		System.out.println("Price is "+s17.price);
		s17.type="Cream";
		System.out.println("Type is "+s17.type);
		s17.skinType="All";
		System.out.println("Skin type "+s17.skinType);
		s17.isWaterResistant=false;
		System.out.println("Water resistant "+s17.isWaterResistant);
		s17.expiryDate="09/2025";
		System.out.println("Expiry "+s17.expiryDate);
		s17.quantity="75ml";
		System.out.println("Quantity "+s17.quantity);

		Sunscreen s18 = new Sunscreen();
		s18.brand="Plum";
		System.out.println("The brand is "+s18.brand);
		s18.spf=35;
		System.out.println("SPF is "+s18.spf);
		s18.price=399;
		System.out.println("Price is "+s18.price);
		s18.type="Gel";
		System.out.println("Type is "+s18.type);
		s18.skinType="Oily";
		System.out.println("Skin type "+s18.skinType);
		s18.isWaterResistant=true;
		System.out.println("Water resistant "+s18.isWaterResistant);
		s18.expiryDate="08/2026";
		System.out.println("Expiry "+s18.expiryDate);
		s18.quantity="100ml";
		System.out.println("Quantity "+s18.quantity);

		Sunscreen s19 = new Sunscreen();
		s19.brand="Lotus Herbals";
		System.out.println("The brand is "+s19.brand);
		s19.spf=50;
		System.out.println("SPF is "+s19.spf);
		s19.price=420;
		System.out.println("Price is "+s19.price);
		s19.type="Cream";
		System.out.println("Type is "+s19.type);
		s19.skinType="Normal";
		System.out.println("Skin type "+s19.skinType);
		s19.isWaterResistant=true;
		System.out.println("Water resistant "+s19.isWaterResistant);
		s19.expiryDate="07/2026";
		System.out.println("Expiry "+s19.expiryDate);
		s19.quantity="120ml";
		System.out.println("Quantity "+s19.quantity);

		Sunscreen s20 = new Sunscreen();
		s20.brand="BananaBoat";
		System.out.println("The brand is "+s20.brand);
		s20.spf=60;
		System.out.println("SPF is "+s20.spf);
		s20.price=650;
		System.out.println("Price is "+s20.price);
		s20.type="Spray";
		System.out.println("Type is "+s20.type);
		s20.skinType="All";
		System.out.println("Skin type "+s20.skinType);
		s20.isWaterResistant=true;
		System.out.println("Water resistant "+s20.isWaterResistant);
		s20.expiryDate="12/2026";
		System.out.println("Expiry "+s20.expiryDate);
		s20.quantity="150ml";
		System.out.println("Quantity "+s20.quantity);
		
				Sunscreen s21 = new Sunscreen();
		s21.brand="Neutrogena Ultra";
		System.out.println("The brand is "+s21.brand);
		s21.spf=70;
		System.out.println("SPF is "+s21.spf);
		s21.price=700;
		System.out.println("Price is "+s21.price);
		s21.type="Cream";
		System.out.println("Type is "+s21.type);
		s21.skinType="Sensitive";
		System.out.println("Skin type "+s21.skinType);
		s21.isWaterResistant=true;
		System.out.println("Water resistant "+s21.isWaterResistant);
		s21.expiryDate="11/2026";
		System.out.println("Expiry "+s21.expiryDate);
		s21.quantity="100ml";
		System.out.println("Quantity "+s21.quantity);

		Sunscreen s22 = new Sunscreen();
		s22.brand="VLCC Matte";
		System.out.println("The brand is "+s22.brand);
		s22.spf=40;
		System.out.println("SPF is "+s22.spf);
		s22.price=300;
		System.out.println("Price is "+s22.price);
		s22.type="Gel";
		System.out.println("Type is "+s22.type);
		s22.skinType="Oily";
		System.out.println("Skin type "+s22.skinType);
		s22.isWaterResistant=false;
		System.out.println("Water resistant "+s22.isWaterResistant);
		s22.expiryDate="10/2025";
		System.out.println("Expiry "+s22.expiryDate);
		s22.quantity="80ml";
		System.out.println("Quantity "+s22.quantity);

		Sunscreen s23 = new Sunscreen();
		s23.brand="Himalaya Safe";
		System.out.println("The brand is "+s23.brand);
		s23.spf=25;
		System.out.println("SPF is "+s23.spf);
		s23.price=200;
		System.out.println("Price is "+s23.price);
		s23.type="Lotion";
		System.out.println("Type is "+s23.type);
		s23.skinType="Normal";
		System.out.println("Skin type "+s23.skinType);
		s23.isWaterResistant=false;
		System.out.println("Water resistant "+s23.isWaterResistant);
		s23.expiryDate="09/2026";
		System.out.println("Expiry "+s23.expiryDate);
		s23.quantity="100ml";
		System.out.println("Quantity "+s23.quantity);

		Sunscreen s24 = new Sunscreen();
		s24.brand="Mamaearth Aqua";
		System.out.println("The brand is "+s24.brand);
		s24.spf=50;
		System.out.println("SPF is "+s24.spf);
		s24.price=399;
		System.out.println("Price is "+s24.price);
		s24.type="Gel";
		System.out.println("Type is "+s24.type);
		s24.skinType="Oily";
		System.out.println("Skin type "+s24.skinType);
		s24.isWaterResistant=true;
		System.out.println("Water resistant "+s24.isWaterResistant);
		s24.expiryDate="08/2026";
		System.out.println("Expiry "+s24.expiryDate);
		s24.quantity="100ml";
		System.out.println("Quantity "+s24.quantity);

		Sunscreen s25 = new Sunscreen();
		s25.brand="WOW Skin";
		System.out.println("The brand is "+s25.brand);
		s25.spf=30;
		System.out.println("SPF is "+s25.spf);
		s25.price=320;
		System.out.println("Price is "+s25.price);
		s25.type="Cream";
		System.out.println("Type is "+s25.type);
		s25.skinType="All";
		System.out.println("Skin type "+s25.skinType);
		s25.isWaterResistant=false;
		System.out.println("Water resistant "+s25.isWaterResistant);
		s25.expiryDate="07/2025";
		System.out.println("Expiry "+s25.expiryDate);
		s25.quantity="120ml";
		System.out.println("Quantity "+s25.quantity);

		Sunscreen s26 = new Sunscreen();
		s26.brand="Ponds Sun";
		System.out.println("The brand is "+s26.brand);
		s26.spf=35;
		System.out.println("SPF is "+s26.spf);
		s26.price=280;
		System.out.println("Price is "+s26.price);
		s26.type="Cream";
		System.out.println("Type is "+s26.type);
		s26.skinType="Normal";
		System.out.println("Skin type "+s26.skinType);
		s26.isWaterResistant=true;
		System.out.println("Water resistant "+s26.isWaterResistant);
		s26.expiryDate="12/2026";
		System.out.println("Expiry "+s26.expiryDate);
		s26.quantity="100ml";
		System.out.println("Quantity "+s26.quantity);

		Sunscreen s27 = new Sunscreen();
		s27.brand="Plum Green";
		System.out.println("The brand is "+s27.brand);
		s27.spf=50;
		System.out.println("SPF is "+s27.spf);
		s27.price=450;
		System.out.println("Price is "+s27.price);
		s27.type="Gel";
		System.out.println("Type is "+s27.type);
		s27.skinType="Sensitive";
		System.out.println("Skin type "+s27.skinType);
		s27.isWaterResistant=true;
		System.out.println("Water resistant "+s27.isWaterResistant);
		s27.expiryDate="11/2026";
		System.out.println("Expiry "+s27.expiryDate);
		s27.quantity="80ml";
		System.out.println("Quantity "+s27.quantity);

		Sunscreen s28 = new Sunscreen();
		s28.brand="Derma Safe";
		System.out.println("The brand is "+s28.brand);
		s28.spf=60;
		System.out.println("SPF is "+s28.spf);
		s28.price=520;
		System.out.println("Price is "+s28.price);
		s28.type="Lotion";
		System.out.println("Type is "+s28.type);
		s28.skinType="All";
		System.out.println("Skin type "+s28.skinType);
		s28.isWaterResistant=true;
		System.out.println("Water resistant "+s28.isWaterResistant);
		s28.expiryDate="10/2026";
		System.out.println("Expiry "+s28.expiryDate);
		s28.quantity="150ml";
		System.out.println("Quantity "+s28.quantity);

		Sunscreen s29 = new Sunscreen();
		s29.brand="Cetaphil Sun";
		System.out.println("The brand is "+s29.brand);
		s29.spf=50;
		System.out.println("SPF is "+s29.spf);
		s29.price=600;
		System.out.println("Price is "+s29.price);
		s29.type="Cream";
		System.out.println("Type is "+s29.type);
		s29.skinType="Dry";
		System.out.println("Skin type "+s29.skinType);
		s29.isWaterResistant=true;
		System.out.println("Water resistant "+s29.isWaterResistant);
		s29.expiryDate="09/2026";
		System.out.println("Expiry "+s29.expiryDate);
		s29.quantity="100ml";
		System.out.println("Quantity "+s29.quantity);

		Sunscreen s30 = new Sunscreen();
		s30.brand="Minimalist SPF";
		System.out.println("The brand is "+s30.brand);
		s30.spf=70;
		System.out.println("SPF is "+s30.spf);
		s30.price=550;
		System.out.println("Price is "+s30.price);
		s30.type="Serum";
		System.out.println("Type is "+s30.type);
		s30.skinType="All";
		System.out.println("Skin type "+s30.skinType);
		s30.isWaterResistant=true;
		System.out.println("Water resistant "+s30.isWaterResistant);
		s30.expiryDate="12/2026";
		System.out.println("Expiry "+s30.expiryDate);
		s30.quantity="50ml";
		System.out.println("Quantity "+s30.quantity);
	}
}