class SwitchBoxExec
{
	public static void main(String[] args)
	{
		SwitchBox s1 = new SwitchBox();
		s1.brand="Anchor";
		System.out.println("The brand is "+s1.brand);
		s1.cost=250;
		System.out.println("The cost is "+s1.cost);
		s1.numberOfSwitches=4;
		System.out.println("Number of switches "+s1.numberOfSwitches);
		s1.material="Plastic";
		System.out.println("Material is "+s1.material);
		s1.colour="White";
		System.out.println("Colour is "+s1.colour);
		s1.hasIndicator=true;
		System.out.println("Has indicator "+s1.hasIndicator);
		s1.type="Modular";
		System.out.println("Type is "+s1.type);
		s1.mountingType="Wall";
		System.out.println("Mounting type "+s1.mountingType);

		SwitchBox s2 = new SwitchBox();
		s2.brand="Havells";
		System.out.println("The brand is "+s2.brand);
		s2.cost=300;
		System.out.println("The cost is "+s2.cost);
		s2.numberOfSwitches=6;
		System.out.println("Number of switches "+s2.numberOfSwitches);
		s2.material="Plastic";
		System.out.println("Material is "+s2.material);
		s2.colour="White";
		System.out.println("Colour is "+s2.colour);
		s2.hasIndicator=true;
		System.out.println("Has indicator "+s2.hasIndicator);
		s2.type="Modular";
		System.out.println("Type is "+s2.type);
		s2.mountingType="Wall";
		System.out.println("Mounting type "+s2.mountingType);

		SwitchBox s3 = new SwitchBox();
		s3.brand="Legrand";
		System.out.println("The brand is "+s3.brand);
		s3.cost=450;
		System.out.println("The cost is "+s3.cost);
		s3.numberOfSwitches=8;
		System.out.println("Number of switches "+s3.numberOfSwitches);
		s3.material="Plastic";
		System.out.println("Material is "+s3.material);
		s3.colour="Grey";
		System.out.println("Colour is "+s3.colour);
		s3.hasIndicator=true;
		System.out.println("Has indicator "+s3.hasIndicator);
		s3.type="Modular";
		System.out.println("Type is "+s3.type);
		s3.mountingType="Wall";
		System.out.println("Mounting type "+s3.mountingType);

		SwitchBox s4 = new SwitchBox();
		s4.brand="GM";
		System.out.println("The brand is "+s4.brand);
		s4.cost=200;
		System.out.println("The cost is "+s4.cost);
		s4.numberOfSwitches=3;
		System.out.println("Number of switches "+s4.numberOfSwitches);
		s4.material="Plastic";
		System.out.println("Material is "+s4.material);
		s4.colour="White";
		System.out.println("Colour is "+s4.colour);
		s4.hasIndicator=false;
		System.out.println("Has indicator "+s4.hasIndicator);
		s4.type="Traditional";
		System.out.println("Type is "+s4.type);
		s4.mountingType="Surface";
		System.out.println("Mounting type "+s4.mountingType);

		SwitchBox s5 = new SwitchBox();
		s5.brand="Syska";
		System.out.println("The brand is "+s5.brand);
		s5.cost=350;
		System.out.println("The cost is "+s5.cost);
		s5.numberOfSwitches=5;
		System.out.println("Number of switches "+s5.numberOfSwitches);
		s5.material="Plastic";
		System.out.println("Material is "+s5.material);
		s5.colour="Black";
		System.out.println("Colour is "+s5.colour);
		s5.hasIndicator=true;
		System.out.println("Has indicator "+s5.hasIndicator);
		s5.type="Modular";
		System.out.println("Type is "+s5.type);
		s5.mountingType="Wall";
		System.out.println("Mounting type "+s5.mountingType);

		SwitchBox s6 = new SwitchBox();
		s6.brand="Orient";
		System.out.println("The brand is "+s6.brand);
		s6.cost=280;
		System.out.println("The cost is "+s6.cost);
		s6.numberOfSwitches=4;
		System.out.println("Number of switches "+s6.numberOfSwitches);
		s6.material="Plastic";
		System.out.println("Material is "+s6.material);
		s6.colour="White";
		System.out.println("Colour is "+s6.colour);
		s6.hasIndicator=false;
		System.out.println("Has indicator "+s6.hasIndicator);
		s6.type="Traditional";
		System.out.println("Type is "+s6.type);
		s6.mountingType="Surface";
		System.out.println("Mounting type "+s6.mountingType);

		SwitchBox s7 = new SwitchBox();
		s7.brand="Philips";
		System.out.println("The brand is "+s7.brand);
		s7.cost=500;
		System.out.println("The cost is "+s7.cost);
		s7.numberOfSwitches=7;
		System.out.println("Number of switches "+s7.numberOfSwitches);
		s7.material="Metal";
		System.out.println("Material is "+s7.material);
		s7.colour="Silver";
		System.out.println("Colour is "+s7.colour);
		s7.hasIndicator=true;
		System.out.println("Has indicator "+s7.hasIndicator);
		s7.type="Modular";
		System.out.println("Type is "+s7.type);
		s7.mountingType="Wall";
		System.out.println("Mounting type "+s7.mountingType);

		SwitchBox s8 = new SwitchBox();
		s8.brand="Bajaj";
		System.out.println("The brand is "+s8.brand);
		s8.cost=220;
		System.out.println("The cost is "+s8.cost);
		s8.numberOfSwitches=3;
		System.out.println("Number of switches "+s8.numberOfSwitches);
		s8.material="Plastic";
		System.out.println("Material is "+s8.material);
		s8.colour="White";
		System.out.println("Colour is "+s8.colour);
		s8.hasIndicator=false;
		System.out.println("Has indicator "+s8.hasIndicator);
		s8.type="Traditional";
		System.out.println("Type is "+s8.type);
		s8.mountingType="Surface";
		System.out.println("Mounting type "+s8.mountingType);

		SwitchBox s9 = new SwitchBox();
		s9.brand="Panasonic";
		System.out.println("The brand is "+s9.brand);
		s9.cost=400;
		System.out.println("The cost is "+s9.cost);
		s9.numberOfSwitches=6;
		System.out.println("Number of switches "+s9.numberOfSwitches);
		s9.material="Plastic";
		System.out.println("Material is "+s9.material);
		s9.colour="Grey";
		System.out.println("Colour is "+s9.colour);
		s9.hasIndicator=true;
		System.out.println("Has indicator "+s9.hasIndicator);
		s9.type="Modular";
		System.out.println("Type is "+s9.type);
		s9.mountingType="Wall";
		System.out.println("Mounting type "+s9.mountingType);

		SwitchBox s10 = new SwitchBox();
		s10.brand="Crompton";
		System.out.println("The brand is "+s10.brand);
		s10.cost=260;
		System.out.println("The cost is "+s10.cost);
		s10.numberOfSwitches=4;
		System.out.println("Number of switches "+s10.numberOfSwitches);
		s10.material="Plastic";
		System.out.println("Material is "+s10.material);
		s10.colour="White";
		System.out.println("Colour is "+s10.colour);
		s10.hasIndicator=true;
		System.out.println("Has indicator "+s10.hasIndicator);
		s10.type="Modular";
		System.out.println("Type is "+s10.type);
		s10.mountingType="Wall";
		System.out.println("Mounting type "+s10.mountingType);
		
		
				SwitchBox s11 = new SwitchBox();
		s11.brand="V-Guard";
		System.out.println("The brand is "+s11.brand);
		s11.cost=300;
		System.out.println("The cost is "+s11.cost);
		s11.numberOfSwitches=5;
		System.out.println("Number of switches "+s11.numberOfSwitches);
		s11.material="Plastic";
		System.out.println("Material is "+s11.material);
		s11.colour="White";
		System.out.println("Colour is "+s11.colour);
		s11.hasIndicator=true;
		System.out.println("Has indicator "+s11.hasIndicator);
		s11.type="Modular";
		System.out.println("Type is "+s11.type);
		s11.mountingType="Wall";
		System.out.println("Mounting type "+s11.mountingType);

		SwitchBox s12 = new SwitchBox();
		s12.brand="Goldmedal";
		System.out.println("The brand is "+s12.brand);
		s12.cost=450;
		System.out.println("The cost is "+s12.cost);
		s12.numberOfSwitches=8;
		System.out.println("Number of switches "+s12.numberOfSwitches);
		s12.material="Plastic";
		System.out.println("Material is "+s12.material);
		s12.colour="Black";
		System.out.println("Colour is "+s12.colour);
		s12.hasIndicator=true;
		System.out.println("Has indicator "+s12.hasIndicator);
		s12.type="Modular";
		System.out.println("Type is "+s12.type);
		s12.mountingType="Wall";
		System.out.println("Mounting type "+s12.mountingType);

		SwitchBox s13 = new SwitchBox();
		s13.brand="Anchor Roma";
		System.out.println("The brand is "+s13.brand);
		s13.cost=350;
		System.out.println("The cost is "+s13.cost);
		s13.numberOfSwitches=6;
		System.out.println("Number of switches "+s13.numberOfSwitches);
		s13.material="Plastic";
		System.out.println("Material is "+s13.material);
		s13.colour="Grey";
		System.out.println("Colour is "+s13.colour);
		s13.hasIndicator=true;
		System.out.println("Has indicator "+s13.hasIndicator);
		s13.type="Modular";
		System.out.println("Type is "+s13.type);
		s13.mountingType="Wall";
		System.out.println("Mounting type "+s13.mountingType);

		SwitchBox s14 = new SwitchBox();
		s14.brand="GreatWhite";
		System.out.println("The brand is "+s14.brand);
		s14.cost=420;
		System.out.println("The cost is "+s14.cost);
		s14.numberOfSwitches=7;
		System.out.println("Number of switches "+s14.numberOfSwitches);
		s14.material="Plastic";
		System.out.println("Material is "+s14.material);
		s14.colour="White";
		System.out.println("Colour is "+s14.colour);
		s14.hasIndicator=true;
		System.out.println("Has indicator "+s14.hasIndicator);
		s14.type="Modular";
		System.out.println("Type is "+s14.type);
		s14.mountingType="Wall";
		System.out.println("Mounting type "+s14.mountingType);

		SwitchBox s15 = new SwitchBox();
		s15.brand="Crabtree";
		System.out.println("The brand is "+s15.brand);
		s15.cost=500;
		System.out.println("The cost is "+s15.cost);
		s15.numberOfSwitches=8;
		System.out.println("Number of switches "+s15.numberOfSwitches);
		s15.material="Metal";
		System.out.println("Material is "+s15.material);
		s15.colour="Silver";
		System.out.println("Colour is "+s15.colour);
		s15.hasIndicator=true;
		System.out.println("Has indicator "+s15.hasIndicator);
		s15.type="Modular";
		System.out.println("Type is "+s15.type);
		s15.mountingType="Wall";
		System.out.println("Mounting type "+s15.mountingType);

		SwitchBox s16 = new SwitchBox();
		s16.brand="Polycab";
		System.out.println("The brand is "+s16.brand);
		s16.cost=380;
		System.out.println("The cost is "+s16.cost);
		s16.numberOfSwitches=6;
		System.out.println("Number of switches "+s16.numberOfSwitches);
		s16.material="Plastic";
		System.out.println("Material is "+s16.material);
		s16.colour="White";
		System.out.println("Colour is "+s16.colour);
		s16.hasIndicator=true;
		System.out.println("Has indicator "+s16.hasIndicator);
		s16.type="Modular";
		System.out.println("Type is "+s16.type);
		s16.mountingType="Wall";
		System.out.println("Mounting type "+s16.mountingType);

		SwitchBox s17 = new SwitchBox();
		s17.brand="Wipro";
		System.out.println("The brand is "+s17.brand);
		s17.cost=360;
		System.out.println("The cost is "+s17.cost);
		s17.numberOfSwitches=5;
		System.out.println("Number of switches "+s17.numberOfSwitches);
		s17.material="Plastic";
		System.out.println("Material is "+s17.material);
		s17.colour="White";
		System.out.println("Colour is "+s17.colour);
		s17.hasIndicator=false;
		System.out.println("Has indicator "+s17.hasIndicator);
		s17.type="Traditional";
		System.out.println("Type is "+s17.type);
		s17.mountingType="Surface";
		System.out.println("Mounting type "+s17.mountingType);

		SwitchBox s18 = new SwitchBox();
		s18.brand="Eveready";
		System.out.println("The brand is "+s18.brand);
		s18.cost=250;
		System.out.println("The cost is "+s18.cost);
		s18.numberOfSwitches=4;
		System.out.println("Number of switches "+s18.numberOfSwitches);
		s18.material="Plastic";
		System.out.println("Material is "+s18.material);
		s18.colour="White";
		System.out.println("Colour is "+s18.colour);
		s18.hasIndicator=false;
		System.out.println("Has indicator "+s18.hasIndicator);
		s18.type="Traditional";
		System.out.println("Type is "+s18.type);
		s18.mountingType="Surface";
		System.out.println("Mounting type "+s18.mountingType);

		SwitchBox s19 = new SwitchBox();
		s19.brand="Orient Electric";
		System.out.println("The brand is "+s19.brand);
		s19.cost=300;
		System.out.println("The cost is "+s19.cost);
		s19.numberOfSwitches=5;
		System.out.println("Number of switches "+s19.numberOfSwitches);
		s19.material="Plastic";
		System.out.println("Material is "+s19.material);
		s19.colour="Grey";
		System.out.println("Colour is "+s19.colour);
		s19.hasIndicator=true;
		System.out.println("Has indicator "+s19.hasIndicator);
		s19.type="Modular";
		System.out.println("Type is "+s19.type);
		s19.mountingType="Wall";
		System.out.println("Mounting type "+s19.mountingType);

		SwitchBox s20 = new SwitchBox();
		s20.brand="Finolex";
		System.out.println("The brand is "+s20.brand);
		s20.cost=320;
		System.out.println("The cost is "+s20.cost);
		s20.numberOfSwitches=6;
		System.out.println("Number of switches "+s20.numberOfSwitches);
		s20.material="Plastic";
		System.out.println("Material is "+s20.material);
		s20.colour="White";
		System.out.println("Colour is "+s20.colour);
		s20.hasIndicator=true;
		System.out.println("Has indicator "+s20.hasIndicator);
		s20.type="Modular";
		System.out.println("Type is "+s20.type);
		s20.mountingType="Wall";
		System.out.println("Mounting type "+s20.mountingType);
		
				SwitchBox s21 = new SwitchBox();
		s21.brand="Local Brand";
		System.out.println("The brand is "+s21.brand);
		s21.cost=150;
		System.out.println("The cost is "+s21.cost);
		s21.numberOfSwitches=3;
		System.out.println("Number of switches "+s21.numberOfSwitches);
		s21.material="Plastic";
		System.out.println("Material is "+s21.material);
		s21.colour="White";
		System.out.println("Colour is "+s21.colour);
		s21.hasIndicator=false;
		System.out.println("Has indicator "+s21.hasIndicator);
		s21.type="Traditional";
		System.out.println("Type is "+s21.type);
		s21.mountingType="Surface";
		System.out.println("Mounting type "+s21.mountingType);

		SwitchBox s22 = new SwitchBox();
		s22.brand="Super Switch";
		System.out.println("The brand is "+s22.brand);
		s22.cost=270;
		System.out.println("The cost is "+s22.cost);
		s22.numberOfSwitches=4;
		System.out.println("Number of switches "+s22.numberOfSwitches);
		s22.material="Plastic";
		System.out.println("Material is "+s22.material);
		s22.colour="Grey";
		System.out.println("Colour is "+s22.colour);
		s22.hasIndicator=true;
		System.out.println("Has indicator "+s22.hasIndicator);
		s22.type="Modular";
		System.out.println("Type is "+s22.type);
		s22.mountingType="Wall";
		System.out.println("Mounting type "+s22.mountingType);

		SwitchBox s23 = new SwitchBox();
		s23.brand="Smart Switch";
		System.out.println("The brand is "+s23.brand);
		s23.cost=600;
		System.out.println("The cost is "+s23.cost);
		s23.numberOfSwitches=8;
		System.out.println("Number of switches "+s23.numberOfSwitches);
		s23.material="Metal";
		System.out.println("Material is "+s23.material);
		s23.colour="Black";
		System.out.println("Colour is "+s23.colour);
		s23.hasIndicator=true;
		System.out.println("Has indicator "+s23.hasIndicator);
		s23.type="Smart";
		System.out.println("Type is "+s23.type);
		s23.mountingType="Wall";
		System.out.println("Mounting type "+s23.mountingType);

		SwitchBox s24 = new SwitchBox();
		s24.brand="Eco Switch";
		System.out.println("The brand is "+s24.brand);
		s24.cost=230;
		System.out.println("The cost is "+s24.cost);
		s24.numberOfSwitches=4;
		System.out.println("Number of switches "+s24.numberOfSwitches);
		s24.material="Plastic";
		System.out.println("Material is "+s24.material);
		s24.colour="White";
		System.out.println("Colour is "+s24.colour);
		s24.hasIndicator=false;
		System.out.println("Has indicator "+s24.hasIndicator);
		s24.type="Traditional";
		System.out.println("Type is "+s24.type);
		s24.mountingType="Surface";
		System.out.println("Mounting type "+s24.mountingType);

		SwitchBox s25 = new SwitchBox();
		s25.brand="Ultra Switch";
		System.out.println("The brand is "+s25.brand);
		s25.cost=450;
		System.out.println("The cost is "+s25.cost);
		s25.numberOfSwitches=7;
		System.out.println("Number of switches "+s25.numberOfSwitches);
		s25.material="Plastic";
		System.out.println("Material is "+s25.material);
		s25.colour="Grey";
		System.out.println("Colour is "+s25.colour);
		s25.hasIndicator=true;
		System.out.println("Has indicator "+s25.hasIndicator);
		s25.type="Modular";
		System.out.println("Type is "+s25.type);
		s25.mountingType="Wall";
		System.out.println("Mounting type "+s25.mountingType);

		SwitchBox s26 = new SwitchBox();
		s26.brand="Prime Switch";
		System.out.println("The brand is "+s26.brand);
		s26.cost=380;
		System.out.println("The cost is "+s26.cost);
		s26.numberOfSwitches=6;
		System.out.println("Number of switches "+s26.numberOfSwitches);
		s26.material="Plastic";
		System.out.println("Material is "+s26.material);
		s26.colour="White";
		System.out.println("Colour is "+s26.colour);
		s26.hasIndicator=true;
		System.out.println("Has indicator "+s26.hasIndicator);
		s26.type="Modular";
		System.out.println("Type is "+s26.type);
		s26.mountingType="Wall";
		System.out.println("Mounting type "+s26.mountingType);

		SwitchBox s27 = new SwitchBox();
		s27.brand="Classic Switch";
		System.out.println("The brand is "+s27.brand);
		s27.cost=200;
		System.out.println("The cost is "+s27.cost);
		s27.numberOfSwitches=3;
		System.out.println("Number of switches "+s27.numberOfSwitches);
		s27.material="Plastic";
		System.out.println("Material is "+s27.material);
		s27.colour="White";
		System.out.println("Colour is "+s27.colour);
		s27.hasIndicator=false;
		System.out.println("Has indicator "+s27.hasIndicator);
		s27.type="Traditional";
		System.out.println("Type is "+s27.type);
		s27.mountingType="Surface";
		System.out.println("Mounting type "+s27.mountingType);

		SwitchBox s28 = new SwitchBox();
		s28.brand="Modern Switch";
		System.out.println("The brand is "+s28.brand);
		s28.cost=420;
		System.out.println("The cost is "+s28.cost);
		s28.numberOfSwitches=7;
		System.out.println("Number of switches "+s28.numberOfSwitches);
		s28.material="Metal";
		System.out.println("Material is "+s28.material);
		s28.colour="Black";
		System.out.println("Colour is "+s28.colour);
		s28.hasIndicator=true;
		System.out.println("Has indicator "+s28.hasIndicator);
		s28.type="Smart";
		System.out.println("Type is "+s28.type);
		s28.mountingType="Wall";
		System.out.println("Mounting type "+s28.mountingType);

		SwitchBox s29 = new SwitchBox();
		s29.brand="Basic Switch";
		System.out.println("The brand is "+s29.brand);
		s29.cost=180;
		System.out.println("The cost is "+s29.cost);
		s29.numberOfSwitches=3;
		System.out.println("Number of switches "+s29.numberOfSwitches);
		s29.material="Plastic";
		System.out.println("Material is "+s29.material);
		s29.colour="White";
		System.out.println("Colour is "+s29.colour);
		s29.hasIndicator=false;
		System.out.println("Has indicator "+s29.hasIndicator);
		s29.type="Traditional";
		System.out.println("Type is "+s29.type);
		s29.mountingType="Surface";
		System.out.println("Mounting type "+s29.mountingType);

		SwitchBox s30 = new SwitchBox();
		s30.brand="Premium Switch";
		System.out.println("The brand is "+s30.brand);
		s30.cost=550;
		System.out.println("The cost is "+s30.cost);
		s30.numberOfSwitches=8;
		System.out.println("Number of switches "+s30.numberOfSwitches);
		s30.material="Metal";
		System.out.println("Material is "+s30.material);
		s30.colour="Silver";
		System.out.println("Colour is "+s30.colour);
		s30.hasIndicator=true;
		System.out.println("Has indicator "+s30.hasIndicator);
		s30.type="Smart";
		System.out.println("Type is "+s30.type);
		s30.mountingType="Wall";
		System.out.println("Mounting type "+s30.mountingType);
	}
}