class TrolleyBagExec
{
	public static void main(String[] args)
	{
		TrolleyBag t1 = new TrolleyBag();
		t1.brand="Skybags";
		System.out.println("The brand is "+t1.brand);
		t1.cost=3500;
		System.out.println("The cost is "+t1.cost);
		t1.colour="Black";
		System.out.println("The colour is "+t1.colour);
		t1.material="Polycarbonate";
		System.out.println("The material is "+t1.material);
		t1.size="Large";
		System.out.println("The size is "+t1.size);
		t1.wheels=4;
		System.out.println("The wheels are "+t1.wheels);
		t1.weight=3.5;
		System.out.println("The weight is "+t1.weight);
		t1.hasLock=true;
		System.out.println("Lock available: "+t1.hasLock);

		TrolleyBag t2 = new TrolleyBag();
		t2.brand="VIP";
		System.out.println("The brand is "+t2.brand);
		t2.cost=4000;
		System.out.println("The cost is "+t2.cost);
		t2.colour="Blue";
		System.out.println("The colour is "+t2.colour);
		t2.material="Plastic";
		System.out.println("The material is "+t2.material);
		t2.size="Medium";
		System.out.println("The size is "+t2.size);
		t2.wheels=4;
		System.out.println("The wheels are "+t2.wheels);
		t2.weight=3.0;
		System.out.println("The weight is "+t2.weight);
		t2.hasLock=true;
		System.out.println("Lock available: "+t2.hasLock);

		TrolleyBag t3 = new TrolleyBag();
		t3.brand="American Tourister";
		System.out.println("The brand is "+t3.brand);
		t3.cost=5000;
		System.out.println("The cost is "+t3.cost);
		t3.colour="Red";
		System.out.println("The colour is "+t3.colour);
		t3.material="Polycarbonate";
		System.out.println("The material is "+t3.material);
		t3.size="Large";
		System.out.println("The size is "+t3.size);
		t3.wheels=4;
		System.out.println("The wheels are "+t3.wheels);
		t3.weight=3.8;
		System.out.println("The weight is "+t3.weight);
		t3.hasLock=true;
		System.out.println("Lock available: "+t3.hasLock);

		TrolleyBag t4 = new TrolleyBag();
		t4.brand="Safari";
		System.out.println("The brand is "+t4.brand);
		t4.cost=3200;
		System.out.println("The cost is "+t4.cost);
		t4.colour="Grey";
		System.out.println("The colour is "+t4.colour);
		t4.material="Fabric";
		System.out.println("The material is "+t4.material);
		t4.size="Medium";
		System.out.println("The size is "+t4.size);
		t4.wheels=2;
		System.out.println("The wheels are "+t4.wheels);
		t4.weight=2.8;
		System.out.println("The weight is "+t4.weight);
		t4.hasLock=false;
		System.out.println("Lock available: "+t4.hasLock);

		TrolleyBag t5 = new TrolleyBag();
		t5.brand="Aristocrat";
		System.out.println("The brand is "+t5.brand);
		t5.cost=2800;
		System.out.println("The cost is "+t5.cost);
		t5.colour="Black";
		System.out.println("The colour is "+t5.colour);
		t5.material="Plastic";
		System.out.println("The material is "+t5.material);
		t5.size="Small";
		System.out.println("The size is "+t5.size);
		t5.wheels=2;
		System.out.println("The wheels are "+t5.wheels);
		t5.weight=2.5;
		System.out.println("The weight is "+t5.weight);
		t5.hasLock=false;
		System.out.println("Lock available: "+t5.hasLock);

		TrolleyBag t6 = new TrolleyBag();
		t6.brand="Wildcraft";
		System.out.println("The brand is "+t6.brand);
		t6.cost=3600;
		System.out.println("The cost is "+t6.cost);
		t6.colour="Green";
		System.out.println("The colour is "+t6.colour);
		t6.material="Fabric";
		System.out.println("The material is "+t6.material);
		t6.size="Large";
		System.out.println("The size is "+t6.size);
		t6.wheels=4;
		System.out.println("The wheels are "+t6.wheels);
		t6.weight=3.2;
		System.out.println("The weight is "+t6.weight);
		t6.hasLock=true;
		System.out.println("Lock available: "+t6.hasLock);

		TrolleyBag t7 = new TrolleyBag();
		t7.brand="Samsonite";
		System.out.println("The brand is "+t7.brand);
		t7.cost=8000;
		System.out.println("The cost is "+t7.cost);
		t7.colour="Blue";
		System.out.println("The colour is "+t7.colour);
		t7.material="Polycarbonate";
		System.out.println("The material is "+t7.material);
		t7.size="Large";
		System.out.println("The size is "+t7.size);
		t7.wheels=4;
		System.out.println("The wheels are "+t7.wheels);
		t7.weight=4.0;
		System.out.println("The weight is "+t7.weight);
		t7.hasLock=true;
		System.out.println("Lock available: "+t7.hasLock);

		TrolleyBag t8 = new TrolleyBag();
		t8.brand="Delsey";
		System.out.println("The brand is "+t8.brand);
		t8.cost=7000;
		System.out.println("The cost is "+t8.cost);
		t8.colour="Silver";
		System.out.println("The colour is "+t8.colour);
		t8.material="Polycarbonate";
		System.out.println("The material is "+t8.material);
		t8.size="Medium";
		System.out.println("The size is "+t8.size);
		t8.wheels=4;
		System.out.println("The wheels are "+t8.wheels);
		t8.weight=3.6;
		System.out.println("The weight is "+t8.weight);
		t8.hasLock=true;
		System.out.println("Lock available: "+t8.hasLock);

		TrolleyBag t9 = new TrolleyBag();
		t9.brand="IT Luggage";
		System.out.println("The brand is "+t9.brand);
		t9.cost=4200;
		System.out.println("The cost is "+t9.cost);
		t9.colour="Purple";
		System.out.println("The colour is "+t9.colour);
		t9.material="Fabric";
		System.out.println("The material is "+t9.material);
		t9.size="Medium";
		System.out.println("The size is "+t9.size);
		t9.wheels=2;
		System.out.println("The wheels are "+t9.wheels);
		t9.weight=3.1;
		System.out.println("The weight is "+t9.weight);
		t9.hasLock=false;
		System.out.println("Lock available: "+t9.hasLock);

		TrolleyBag t10 = new TrolleyBag();
		t10.brand="Travelpro";
		System.out.println("The brand is "+t10.brand);
		t10.cost=6000;
		System.out.println("The cost is "+t10.cost);
		t10.colour="Black";
		System.out.println("The colour is "+t10.colour);
		t10.material="Fabric";
		System.out.println("The material is "+t10.material);
		t10.size="Large";
		System.out.println("The size is "+t10.size);
		t10.wheels=4;
		System.out.println("The wheels are "+t10.wheels);
		t10.weight=3.7;
		System.out.println("The weight is "+t10.weight);
		t10.hasLock=true;
		System.out.println("Lock available: "+t10.hasLock);
		
				TrolleyBag t11 = new TrolleyBag();
		t11.brand="Carlton";
		System.out.println("The brand is "+t11.brand);
		t11.cost=4500;
		System.out.println("The cost is "+t11.cost);
		t11.colour="Grey";
		System.out.println("The colour is "+t11.colour);
		t11.material="Polycarbonate";
		System.out.println("The material is "+t11.material);
		t11.size="Large";
		System.out.println("The size is "+t11.size);
		t11.wheels=4;
		System.out.println("The wheels are "+t11.wheels);
		t11.weight=3.9;
		System.out.println("The weight is "+t11.weight);
		t11.hasLock=true;
		System.out.println("Lock available: "+t11.hasLock);

		TrolleyBag t12 = new TrolleyBag();
		t12.brand="VIP Sky";
		System.out.println("The brand is "+t12.brand);
		t12.cost=4800;
		System.out.println("The cost is "+t12.cost);
		t12.colour="Blue";
		System.out.println("The colour is "+t12.colour);
		t12.material="Polycarbonate";
		System.out.println("The material is "+t12.material);
		t12.size="Large";
		System.out.println("The size is "+t12.size);
		t12.wheels=4;
		System.out.println("The wheels are "+t12.wheels);
		t12.weight=3.6;
		System.out.println("The weight is "+t12.weight);
		t12.hasLock=true;
		System.out.println("Lock available: "+t12.hasLock);

		TrolleyBag t13 = new TrolleyBag();
		t13.brand="Kamiliant";
		System.out.println("The brand is "+t13.brand);
		t13.cost=3500;
		System.out.println("The cost is "+t13.cost);
		t13.colour="Orange";
		System.out.println("The colour is "+t13.colour);
		t13.material="Plastic";
		System.out.println("The material is "+t13.material);
		t13.size="Medium";
		System.out.println("The size is "+t13.size);
		t13.wheels=4;
		System.out.println("The wheels are "+t13.wheels);
		t13.weight=3.3;
		System.out.println("The weight is "+t13.weight);
		t13.hasLock=true;
		System.out.println("Lock available: "+t13.hasLock);

		TrolleyBag t14 = new TrolleyBag();
		t14.brand="Nasher Miles";
		System.out.println("The brand is "+t14.brand);
		t14.cost=3000;
		System.out.println("The cost is "+t14.cost);
		t14.colour="Yellow";
		System.out.println("The colour is "+t14.colour);
		t14.material="Plastic";
		System.out.println("The material is "+t14.material);
		t14.size="Medium";
		System.out.println("The size is "+t14.size);
		t14.wheels=4;
		System.out.println("The wheels are "+t14.wheels);
		t14.weight=3.2;
		System.out.println("The weight is "+t14.weight);
		t14.hasLock=false;
		System.out.println("Lock available: "+t14.hasLock);

		TrolleyBag t15 = new TrolleyBag();
		t15.brand="Amazon Basics";
		System.out.println("The brand is "+t15.brand);
		t15.cost=2500;
		System.out.println("The cost is "+t15.cost);
		t15.colour="Black";
		System.out.println("The colour is "+t15.colour);
		t15.material="Fabric";
		System.out.println("The material is "+t15.material);
		t15.size="Small";
		System.out.println("The size is "+t15.size);
		t15.wheels=2;
		System.out.println("The wheels are "+t15.wheels);
		t15.weight=2.7;
		System.out.println("The weight is "+t15.weight);
		t15.hasLock=false;
		System.out.println("Lock available: "+t15.hasLock);

		TrolleyBag t16 = new TrolleyBag();
		t16.brand="Safari Pro";
		System.out.println("The brand is "+t16.brand);
		t16.cost=4200;
		System.out.println("The cost is "+t16.cost);
		t16.colour="Green";
		System.out.println("The colour is "+t16.colour);
		t16.material="Fabric";
		System.out.println("The material is "+t16.material);
		t16.size="Large";
		System.out.println("The size is "+t16.size);
		t16.wheels=4;
		System.out.println("The wheels are "+t16.wheels);
		t16.weight=3.5;
		System.out.println("The weight is "+t16.weight);
		t16.hasLock=true;
		System.out.println("Lock available: "+t16.hasLock);

		TrolleyBag t17 = new TrolleyBag();
		t17.brand="Skyline";
		System.out.println("The brand is "+t17.brand);
		t17.cost=3100;
		System.out.println("The cost is "+t17.cost);
		t17.colour="Red";
		System.out.println("The colour is "+t17.colour);
		t17.material="Plastic";
		System.out.println("The material is "+t17.material);
		t17.size="Medium";
		System.out.println("The size is "+t17.size);
		t17.wheels=4;
		System.out.println("The wheels are "+t17.wheels);
		t17.weight=3.0;
		System.out.println("The weight is "+t17.weight);
		t17.hasLock=true;
		System.out.println("Lock available: "+t17.hasLock);

		TrolleyBag t18 = new TrolleyBag();
		t18.brand="Urban Gear";
		System.out.println("The brand is "+t18.brand);
		t18.cost=2700;
		System.out.println("The cost is "+t18.cost);
		t18.colour="Blue";
		System.out.println("The colour is "+t18.colour);
		t18.material="Fabric";
		System.out.println("The material is "+t18.material);
		t18.size="Small";
		System.out.println("The size is "+t18.size);
		t18.wheels=2;
		System.out.println("The wheels are "+t18.wheels);
		t18.weight=2.6;
		System.out.println("The weight is "+t18.weight);
		t18.hasLock=false;
		System.out.println("Lock available: "+t18.hasLock);

		TrolleyBag t19 = new TrolleyBag();
		t19.brand="Travel Mate";
		System.out.println("The brand is "+t19.brand);
		t19.cost=3300;
		System.out.println("The cost is "+t19.cost);
		t19.colour="Grey";
		System.out.println("The colour is "+t19.colour);
		t19.material="Polycarbonate";
		System.out.println("The material is "+t19.material);
		t19.size="Medium";
		System.out.println("The size is "+t19.size);
		t19.wheels=4;
		System.out.println("The wheels are "+t19.wheels);
		t19.weight=3.4;
		System.out.println("The weight is "+t19.weight);
		t19.hasLock=true;
		System.out.println("Lock available: "+t19.hasLock);

		TrolleyBag t20 = new TrolleyBag();
		t20.brand="VIP Elite";
		System.out.println("The brand is "+t20.brand);
		t20.cost=5500;
		System.out.println("The cost is "+t20.cost);
		t20.colour="Black";
		System.out.println("The colour is "+t20.colour);
		t20.material="Polycarbonate";
		System.out.println("The material is "+t20.material);
		t20.size="Large";
		System.out.println("The size is "+t20.size);
		t20.wheels=4;
		System.out.println("The wheels are "+t20.wheels);
		t20.weight=3.9;
		System.out.println("The weight is "+t20.weight);
		t20.hasLock=true;
		System.out.println("Lock available: "+t20.hasLock);
		
				TrolleyBag t21 = new TrolleyBag();
		t21.brand="Globe Trotter";
		System.out.println("The brand is "+t21.brand);
		t21.cost=6000;
		System.out.println("The cost is "+t21.cost);
		t21.colour="Brown";
		System.out.println("The colour is "+t21.colour);
		t21.material="Leather";
		System.out.println("The material is "+t21.material);
		t21.size="Large";
		System.out.println("The size is "+t21.size);
		t21.wheels=4;
		System.out.println("The wheels are "+t21.wheels);
		t21.weight=4.2;
		System.out.println("The weight is "+t21.weight);
		t21.hasLock=true;
		System.out.println("Lock available: "+t21.hasLock);

		TrolleyBag t22 = new TrolleyBag();
		t22.brand="Tourister Lite";
		System.out.println("The brand is "+t22.brand);
		t22.cost=3700;
		System.out.println("The cost is "+t22.cost);
		t22.colour="Blue";
		System.out.println("The colour is "+t22.colour);
		t22.material="Fabric";
		System.out.println("The material is "+t22.material);
		t22.size="Medium";
		System.out.println("The size is "+t22.size);
		t22.wheels=2;
		System.out.println("The wheels are "+t22.wheels);
		t22.weight=3.0;
		System.out.println("The weight is "+t22.weight);
		t22.hasLock=false;
		System.out.println("Lock available: "+t22.hasLock);

		TrolleyBag t23 = new TrolleyBag();
		t23.brand="Travel King";
		System.out.println("The brand is "+t23.brand);
		t23.cost=2900;
		System.out.println("The cost is "+t23.cost);
		t23.colour="Red";
		System.out.println("The colour is "+t23.colour);
		t23.material="Plastic";
		System.out.println("The material is "+t23.material);
		t23.size="Small";
		System.out.println("The size is "+t23.size);
		t23.wheels=2;
		System.out.println("The wheels are "+t23.wheels);
		t23.weight=2.8;
		System.out.println("The weight is "+t23.weight);
		t23.hasLock=false;
		System.out.println("Lock available: "+t23.hasLock);

		TrolleyBag t24 = new TrolleyBag();
		t24.brand="Urban Travel";
		System.out.println("The brand is "+t24.brand);
		t24.cost=4100;
		System.out.println("The cost is "+t24.cost);
		t24.colour="Grey";
		System.out.println("The colour is "+t24.colour);
		t24.material="Polycarbonate";
		System.out.println("The material is "+t24.material);
		t24.size="Medium";
		System.out.println("The size is "+t24.size);
		t24.wheels=4;
		System.out.println("The wheels are "+t24.wheels);
		t24.weight=3.3;
		System.out.println("The weight is "+t24.weight);
		t24.hasLock=true;
		System.out.println("Lock available: "+t24.hasLock);

		TrolleyBag t25 = new TrolleyBag();
		t25.brand="Voyager";
		System.out.println("The brand is "+t25.brand);
		t25.cost=4600;
		System.out.println("The cost is "+t25.cost);
		t25.colour="Black";
		System.out.println("The colour is "+t25.colour);
		t25.material="Polycarbonate";
		System.out.println("The material is "+t25.material);
		t25.size="Large";
		System.out.println("The size is "+t25.size);
		t25.wheels=4;
		System.out.println("The wheels are "+t25.wheels);
		t25.weight=3.7;
		System.out.println("The weight is "+t25.weight);
		t25.hasLock=true;
		System.out.println("Lock available: "+t25.hasLock);

		TrolleyBag t26 = new TrolleyBag();
		t26.brand="TravelX";
		System.out.println("The brand is "+t26.brand);
		t26.cost=3000;
		System.out.println("The cost is "+t26.cost);
		t26.colour="Green";
		System.out.println("The colour is "+t26.colour);
		t26.material="Fabric";
		System.out.println("The material is "+t26.material);
		t26.size="Medium";
		System.out.println("The size is "+t26.size);
		t26.wheels=2;
		System.out.println("The wheels are "+t26.wheels);
		t26.weight=3.1;
		System.out.println("The weight is "+t26.weight);
		t26.hasLock=false;
		System.out.println("Lock available: "+t26.hasLock);

		TrolleyBag t27 = new TrolleyBag();
		t27.brand="GoTravel";
		System.out.println("The brand is "+t27.brand);
		t27.cost=3500;
		System.out.println("The cost is "+t27.cost);
		t27.colour="Blue";
		System.out.println("The colour is "+t27.colour);
		t27.material="Plastic";
		System.out.println("The material is "+t27.material);
		t27.size="Medium";
		System.out.println("The size is "+t27.size);
		t27.wheels=4;
		System.out.println("The wheels are "+t27.wheels);
		t27.weight=3.2;
		System.out.println("The weight is "+t27.weight);
		t27.hasLock=true;
		System.out.println("Lock available: "+t27.hasLock);

		TrolleyBag t28 = new TrolleyBag();
		t28.brand="EasyTrip";
		System.out.println("The brand is "+t28.brand);
		t28.cost=2800;
		System.out.println("The cost is "+t28.cost);
		t28.colour="Yellow";
		System.out.println("The colour is "+t28.colour);
		t28.material="Fabric";
		System.out.println("The material is "+t28.material);
		t28.size="Small";
		System.out.println("The size is "+t28.size);
		t28.wheels=2;
		System.out.println("The wheels are "+t28.wheels);
		t28.weight=2.7;
		System.out.println("The weight is "+t28.weight);
		t28.hasLock=false;
		System.out.println("Lock available: "+t28.hasLock);

		TrolleyBag t29 = new TrolleyBag();
		t29.brand="PackMate";
		System.out.println("The brand is "+t29.brand);
		t29.cost=3900;
		System.out.println("The cost is "+t29.cost);
		t29.colour="Grey";
		System.out.println("The colour is "+t29.colour);
		t29.material="Polycarbonate";
		System.out.println("The material is "+t29.material);
		t29.size="Large";
		System.out.println("The size is "+t29.size);
		t29.wheels=4;
		System.out.println("The wheels are "+t29.wheels);
		t29.weight=3.5;
		System.out.println("The weight is "+t29.weight);
		t29.hasLock=true;
		System.out.println("Lock available: "+t29.hasLock);

		TrolleyBag t30 = new TrolleyBag();
		t30.brand="Elite Travel";
		System.out.println("The brand is "+t30.brand);
		t30.cost=5200;
		System.out.println("The cost is "+t30.cost);
		t30.colour="Black";
		System.out.println("The colour is "+t30.colour);
		t30.material="Polycarbonate";
		System.out.println("The material is "+t30.material);
		t30.size="Large";
		System.out.println("The size is "+t30.size);
		t30.wheels=4;
		System.out.println("The wheels are "+t30.wheels);
		t30.weight=3.8;
		System.out.println("The weight is "+t30.weight);
		t30.hasLock=true;
		System.out.println("Lock available: "+t30.hasLock);
	}
}