class VaseExec
{
	public static void main(String[] args)
	{
		Vase v1 = new Vase();
		v1.brand="HomeCentre";
		System.out.println("The brand is "+v1.brand);
		v1.material="Glass";
		System.out.println("Material is "+v1.material);
		v1.colour="Transparent";
		System.out.println("Colour is "+v1.colour);
		v1.cost=500;
		System.out.println("Cost is "+v1.cost);
		v1.height=10.5;
		System.out.println("Height is "+v1.height);
		v1.shape="Round";
		System.out.println("Shape is "+v1.shape);
		v1.isDecorative=true;
		System.out.println("Decorative "+v1.isDecorative);
		v1.origin="India";
		System.out.println("Origin "+v1.origin);

		Vase v2 = new Vase();
		v2.brand="Ikea";
		System.out.println("The brand is "+v2.brand);
		v2.material="Ceramic";
		System.out.println("Material is "+v2.material);
		v2.colour="White";
		System.out.println("Colour is "+v2.colour);
		v2.cost=700;
		System.out.println("Cost is "+v2.cost);
		v2.height=12.0;
		System.out.println("Height is "+v2.height);
		v2.shape="Cylindrical";
		System.out.println("Shape is "+v2.shape);
		v2.isDecorative=true;
		System.out.println("Decorative "+v2.isDecorative);
		v2.origin="Sweden";
		System.out.println("Origin "+v2.origin);

		Vase v3 = new Vase();
		v3.brand="UrbanLadder";
		System.out.println("The brand is "+v3.brand);
		v3.material="Wood";
		System.out.println("Material is "+v3.material);
		v3.colour="Brown";
		System.out.println("Colour is "+v3.colour);
		v3.cost=900;
		System.out.println("Cost is "+v3.cost);
		v3.height=14.0;
		System.out.println("Height is "+v3.height);
		v3.shape="Square";
		System.out.println("Shape is "+v3.shape);
		v3.isDecorative=true;
		System.out.println("Decorative "+v3.isDecorative);
		v3.origin="India";
		System.out.println("Origin "+v3.origin);

		Vase v4 = new Vase();
		v4.brand="Nilkamal";
		System.out.println("The brand is "+v4.brand);
		v4.material="Plastic";
		System.out.println("Material is "+v4.material);
		v4.colour="Blue";
		System.out.println("Colour is "+v4.colour);
		v4.cost=300;
		System.out.println("Cost is "+v4.cost);
		v4.height=9.0;
		System.out.println("Height is "+v4.height);
		v4.shape="Round";
		System.out.println("Shape is "+v4.shape);
		v4.isDecorative=false;
		System.out.println("Decorative "+v4.isDecorative);
		v4.origin="India";
		System.out.println("Origin "+v4.origin);

		Vase v5 = new Vase();
		v5.brand="Pepperfry";
		System.out.println("The brand is "+v5.brand);
		v5.material="Ceramic";
		System.out.println("Material is "+v5.material);
		v5.colour="Black";
		System.out.println("Colour is "+v5.colour);
		v5.cost=800;
		System.out.println("Cost is "+v5.cost);
		v5.height=11.5;
		System.out.println("Height is "+v5.height);
		v5.shape="Oval";
		System.out.println("Shape is "+v5.shape);
		v5.isDecorative=true;
		System.out.println("Decorative "+v5.isDecorative);
		v5.origin="India";
		System.out.println("Origin "+v5.origin);

		Vase v6 = new Vase();
		v6.brand="Local";
		System.out.println("The brand is "+v6.brand);
		v6.material="Clay";
		System.out.println("Material is "+v6.material);
		v6.colour="Brown";
		System.out.println("Colour is "+v6.colour);
		v6.cost=200;
		System.out.println("Cost is "+v6.cost);
		v6.height=8.0;
		System.out.println("Height is "+v6.height);
		v6.shape="Round";
		System.out.println("Shape is "+v6.shape);
		v6.isDecorative=false;
		System.out.println("Decorative "+v6.isDecorative);
		v6.origin="Village";
		System.out.println("Origin "+v6.origin);

		Vase v7 = new Vase();
		v7.brand="AmazonBasics";
		System.out.println("The brand is "+v7.brand);
		v7.material="Glass";
		System.out.println("Material is "+v7.material);
		v7.colour="Green";
		System.out.println("Colour is "+v7.colour);
		v7.cost=600;
		System.out.println("Cost is "+v7.cost);
		v7.height=13.0;
		System.out.println("Height is "+v7.height);
		v7.shape="Cylindrical";
		System.out.println("Shape is "+v7.shape);
		v7.isDecorative=true;
		System.out.println("Decorative "+v7.isDecorative);
		v7.origin="India";
		System.out.println("Origin "+v7.origin);

		Vase v8 = new Vase();
		v8.brand="Flipkart";
		System.out.println("The brand is "+v8.brand);
		v8.material="Metal";
		System.out.println("Material is "+v8.material);
		v8.colour="Silver";
		System.out.println("Colour is "+v8.colour);
		v8.cost=1000;
		System.out.println("Cost is "+v8.cost);
		v8.height=15.0;
		System.out.println("Height is "+v8.height);
		v8.shape="Square";
		System.out.println("Shape is "+v8.shape);
		v8.isDecorative=true;
		System.out.println("Decorative "+v8.isDecorative);
		v8.origin="India";
		System.out.println("Origin "+v8.origin);

		Vase v9 = new Vase();
		v9.brand="HomeTown";
		System.out.println("The brand is "+v9.brand);
		v9.material="Ceramic";
		System.out.println("Material is "+v9.material);
		v9.colour="Pink";
		System.out.println("Colour is "+v9.colour);
		v9.cost=750;
		System.out.println("Cost is "+v9.cost);
		v9.height=12.5;
		System.out.println("Height is "+v9.height);
		v9.shape="Oval";
		System.out.println("Shape is "+v9.shape);
		v9.isDecorative=true;
		System.out.println("Decorative "+v9.isDecorative);
		v9.origin="India";
		System.out.println("Origin "+v9.origin);

		Vase v10 = new Vase();
		v10.brand="CraftsIndia";
		System.out.println("The brand is "+v10.brand);
		v10.material="Clay";
		System.out.println("Material is "+v10.material);
		v10.colour="Terracotta";
		System.out.println("Colour is "+v10.colour);
		v10.cost=350;
		System.out.println("Cost is "+v10.cost);
		v10.height=9.5;
		System.out.println("Height is "+v10.height);
		v10.shape="Round";
		System.out.println("Shape is "+v10.shape);
		v10.isDecorative=true;
		System.out.println("Decorative "+v10.isDecorative);
		v10.origin="India";
		System.out.println("Origin "+v10.origin);
		
				Vase v11 = new Vase();
		v11.brand="DecoWorld";
		System.out.println("The brand is "+v11.brand);
		v11.material="Glass";
		System.out.println("Material is "+v11.material);
		v11.colour="Blue";
		System.out.println("Colour is "+v11.colour);
		v11.cost=650;
		System.out.println("Cost is "+v11.cost);
		v11.height=11.0;
		System.out.println("Height is "+v11.height);
		v11.shape="Cylindrical";
		System.out.println("Shape is "+v11.shape);
		v11.isDecorative=true;
		System.out.println("Decorative "+v11.isDecorative);
		v11.origin="India";
		System.out.println("Origin "+v11.origin);

		Vase v12 = new Vase();
		v12.brand="ArtIndia";
		System.out.println("The brand is "+v12.brand);
		v12.material="Ceramic";
		System.out.println("Material is "+v12.material);
		v12.colour="White";
		System.out.println("Colour is "+v12.colour);
		v12.cost=820;
		System.out.println("Cost is "+v12.cost);
		v12.height=13.5;
		System.out.println("Height is "+v12.height);
		v12.shape="Oval";
		System.out.println("Shape is "+v12.shape);
		v12.isDecorative=true;
		System.out.println("Decorative "+v12.isDecorative);
		v12.origin="India";
		System.out.println("Origin "+v12.origin);

		Vase v13 = new Vase();
		v13.brand="StyleHome";
		System.out.println("The brand is "+v13.brand);
		v13.material="Metal";
		System.out.println("Material is "+v13.material);
		v13.colour="Golden";
		System.out.println("Colour is "+v13.colour);
		v13.cost=1200;
		System.out.println("Cost is "+v13.cost);
		v13.height=16.0;
		System.out.println("Height is "+v13.height);
		v13.shape="Square";
		System.out.println("Shape is "+v13.shape);
		v13.isDecorative=true;
		System.out.println("Decorative "+v13.isDecorative);
		v13.origin="India";
		System.out.println("Origin "+v13.origin);

		Vase v14 = new Vase();
		v14.brand="BudgetHome";
		System.out.println("The brand is "+v14.brand);
		v14.material="Plastic";
		System.out.println("Material is "+v14.material);
		v14.colour="Green";
		System.out.println("Colour is "+v14.colour);
		v14.cost=250;
		System.out.println("Cost is "+v14.cost);
		v14.height=8.5;
		System.out.println("Height is "+v14.height);
		v14.shape="Round";
		System.out.println("Shape is "+v14.shape);
		v14.isDecorative=false;
		System.out.println("Decorative "+v14.isDecorative);
		v14.origin="India";
		System.out.println("Origin "+v14.origin);

		Vase v15 = new Vase();
		v15.brand="PremiumDecor";
		System.out.println("The brand is "+v15.brand);
		v15.material="Glass";
		System.out.println("Material is "+v15.material);
		v15.colour="Black";
		System.out.println("Colour is "+v15.colour);
		v15.cost=1500;
		System.out.println("Cost is "+v15.cost);
		v15.height=18.0;
		System.out.println("Height is "+v15.height);
		v15.shape="Cylindrical";
		System.out.println("Shape is "+v15.shape);
		v15.isDecorative=true;
		System.out.println("Decorative "+v15.isDecorative);
		v15.origin="Italy";
		System.out.println("Origin "+v15.origin);

		Vase v16 = new Vase();
		v16.brand="SimpleHome";
		System.out.println("The brand is "+v16.brand);
		v16.material="Clay";
		System.out.println("Material is "+v16.material);
		v16.colour="Brown";
		System.out.println("Colour is "+v16.colour);
		v16.cost=220;
		System.out.println("Cost is "+v16.cost);
		v16.height=9.0;
		System.out.println("Height is "+v16.height);
		v16.shape="Round";
		System.out.println("Shape is "+v16.shape);
		v16.isDecorative=false;
		System.out.println("Decorative "+v16.isDecorative);
		v16.origin="India";
		System.out.println("Origin "+v16.origin);

		Vase v17 = new Vase();
		v17.brand="DecorPlus";
		System.out.println("The brand is "+v17.brand);
		v17.material="Ceramic";
		System.out.println("Material is "+v17.material);
		v17.colour="Purple";
		System.out.println("Colour is "+v17.colour);
		v17.cost=880;
		System.out.println("Cost is "+v17.cost);
		v17.height=14.5;
		System.out.println("Height is "+v17.height);
		v17.shape="Oval";
		System.out.println("Shape is "+v17.shape);
		v17.isDecorative=true;
		System.out.println("Decorative "+v17.isDecorative);
		v17.origin="India";
		System.out.println("Origin "+v17.origin);

		Vase v18 = new Vase();
		v18.brand="Artisan";
		System.out.println("The brand is "+v18.brand);
		v18.material="Wood";
		System.out.println("Material is "+v18.material);
		v18.colour="Brown";
		System.out.println("Colour is "+v18.colour);
		v18.cost=950;
		System.out.println("Cost is "+v18.cost);
		v18.height=15.5;
		System.out.println("Height is "+v18.height);
		v18.shape="Square";
		System.out.println("Shape is "+v18.shape);
		v18.isDecorative=true;
		System.out.println("Decorative "+v18.isDecorative);
		v18.origin="India";
		System.out.println("Origin "+v18.origin);

		Vase v19 = new Vase();
		v19.brand="EcoDecor";
		System.out.println("The brand is "+v19.brand);
		v19.material="Bamboo";
		System.out.println("Material is "+v19.material);
		v19.colour="Light Brown";
		System.out.println("Colour is "+v19.colour);
		v19.cost=400;
		System.out.println("Cost is "+v19.cost);
		v19.height=12.0;
		System.out.println("Height is "+v19.height);
		v19.shape="Cylindrical";
		System.out.println("Shape is "+v19.shape);
		v19.isDecorative=true;
		System.out.println("Decorative "+v19.isDecorative);
		v19.origin="India";
		System.out.println("Origin "+v19.origin);

		Vase v20 = new Vase();
		v20.brand="UrbanDecor";
		System.out.println("The brand is "+v20.brand);
		v20.material="Glass";
		System.out.println("Material is "+v20.material);
		v20.colour="Grey";
		System.out.println("Colour is "+v20.colour);
		v20.cost=700;
		System.out.println("Cost is "+v20.cost);
		v20.height=13.0;
		System.out.println("Height is "+v20.height);
		v20.shape="Round";
		System.out.println("Shape is "+v20.shape);
		v20.isDecorative=true;
		System.out.println("Decorative "+v20.isDecorative);
		v20.origin="India";
		System.out.println("Origin "+v20.origin);
		
				Vase v21 = new Vase();
		v21.brand="ClassicDecor";
		System.out.println("The brand is "+v21.brand);
		v21.material="Ceramic";
		System.out.println("Material is "+v21.material);
		v21.colour="Beige";
		System.out.println("Colour is "+v21.colour);
		v21.cost=600;
		System.out.println("Cost is "+v21.cost);
		v21.height=11.0;
		System.out.println("Height is "+v21.height);
		v21.shape="Oval";
		System.out.println("Shape is "+v21.shape);
		v21.isDecorative=true;
		System.out.println("Decorative "+v21.isDecorative);
		v21.origin="India";
		System.out.println("Origin "+v21.origin);

		Vase v22 = new Vase();
		v22.brand="ModernHome";
		System.out.println("The brand is "+v22.brand);
		v22.material="Metal";
		System.out.println("Material is "+v22.material);
		v22.colour="Black";
		System.out.println("Colour is "+v22.colour);
		v22.cost=1100;
		System.out.println("Cost is "+v22.cost);
		v22.height=17.0;
		System.out.println("Height is "+v22.height);
		v22.shape="Square";
		System.out.println("Shape is "+v22.shape);
		v22.isDecorative=true;
		System.out.println("Decorative "+v22.isDecorative);
		v22.origin="India";
		System.out.println("Origin "+v22.origin);

		Vase v23 = new Vase();
		v23.brand="VillageCraft";
		System.out.println("The brand is "+v23.brand);
		v23.material="Clay";
		System.out.println("Material is "+v23.material);
		v23.colour="Brown";
		System.out.println("Colour is "+v23.colour);
		v23.cost=300;
		System.out.println("Cost is "+v23.cost);
		v23.height=10.0;
		System.out.println("Height is "+v23.height);
		v23.shape="Round";
		System.out.println("Shape is "+v23.shape);
		v23.isDecorative=false;
		System.out.println("Decorative "+v23.isDecorative);
		v23.origin="Village";
		System.out.println("Origin "+v23.origin);

		Vase v24 = new Vase();
		v24.brand="GlassArt";
		System.out.println("The brand is "+v24.brand);
		v24.material="Glass";
		System.out.println("Material is "+v24.material);
		v24.colour="Transparent";
		System.out.println("Colour is "+v24.colour);
		v24.cost=850;
		System.out.println("Cost is "+v24.cost);
		v24.height=14.0;
		System.out.println("Height is "+v24.height);
		v24.shape="Cylindrical";
		System.out.println("Shape is "+v24.shape);
		v24.isDecorative=true;
		System.out.println("Decorative "+v24.isDecorative);
		v24.origin="India";
		System.out.println("Origin "+v24.origin);

		Vase v25 = new Vase();
		v25.brand="RoyalDecor";
		System.out.println("The brand is "+v25.brand);
		v25.material="Ceramic";
		System.out.println("Material is "+v25.material);
		v25.colour="Golden";
		System.out.println("Colour is "+v25.colour);
		v25.cost=1300;
		System.out.println("Cost is "+v25.cost);
		v25.height=18.5;
		System.out.println("Height is "+v25.height);
		v25.shape="Oval";
		System.out.println("Shape is "+v25.shape);
		v25.isDecorative=true;
		System.out.println("Decorative "+v25.isDecorative);
		v25.origin="India";
		System.out.println("Origin "+v25.origin);

		Vase v26 = new Vase();
		v26.brand="MiniDecor";
		System.out.println("The brand is "+v26.brand);
		v26.material="Plastic";
		System.out.println("Material is "+v26.material);
		v26.colour="Pink";
		System.out.println("Colour is "+v26.colour);
		v26.cost=180;
		System.out.println("Cost is "+v26.cost);
		v26.height=7.5;
		System.out.println("Height is "+v26.height);
		v26.shape="Round";
		System.out.println("Shape is "+v26.shape);
		v26.isDecorative=false;
		System.out.println("Decorative "+v26.isDecorative);
		v26.origin="India";
		System.out.println("Origin "+v26.origin);

		Vase v27 = new Vase();
		v27.brand="EliteDecor";
		System.out.println("The brand is "+v27.brand);
		v27.material="Glass";
		System.out.println("Material is "+v27.material);
		v27.colour="Blue";
		System.out.println("Colour is "+v27.colour);
		v27.cost=950;
		System.out.println("Cost is "+v27.cost);
		v27.height=16.0;
		System.out.println("Height is "+v27.height);
		v27.shape="Cylindrical";
		System.out.println("Shape is "+v27.shape);
		v27.isDecorative=true;
		System.out.println("Decorative "+v27.isDecorative);
		v27.origin="India";
		System.out.println("Origin "+v27.origin);

		Vase v28 = new Vase();
		v28.brand="SimpleDecor";
		System.out.println("The brand is "+v28.brand);
		v28.material="Clay";
		System.out.println("Material is "+v28.material);
		v28.colour="Terracotta";
		System.out.println("Colour is "+v28.colour);
		v28.cost=280;
		System.out.println("Cost is "+v28.cost);
		v28.height=9.5;
		System.out.println("Height is "+v28.height);
		v28.shape="Round";
		System.out.println("Shape is "+v28.shape);
		v28.isDecorative=true;
		System.out.println("Decorative "+v28.isDecorative);
		v28.origin="India";
		System.out.println("Origin "+v28.origin);

		Vase v29 = new Vase();
		v29.brand="TrendyHome";
		System.out.println("The brand is "+v29.brand);
		v29.material="Metal";
		System.out.println("Material is "+v29.material);
		v29.colour="Silver";
		System.out.println("Colour is "+v29.colour);
		v29.cost=1050;
		System.out.println("Cost is "+v29.cost);
		v29.height=17.5;
		System.out.println("Height is "+v29.height);
		v29.shape="Square";
		System.out.println("Shape is "+v29.shape);
		v29.isDecorative=true;
		System.out.println("Decorative "+v29.isDecorative);
		v29.origin="India";
		System.out.println("Origin "+v29.origin);

		Vase v30 = new Vase();
		v30.brand="LuxuryDecor";
		System.out.println("The brand is "+v30.brand);
		v30.material="Glass";
		System.out.println("Material is "+v30.material);
		v30.colour="Black";
		System.out.println("Colour is "+v30.colour);
		v30.cost=1600;
		System.out.println("Cost is "+v30.cost);
		v30.height=19.0;
		System.out.println("Height is "+v30.height);
		v30.shape="Oval";
		System.out.println("Shape is "+v30.shape);
		v30.isDecorative=true;
		System.out.println("Decorative "+v30.isDecorative);
		v30.origin="Italy";
		System.out.println("Origin "+v30.origin);
	}
}