class WalletExec
{
	public static void main(String[] args)
	{
		Wallet w1 = new Wallet();
		w1.brand="Wildcraft";
		System.out.println("The brand is "+w1.brand);
		w1.cost=1200;
		System.out.println("The cost is "+w1.cost);
		w1.colour="Black";
		System.out.println("The colour is "+w1.colour);
		w1.material="Leather";
		System.out.println("The material is "+w1.material);
		w1.type="Bifold";
		System.out.println("The type is "+w1.type);
		w1.compartments=4;
		System.out.println("The compartments are "+w1.compartments);
		w1.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w1.hasCoinPocket);
		w1.size="Medium";
		System.out.println("The size is "+w1.size);

		Wallet w2 = new Wallet();
		w2.brand="Puma";
		System.out.println("The brand is "+w2.brand);
		w2.cost=900;
		System.out.println("The cost is "+w2.cost);
		w2.colour="Brown";
		System.out.println("The colour is "+w2.colour);
		w2.material="Leather";
		System.out.println("The material is "+w2.material);
		w2.type="Trifold";
		System.out.println("The type is "+w2.type);
		w2.compartments=5;
		System.out.println("The compartments are "+w2.compartments);
		w2.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w2.hasCoinPocket);
		w2.size="Medium";
		System.out.println("The size is "+w2.size);

		Wallet w3 = new Wallet();
		w3.brand="Skybags";
		System.out.println("The brand is "+w3.brand);
		w3.cost=800;
		System.out.println("The cost is "+w3.cost);
		w3.colour="Blue";
		System.out.println("The colour is "+w3.colour);
		w3.material="Fabric";
		System.out.println("The material is "+w3.material);
		w3.type="Bifold";
		System.out.println("The type is "+w3.type);
		w3.compartments=3;
		System.out.println("The compartments are "+w3.compartments);
		w3.hasCoinPocket=false;
		System.out.println("Coin pocket available: "+w3.hasCoinPocket);
		w3.size="Small";
		System.out.println("The size is "+w3.size);

		Wallet w4 = new Wallet();
		w4.brand="Fastrack";
		System.out.println("The brand is "+w4.brand);
		w4.cost=1100;
		System.out.println("The cost is "+w4.cost);
		w4.colour="Grey";
		System.out.println("The colour is "+w4.colour);
		w4.material="Leather";
		System.out.println("The material is "+w4.material);
		w4.type="Bifold";
		System.out.println("The type is "+w4.type);
		w4.compartments=4;
		System.out.println("The compartments are "+w4.compartments);
		w4.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w4.hasCoinPocket);
		w4.size="Medium";
		System.out.println("The size is "+w4.size);

		Wallet w5 = new Wallet();
		w5.brand="Levis";
		System.out.println("The brand is "+w5.brand);
		w5.cost=1500;
		System.out.println("The cost is "+w5.cost);
		w5.colour="Black";
		System.out.println("The colour is "+w5.colour);
		w5.material="Leather";
		System.out.println("The material is "+w5.material);
		w5.type="Trifold";
		System.out.println("The type is "+w5.type);
		w5.compartments=6;
		System.out.println("The compartments are "+w5.compartments);
		w5.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w5.hasCoinPocket);
		w5.size="Large";
		System.out.println("The size is "+w5.size);

		Wallet w6 = new Wallet();
		w6.brand="Allen Solly";
		System.out.println("The brand is "+w6.brand);
		w6.cost=1300;
		System.out.println("The cost is "+w6.cost);
		w6.colour="Brown";
		System.out.println("The colour is "+w6.colour);
		w6.material="Leather";
		System.out.println("The material is "+w6.material);
		w6.type="Bifold";
		System.out.println("The type is "+w6.type);
		w6.compartments=4;
		System.out.println("The compartments are "+w6.compartments);
		w6.hasCoinPocket=false;
		System.out.println("Coin pocket available: "+w6.hasCoinPocket);
		w6.size="Medium";
		System.out.println("The size is "+w6.size);

		Wallet w7 = new Wallet();
		w7.brand="Tommy";
		System.out.println("The brand is "+w7.brand);
		w7.cost=2000;
		System.out.println("The cost is "+w7.cost);
		w7.colour="Black";
		System.out.println("The colour is "+w7.colour);
		w7.material="Leather";
		System.out.println("The material is "+w7.material);
		w7.type="Bifold";
		System.out.println("The type is "+w7.type);
		w7.compartments=5;
		System.out.println("The compartments are "+w7.compartments);
		w7.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w7.hasCoinPocket);
		w7.size="Large";
		System.out.println("The size is "+w7.size);

		Wallet w8 = new Wallet();
		w8.brand="Woodland";
		System.out.println("The brand is "+w8.brand);
		w8.cost=1700;
		System.out.println("The cost is "+w8.cost);
		w8.colour="Brown";
		System.out.println("The colour is "+w8.colour);
		w8.material="Leather";
		System.out.println("The material is "+w8.material);
		w8.type="Trifold";
		System.out.println("The type is "+w8.type);
		w8.compartments=6;
		System.out.println("The compartments are "+w8.compartments);
		w8.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w8.hasCoinPocket);
		w8.size="Large";
		System.out.println("The size is "+w8.size);

		Wallet w9 = new Wallet();
		w9.brand="Nike";
		System.out.println("The brand is "+w9.brand);
		w9.cost=1400;
		System.out.println("The cost is "+w9.cost);
		w9.colour="Blue";
		System.out.println("The colour is "+w9.colour);
		w9.material="Fabric";
		System.out.println("The material is "+w9.material);
		w9.type="Bifold";
		System.out.println("The type is "+w9.type);
		w9.compartments=3;
		System.out.println("The compartments are "+w9.compartments);
		w9.hasCoinPocket=false;
		System.out.println("Coin pocket available: "+w9.hasCoinPocket);
		w9.size="Medium";
		System.out.println("The size is "+w9.size);

		Wallet w10 = new Wallet();
		w10.brand="Adidas";
		System.out.println("The brand is "+w10.brand);
		w10.cost=1600;
		System.out.println("The cost is "+w10.cost);
		w10.colour="Black";
		System.out.println("The colour is "+w10.colour);
		w10.material="Fabric";
		System.out.println("The material is "+w10.material);
		w10.type="Bifold";
		System.out.println("The type is "+w10.type);
		w10.compartments=4;
		System.out.println("The compartments are "+w10.compartments);
		w10.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w10.hasCoinPocket);
		w10.size="Medium";
		System.out.println("The size is "+w10.size);
		
		
				Wallet w11 = new Wallet();
		w11.brand="Reebok";
		System.out.println("The brand is "+w11.brand);
		w11.cost=1300;
		System.out.println("The cost is "+w11.cost);
		w11.colour="Grey";
		System.out.println("The colour is "+w11.colour);
		w11.material="Fabric";
		System.out.println("The material is "+w11.material);
		w11.type="Bifold";
		System.out.println("The type is "+w11.type);
		w11.compartments=3;
		System.out.println("The compartments are "+w11.compartments);
		w11.hasCoinPocket=false;
		System.out.println("Coin pocket available: "+w11.hasCoinPocket);
		w11.size="Small";
		System.out.println("The size is "+w11.size);

		Wallet w12 = new Wallet();
		w12.brand="Hidesign";
		System.out.println("The brand is "+w12.brand);
		w12.cost=2500;
		System.out.println("The cost is "+w12.cost);
		w12.colour="Brown";
		System.out.println("The colour is "+w12.colour);
		w12.material="Leather";
		System.out.println("The material is "+w12.material);
		w12.type="Bifold";
		System.out.println("The type is "+w12.type);
		w12.compartments=5;
		System.out.println("The compartments are "+w12.compartments);
		w12.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w12.hasCoinPocket);
		w12.size="Large";
		System.out.println("The size is "+w12.size);

		Wallet w13 = new Wallet();
		w13.brand="Caprese";
		System.out.println("The brand is "+w13.brand);
		w13.cost=1800;
		System.out.println("The cost is "+w13.cost);
		w13.colour="Pink";
		System.out.println("The colour is "+w13.colour);
		w13.material="Leather";
		System.out.println("The material is "+w13.material);
		w13.type="Zip";
		System.out.println("The type is "+w13.type);
		w13.compartments=6;
		System.out.println("The compartments are "+w13.compartments);
		w13.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w13.hasCoinPocket);
		w13.size="Large";
		System.out.println("The size is "+w13.size);

		Wallet w14 = new Wallet();
		w14.brand="Lavie";
		System.out.println("The brand is "+w14.brand);
		w14.cost=1500;
		System.out.println("The cost is "+w14.cost);
		w14.colour="Red";
		System.out.println("The colour is "+w14.colour);
		w14.material="Leather";
		System.out.println("The material is "+w14.material);
		w14.type="Zip";
		System.out.println("The type is "+w14.type);
		w14.compartments=5;
		System.out.println("The compartments are "+w14.compartments);
		w14.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w14.hasCoinPocket);
		w14.size="Medium";
		System.out.println("The size is "+w14.size);

		Wallet w15 = new Wallet();
		w15.brand="Baggit";
		System.out.println("The brand is "+w15.brand);
		w15.cost=1200;
		System.out.println("The cost is "+w15.cost);
		w15.colour="Yellow";
		System.out.println("The colour is "+w15.colour);
		w15.material="Synthetic";
		System.out.println("The material is "+w15.material);
		w15.type="Zip";
		System.out.println("The type is "+w15.type);
		w15.compartments=4;
		System.out.println("The compartments are "+w15.compartments);
		w15.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w15.hasCoinPocket);
		w15.size="Medium";
		System.out.println("The size is "+w15.size);

		Wallet w16 = new Wallet();
		w16.brand="Gucci";
		System.out.println("The brand is "+w16.brand);
		w16.cost=5000;
		System.out.println("The cost is "+w16.cost);
		w16.colour="Black";
		System.out.println("The colour is "+w16.colour);
		w16.material="Leather";
		System.out.println("The material is "+w16.material);
		w16.type="Bifold";
		System.out.println("The type is "+w16.type);
		w16.compartments=6;
		System.out.println("The compartments are "+w16.compartments);
		w16.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w16.hasCoinPocket);
		w16.size="Large";
		System.out.println("The size is "+w16.size);

		Wallet w17 = new Wallet();
		w17.brand="Louis Vuitton";
		System.out.println("The brand is "+w17.brand);
		w17.cost=8000;
		System.out.println("The cost is "+w17.cost);
		w17.colour="Brown";
		System.out.println("The colour is "+w17.colour);
		w17.material="Leather";
		System.out.println("The material is "+w17.material);
		w17.type="Bifold";
		System.out.println("The type is "+w17.type);
		w17.compartments=7;
		System.out.println("The compartments are "+w17.compartments);
		w17.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w17.hasCoinPocket);
		w17.size="Large";
		System.out.println("The size is "+w17.size);

		Wallet w18 = new Wallet();
		w18.brand="Zara";
		System.out.println("The brand is "+w18.brand);
		w18.cost=2200;
		System.out.println("The cost is "+w18.cost);
		w18.colour="Grey";
		System.out.println("The colour is "+w18.colour);
		w18.material="Synthetic";
		System.out.println("The material is "+w18.material);
		w18.type="Zip";
		System.out.println("The type is "+w18.type);
		w18.compartments=5;
		System.out.println("The compartments are "+w18.compartments);
		w18.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w18.hasCoinPocket);
		w18.size="Medium";
		System.out.println("The size is "+w18.size);

		Wallet w19 = new Wallet();
		w19.brand="H&M";
		System.out.println("The brand is "+w19.brand);
		w19.cost=1000;
		System.out.println("The cost is "+w19.cost);
		w19.colour="Black";
		System.out.println("The colour is "+w19.colour);
		w19.material="Synthetic";
		System.out.println("The material is "+w19.material);
		w19.type="Bifold";
		System.out.println("The type is "+w19.type);
		w19.compartments=3;
		System.out.println("The compartments are "+w19.compartments);
		w19.hasCoinPocket=false;
		System.out.println("Coin pocket available: "+w19.hasCoinPocket);
		w19.size="Small";
		System.out.println("The size is "+w19.size);

		Wallet w20 = new Wallet();
		w20.brand="Forever21";
		System.out.println("The brand is "+w20.brand);
		w20.cost=1100;
		System.out.println("The cost is "+w20.cost);
		w20.colour="Pink";
		System.out.println("The colour is "+w20.colour);
		w20.material="Synthetic";
		System.out.println("The material is "+w20.material);
		w20.type="Zip";
		System.out.println("The type is "+w20.type);
		w20.compartments=4;
		System.out.println("The compartments are "+w20.compartments);
		w20.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w20.hasCoinPocket);
		w20.size="Medium";
		System.out.println("The size is "+w20.size);
		
				Wallet w21 = new Wallet();
		w21.brand="Guess";
		System.out.println("The brand is "+w21.brand);
		w21.cost=2700;
		System.out.println("The cost is "+w21.cost);
		w21.colour="Black";
		System.out.println("The colour is "+w21.colour);
		w21.material="Leather";
		System.out.println("The material is "+w21.material);
		w21.type="Bifold";
		System.out.println("The type is "+w21.type);
		w21.compartments=5;
		System.out.println("The compartments are "+w21.compartments);
		w21.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w21.hasCoinPocket);
		w21.size="Large";
		System.out.println("The size is "+w21.size);

		Wallet w22 = new Wallet();
		w22.brand="Armani";
		System.out.println("The brand is "+w22.brand);
		w22.cost=6000;
		System.out.println("The cost is "+w22.cost);
		w22.colour="Brown";
		System.out.println("The colour is "+w22.colour);
		w22.material="Leather";
		System.out.println("The material is "+w22.material);
		w22.type="Bifold";
		System.out.println("The type is "+w22.type);
		w22.compartments=6;
		System.out.println("The compartments are "+w22.compartments);
		w22.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w22.hasCoinPocket);
		w22.size="Large";
		System.out.println("The size is "+w22.size);

		Wallet w23 = new Wallet();
		w23.brand="Diesel";
		System.out.println("The brand is "+w23.brand);
		w23.cost=3000;
		System.out.println("The cost is "+w23.cost);
		w23.colour="Black";
		System.out.println("The colour is "+w23.colour);
		w23.material="Leather";
		System.out.println("The material is "+w23.material);
		w23.type="Bifold";
		System.out.println("The type is "+w23.type);
		w23.compartments=5;
		System.out.println("The compartments are "+w23.compartments);
		w23.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w23.hasCoinPocket);
		w23.size="Medium";
		System.out.println("The size is "+w23.size);

		Wallet w24 = new Wallet();
		w24.brand="Tom Ford";
		System.out.println("The brand is "+w24.brand);
		w24.cost=7000;
		System.out.println("The cost is "+w24.cost);
		w24.colour="Brown";
		System.out.println("The colour is "+w24.colour);
		w24.material="Leather";
		System.out.println("The material is "+w24.material);
		w24.type="Bifold";
		System.out.println("The type is "+w24.type);
		w24.compartments=6;
		System.out.println("The compartments are "+w24.compartments);
		w24.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w24.hasCoinPocket);
		w24.size="Large";
		System.out.println("The size is "+w24.size);

		Wallet w25 = new Wallet();
		w25.brand="Urban Forest";
		System.out.println("The brand is "+w25.brand);
		w25.cost=1300;
		System.out.println("The cost is "+w25.cost);
		w25.colour="Black";
		System.out.println("The colour is "+w25.colour);
		w25.material="Leather";
		System.out.println("The material is "+w25.material);
		w25.type="Bifold";
		System.out.println("The type is "+w25.type);
		w25.compartments=4;
		System.out.println("The compartments are "+w25.compartments);
		w25.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w25.hasCoinPocket);
		w25.size="Medium";
		System.out.println("The size is "+w25.size);

		Wallet w26 = new Wallet();
		w26.brand="Hornbull";
		System.out.println("The brand is "+w26.brand);
		w26.cost=1000;
		System.out.println("The cost is "+w26.cost);
		w26.colour="Brown";
		System.out.println("The colour is "+w26.colour);
		w26.material="Leather";
		System.out.println("The material is "+w26.material);
		w26.type="Bifold";
		System.out.println("The type is "+w26.type);
		w26.compartments=4;
		System.out.println("The compartments are "+w26.compartments);
		w26.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w26.hasCoinPocket);
		w26.size="Medium";
		System.out.println("The size is "+w26.size);

		Wallet w27 = new Wallet();
		w27.brand="Rigohill";
		System.out.println("The brand is "+w27.brand);
		w27.cost=900;
		System.out.println("The cost is "+w27.cost);
		w27.colour="Black";
		System.out.println("The colour is "+w27.colour);
		w27.material="Leather";
		System.out.println("The material is "+w27.material);
		w27.type="Bifold";
		System.out.println("The type is "+w27.type);
		w27.compartments=3;
		System.out.println("The compartments are "+w27.compartments);
		w27.hasCoinPocket=false;
		System.out.println("Coin pocket available: "+w27.hasCoinPocket);
		w27.size="Small";
		System.out.println("The size is "+w27.size);

		Wallet w28 = new Wallet();
		w28.brand="Contacts";
		System.out.println("The brand is "+w28.brand);
		w28.cost=1400;
		System.out.println("The cost is "+w28.cost);
		w28.colour="Brown";
		System.out.println("The colour is "+w28.colour);
		w28.material="Leather";
		System.out.println("The material is "+w28.material);
		w28.type="Bifold";
		System.out.println("The type is "+w28.type);
		w28.compartments=4;
		System.out.println("The compartments are "+w28.compartments);
		w28.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w28.hasCoinPocket);
		w28.size="Medium";
		System.out.println("The size is "+w28.size);

		Wallet w29 = new Wallet();
		w29.brand="Teakwood";
		System.out.println("The brand is "+w29.brand);
		w29.cost=1800;
		System.out.println("The cost is "+w29.cost);
		w29.colour="Black";
		System.out.println("The colour is "+w29.colour);
		w29.material="Leather";
		System.out.println("The material is "+w29.material);
		w29.type="Bifold";
		System.out.println("The type is "+w29.type);
		w29.compartments=5;
		System.out.println("The compartments are "+w29.compartments);
		w29.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w29.hasCoinPocket);
		w29.size="Large";
		System.out.println("The size is "+w29.size);

		Wallet w30 = new Wallet();
		w30.brand="Allen Cooper";
		System.out.println("The brand is "+w30.brand);
		w30.cost=1500;
		System.out.println("The cost is "+w30.cost);
		w30.colour="Brown";
		System.out.println("The colour is "+w30.colour);
		w30.material="Leather";
		System.out.println("The material is "+w30.material);
		w30.type="Bifold";
		System.out.println("The type is "+w30.type);
		w30.compartments=4;
		System.out.println("The compartments are "+w30.compartments);
		w30.hasCoinPocket=true;
		System.out.println("Coin pocket available: "+w30.hasCoinPocket);
		w30.size="Medium";
		System.out.println("The size is "+w30.size);
	}
}