class WatchExec
{
	public static void main(String[] args)
	{
		Watch w1 = new Watch();
		w1.brand="Titan";
		System.out.println("The brand is "+w1.brand);
		w1.cost=2500;
		System.out.println("The cost is "+w1.cost);
		w1.colour="Black";
		System.out.println("The colour is "+w1.colour);
		w1.type="Analog";
		System.out.println("The type is "+w1.type);
		w1.displayType="Dial";
		System.out.println("The display type is "+w1.displayType);
		w1.strapMaterial="Leather";
		System.out.println("The strap material is "+w1.strapMaterial);
		w1.isWaterResistant=true;
		System.out.println("Water resistant: "+w1.isWaterResistant);
		w1.size="Medium";
		System.out.println("The size is "+w1.size);

		Watch w2 = new Watch();
		w2.brand="Fastrack";
		System.out.println("The brand is "+w2.brand);
		w2.cost=1800;
		System.out.println("The cost is "+w2.cost);
		w2.colour="Blue";
		System.out.println("The colour is "+w2.colour);
		w2.type="Digital";
		System.out.println("The type is "+w2.type);
		w2.displayType="LED";
		System.out.println("The display type is "+w2.displayType);
		w2.strapMaterial="Rubber";
		System.out.println("The strap material is "+w2.strapMaterial);
		w2.isWaterResistant=true;
		System.out.println("Water resistant: "+w2.isWaterResistant);
		w2.size="Medium";
		System.out.println("The size is "+w2.size);

		Watch w3 = new Watch();
		w3.brand="Casio";
		System.out.println("The brand is "+w3.brand);
		w3.cost=2200;
		System.out.println("The cost is "+w3.cost);
		w3.colour="Grey";
		System.out.println("The colour is "+w3.colour);
		w3.type="Digital";
		System.out.println("The type is "+w3.type);
		w3.displayType="LCD";
		System.out.println("The display type is "+w3.displayType);
		w3.strapMaterial="Plastic";
		System.out.println("The strap material is "+w3.strapMaterial);
		w3.isWaterResistant=true;
		System.out.println("Water resistant: "+w3.isWaterResistant);
		w3.size="Large";
		System.out.println("The size is "+w3.size);

		Watch w4 = new Watch();
		w4.brand="Sonata";
		System.out.println("The brand is "+w4.brand);
		w4.cost=1200;
		System.out.println("The cost is "+w4.cost);
		w4.colour="Black";
		System.out.println("The colour is "+w4.colour);
		w4.type="Analog";
		System.out.println("The type is "+w4.type);
		w4.displayType="Dial";
		System.out.println("The display type is "+w4.displayType);
		w4.strapMaterial="Metal";
		System.out.println("The strap material is "+w4.strapMaterial);
		w4.isWaterResistant=false;
		System.out.println("Water resistant: "+w4.isWaterResistant);
		w4.size="Small";
		System.out.println("The size is "+w4.size);

		Watch w5 = new Watch();
		w5.brand="Timex";
		System.out.println("The brand is "+w5.brand);
		w5.cost=2000;
		System.out.println("The cost is "+w5.cost);
		w5.colour="Brown";
		System.out.println("The colour is "+w5.colour);
		w5.type="Analog";
		System.out.println("The type is "+w5.type);
		w5.displayType="Dial";
		System.out.println("The display type is "+w5.displayType);
		w5.strapMaterial="Leather";
		System.out.println("The strap material is "+w5.strapMaterial);
		w5.isWaterResistant=true;
		System.out.println("Water resistant: "+w5.isWaterResistant);
		w5.size="Medium";
		System.out.println("The size is "+w5.size);

		Watch w6 = new Watch();
		w6.brand="Noise";
		System.out.println("The brand is "+w6.brand);
		w6.cost=3000;
		System.out.println("The cost is "+w6.cost);
		w6.colour="Black";
		System.out.println("The colour is "+w6.colour);
		w6.type="Smart";
		System.out.println("The type is "+w6.type);
		w6.displayType="Touchscreen";
		System.out.println("The display type is "+w6.displayType);
		w6.strapMaterial="Rubber";
		System.out.println("The strap material is "+w6.strapMaterial);
		w6.isWaterResistant=true;
		System.out.println("Water resistant: "+w6.isWaterResistant);
		w6.size="Medium";
		System.out.println("The size is "+w6.size);

		Watch w7 = new Watch();
		w7.brand="Boat";
		System.out.println("The brand is "+w7.brand);
		w7.cost=2800;
		System.out.println("The cost is "+w7.cost);
		w7.colour="Blue";
		System.out.println("The colour is "+w7.colour);
		w7.type="Smart";
		System.out.println("The type is "+w7.type);
		w7.displayType="Touchscreen";
		System.out.println("The display type is "+w7.displayType);
		w7.strapMaterial="Silicone";
		System.out.println("The strap material is "+w7.strapMaterial);
		w7.isWaterResistant=true;
		System.out.println("Water resistant: "+w7.isWaterResistant);
		w7.size="Large";
		System.out.println("The size is "+w7.size);

		Watch w8 = new Watch();
		w8.brand="FireBoltt";
		System.out.println("The brand is "+w8.brand);
		w8.cost=2600;
		System.out.println("The cost is "+w8.cost);
		w8.colour="Black";
		System.out.println("The colour is "+w8.colour);
		w8.type="Smart";
		System.out.println("The type is "+w8.type);
		w8.displayType="Touchscreen";
		System.out.println("The display type is "+w8.displayType);
		w8.strapMaterial="Rubber";
		System.out.println("The strap material is "+w8.strapMaterial);
		w8.isWaterResistant=true;
		System.out.println("Water resistant: "+w8.isWaterResistant);
		w8.size="Medium";
		System.out.println("The size is "+w8.size);

		Watch w9 = new Watch();
		w9.brand="Rolex";
		System.out.println("The brand is "+w9.brand);
		w9.cost=50000;
		System.out.println("The cost is "+w9.cost);
		w9.colour="Gold";
		System.out.println("The colour is "+w9.colour);
		w9.type="Analog";
		System.out.println("The type is "+w9.type);
		w9.displayType="Dial";
		System.out.println("The display type is "+w9.displayType);
		w9.strapMaterial="Metal";
		System.out.println("The strap material is "+w9.strapMaterial);
		w9.isWaterResistant=true;
		System.out.println("Water resistant: "+w9.isWaterResistant);
		w9.size="Large";
		System.out.println("The size is "+w9.size);

		Watch w10 = new Watch();
		w10.brand="Fossil";
		System.out.println("The brand is "+w10.brand);
		w10.cost=7000;
		System.out.println("The cost is "+w10.cost);
		w10.colour="Brown";
		System.out.println("The colour is "+w10.colour);
		w10.type="Analog";
		System.out.println("The type is "+w10.type);
		w10.displayType="Dial";
		System.out.println("The display type is "+w10.displayType);
		w10.strapMaterial="Leather";
		System.out.println("The strap material is "+w10.strapMaterial);
		w10.isWaterResistant=true;
		System.out.println("Water resistant: "+w10.isWaterResistant);
		w10.size="Medium";
		System.out.println("The size is "+w10.size);
		
				Watch w11 = new Watch();
		w11.brand="Citizen";
		System.out.println("The brand is "+w11.brand);
		w11.cost=8000;
		System.out.println("The cost is "+w11.cost);
		w11.colour="Black";
		System.out.println("The colour is "+w11.colour);
		w11.type="Analog";
		System.out.println("The type is "+w11.type);
		w11.displayType="Dial";
		System.out.println("The display type is "+w11.displayType);
		w11.strapMaterial="Metal";
		System.out.println("The strap material is "+w11.strapMaterial);
		w11.isWaterResistant=true;
		System.out.println("Water resistant: "+w11.isWaterResistant);
		w11.size="Large";
		System.out.println("The size is "+w11.size);

		Watch w12 = new Watch();
		w12.brand="Seiko";
		System.out.println("The brand is "+w12.brand);
		w12.cost=9000;
		System.out.println("The cost is "+w12.cost);
		w12.colour="Silver";
		System.out.println("The colour is "+w12.colour);
		w12.type="Analog";
		System.out.println("The type is "+w12.type);
		w12.displayType="Dial";
		System.out.println("The display type is "+w12.displayType);
		w12.strapMaterial="Metal";
		System.out.println("The strap material is "+w12.strapMaterial);
		w12.isWaterResistant=true;
		System.out.println("Water resistant: "+w12.isWaterResistant);
		w12.size="Large";
		System.out.println("The size is "+w12.size);

		Watch w13 = new Watch();
		w13.brand="Maxima";
		System.out.println("The brand is "+w13.brand);
		w13.cost=1500;
		System.out.println("The cost is "+w13.cost);
		w13.colour="Blue";
		System.out.println("The colour is "+w13.colour);
		w13.type="Analog";
		System.out.println("The type is "+w13.type);
		w13.displayType="Dial";
		System.out.println("The display type is "+w13.displayType);
		w13.strapMaterial="Leather";
		System.out.println("The strap material is "+w13.strapMaterial);
		w13.isWaterResistant=false;
		System.out.println("Water resistant: "+w13.isWaterResistant);
		w13.size="Medium";
		System.out.println("The size is "+w13.size);

		Watch w14 = new Watch();
		w14.brand="Daniel Klein";
		System.out.println("The brand is "+w14.brand);
		w14.cost=3500;
		System.out.println("The cost is "+w14.cost);
		w14.colour="Black";
		System.out.println("The colour is "+w14.colour);
		w14.type="Analog";
		System.out.println("The type is "+w14.type);
		w14.displayType="Dial";
		System.out.println("The display type is "+w14.displayType);
		w14.strapMaterial="Leather";
		System.out.println("The strap material is "+w14.strapMaterial);
		w14.isWaterResistant=true;
		System.out.println("Water resistant: "+w14.isWaterResistant);
		w14.size="Medium";
		System.out.println("The size is "+w14.size);

		Watch w15 = new Watch();
		w15.brand="Guess";
		System.out.println("The brand is "+w15.brand);
		w15.cost=6000;
		System.out.println("The cost is "+w15.cost);
		w15.colour="Gold";
		System.out.println("The colour is "+w15.colour);
		w15.type="Analog";
		System.out.println("The type is "+w15.type);
		w15.displayType="Dial";
		System.out.println("The display type is "+w15.displayType);
		w15.strapMaterial="Metal";
		System.out.println("The strap material is "+w15.strapMaterial);
		w15.isWaterResistant=true;
		System.out.println("Water resistant: "+w15.isWaterResistant);
		w15.size="Large";
		System.out.println("The size is "+w15.size);

		Watch w16 = new Watch();
		w16.brand="Armani";
		System.out.println("The brand is "+w16.brand);
		w16.cost=12000;
		System.out.println("The cost is "+w16.cost);
		w16.colour="Black";
		System.out.println("The colour is "+w16.colour);
		w16.type="Analog";
		System.out.println("The type is "+w16.type);
		w16.displayType="Dial";
		System.out.println("The display type is "+w16.displayType);
		w16.strapMaterial="Leather";
		System.out.println("The strap material is "+w16.strapMaterial);
		w16.isWaterResistant=true;
		System.out.println("Water resistant: "+w16.isWaterResistant);
		w16.size="Large";
		System.out.println("The size is "+w16.size);

		Watch w17 = new Watch();
		w17.brand="Diesel";
		System.out.println("The brand is "+w17.brand);
		w17.cost=9000;
		System.out.println("The cost is "+w17.cost);
		w17.colour="Grey";
		System.out.println("The colour is "+w17.colour);
		w17.type="Analog";
		System.out.println("The type is "+w17.type);
		w17.displayType="Dial";
		System.out.println("The display type is "+w17.displayType);
		w17.strapMaterial="Metal";
		System.out.println("The strap material is "+w17.strapMaterial);
		w17.isWaterResistant=true;
		System.out.println("Water resistant: "+w17.isWaterResistant);
		w17.size="Large";
		System.out.println("The size is "+w17.size);

		Watch w18 = new Watch();
		w18.brand="Skagen";
		System.out.println("The brand is "+w18.brand);
		w18.cost=7500;
		System.out.println("The cost is "+w18.cost);
		w18.colour="Silver";
		System.out.println("The colour is "+w18.colour);
		w18.type="Analog";
		System.out.println("The type is "+w18.type);
		w18.displayType="Dial";
		System.out.println("The display type is "+w18.displayType);
		w18.strapMaterial="Metal";
		System.out.println("The strap material is "+w18.strapMaterial);
		w18.isWaterResistant=true;
		System.out.println("Water resistant: "+w18.isWaterResistant);
		w18.size="Medium";
		System.out.println("The size is "+w18.size);

		Watch w19 = new Watch();
		w19.brand="Police";
		System.out.println("The brand is "+w19.brand);
		w19.cost=5000;
		System.out.println("The cost is "+w19.cost);
		w19.colour="Black";
		System.out.println("The colour is "+w19.colour);
		w19.type="Analog";
		System.out.println("The type is "+w19.type);
		w19.displayType="Dial";
		System.out.println("The display type is "+w19.displayType);
		w19.strapMaterial="Leather";
		System.out.println("The strap material is "+w19.strapMaterial);
		w19.isWaterResistant=true;
		System.out.println("Water resistant: "+w19.isWaterResistant);
		w19.size="Large";
		System.out.println("The size is "+w19.size);

		Watch w20 = new Watch();
		w20.brand="Tommy Hilfiger";
		System.out.println("The brand is "+w20.brand);
		w20.cost=6500;
		System.out.println("The cost is "+w20.cost);
		w20.colour="Blue";
		System.out.println("The colour is "+w20.colour);
		w20.type="Analog";
		System.out.println("The type is "+w20.type);
		w20.displayType="Dial";
		System.out.println("The display type is "+w20.displayType);
		w20.strapMaterial="Leather";
		System.out.println("The strap material is "+w20.strapMaterial);
		w20.isWaterResistant=true;
		System.out.println("Water resistant: "+w20.isWaterResistant);
		w20.size="Medium";
		System.out.println("The size is "+w20.size);
				Watch w21 = new Watch();
		w21.brand="Boat Xtend";
		System.out.println("The brand is "+w21.brand);
		w21.cost=3000;
		System.out.println("The cost is "+w21.cost);
		w21.colour="Black";
		System.out.println("The colour is "+w21.colour);
		w21.type="Smart";
		System.out.println("The type is "+w21.type);
		w21.displayType="Touchscreen";
		System.out.println("The display type is "+w21.displayType);
		w21.strapMaterial="Silicone";
		System.out.println("The strap material is "+w21.strapMaterial);
		w21.isWaterResistant=true;
		System.out.println("Water resistant: "+w21.isWaterResistant);
		w21.size="Medium";
		System.out.println("The size is "+w21.size);

		Watch w22 = new Watch();
		w22.brand="Noise Colorfit";
		System.out.println("The brand is "+w22.brand);
		w22.cost=2800;
		System.out.println("The cost is "+w22.cost);
		w22.colour="Blue";
		System.out.println("The colour is "+w22.colour);
		w22.type="Smart";
		System.out.println("The type is "+w22.type);
		w22.displayType="Touchscreen";
		System.out.println("The display type is "+w22.displayType);
		w22.strapMaterial="Rubber";
		System.out.println("The strap material is "+w22.strapMaterial);
		w22.isWaterResistant=true;
		System.out.println("Water resistant: "+w22.isWaterResistant);
		w22.size="Large";
		System.out.println("The size is "+w22.size);

		Watch w23 = new Watch();
		w23.brand="FireBoltt Ninja";
		System.out.println("The brand is "+w23.brand);
		w23.cost=2600;
		System.out.println("The cost is "+w23.cost);
		w23.colour="Black";
		System.out.println("The colour is "+w23.colour);
		w23.type="Smart";
		System.out.println("The type is "+w23.type);
		w23.displayType="Touchscreen";
		System.out.println("The display type is "+w23.displayType);
		w23.strapMaterial="Rubber";
		System.out.println("The strap material is "+w23.strapMaterial);
		w23.isWaterResistant=true;
		System.out.println("Water resistant: "+w23.isWaterResistant);
		w23.size="Medium";
		System.out.println("The size is "+w23.size);

		Watch w24 = new Watch();
		w24.brand="Realme";
		System.out.println("The brand is "+w24.brand);
		w24.cost=3000;
		System.out.println("The cost is "+w24.cost);
		w24.colour="Grey";
		System.out.println("The colour is "+w24.colour);
		w24.type="Smart";
		System.out.println("The type is "+w24.type);
		w24.displayType="Touchscreen";
		System.out.println("The display type is "+w24.displayType);
		w24.strapMaterial="Silicone";
		System.out.println("The strap material is "+w24.strapMaterial);
		w24.isWaterResistant=true;
		System.out.println("Water resistant: "+w24.isWaterResistant);
		w24.size="Medium";
		System.out.println("The size is "+w24.size);

		Watch w25 = new Watch();
		w25.brand="Mi";
		System.out.println("The brand is "+w25.brand);
		w25.cost=2500;
		System.out.println("The cost is "+w25.cost);
		w25.colour="Black";
		System.out.println("The colour is "+w25.colour);
		w25.type="Smart";
		System.out.println("The type is "+w25.type);
		w25.displayType="Touchscreen";
		System.out.println("The display type is "+w25.displayType);
		w25.strapMaterial="Rubber";
		System.out.println("The strap material is "+w25.strapMaterial);
		w25.isWaterResistant=true;
		System.out.println("Water resistant: "+w25.isWaterResistant);
		w25.size="Medium";
		System.out.println("The size is "+w25.size);

		Watch w26 = new Watch();
		w26.brand="OnePlus";
		System.out.println("The brand is "+w26.brand);
		w26.cost=5000;
		System.out.println("The cost is "+w26.cost);
		w26.colour="Black";
		System.out.println("The colour is "+w26.colour);
		w26.type="Smart";
		System.out.println("The type is "+w26.type);
		w26.displayType="Touchscreen";
		System.out.println("The display type is "+w26.displayType);
		w26.strapMaterial="Silicone";
		System.out.println("The strap material is "+w26.strapMaterial);
		w26.isWaterResistant=true;
		System.out.println("Water resistant: "+w26.isWaterResistant);
		w26.size="Large";
		System.out.println("The size is "+w26.size);

		Watch w27 = new Watch();
		w27.brand="Apple";
		System.out.println("The brand is "+w27.brand);
		w27.cost=30000;
		System.out.println("The cost is "+w27.cost);
		w27.colour="Silver";
		System.out.println("The colour is "+w27.colour);
		w27.type="Smart";
		System.out.println("The type is "+w27.type);
		w27.displayType="Touchscreen";
		System.out.println("The display type is "+w27.displayType);
		w27.strapMaterial="Silicone";
		System.out.println("The strap material is "+w27.strapMaterial);
		w27.isWaterResistant=true;
		System.out.println("Water resistant: "+w27.isWaterResistant);
		w27.size="Large";
		System.out.println("The size is "+w27.size);

		Watch w28 = new Watch();
		w28.brand="Samsung";
		System.out.println("The brand is "+w28.brand);
		w28.cost=20000;
		System.out.println("The cost is "+w28.cost);
		w28.colour="Black";
		System.out.println("The colour is "+w28.colour);
		w28.type="Smart";
		System.out.println("The type is "+w28.type);
		w28.displayType="Touchscreen";
		System.out.println("The display type is "+w28.displayType);
		w28.strapMaterial="Rubber";
		System.out.println("The strap material is "+w28.strapMaterial);
		w28.isWaterResistant=true;
		System.out.println("Water resistant: "+w28.isWaterResistant);
		w28.size="Large";
		System.out.println("The size is "+w28.size);

		Watch w29 = new Watch();
		w29.brand="Garmin";
		System.out.println("The brand is "+w29.brand);
		w29.cost=25000;
		System.out.println("The cost is "+w29.cost);
		w29.colour="Black";
		System.out.println("The colour is "+w29.colour);
		w29.type="Sports";
		System.out.println("The type is "+w29.type);
		w29.displayType="Digital";
		System.out.println("The display type is "+w29.displayType);
		w29.strapMaterial="Rubber";
		System.out.println("The strap material is "+w29.strapMaterial);
		w29.isWaterResistant=true;
		System.out.println("Water resistant: "+w29.isWaterResistant);
		w29.size="Large";
		System.out.println("The size is "+w29.size);

		Watch w30 = new Watch();
		w30.brand="Casio GShock";
		System.out.println("The brand is "+w30.brand);
		w30.cost=8000;
		System.out.println("The cost is "+w30.cost);
		w30.colour="Black";
		System.out.println("The colour is "+w30.colour);
		w30.type="Digital";
		System.out.println("The type is "+w30.type);
		w30.displayType="LED";
		System.out.println("The display type is "+w30.displayType);
		w30.strapMaterial="Rubber";
		System.out.println("The strap material is "+w30.strapMaterial);
		w30.isWaterResistant=true;
		System.out.println("Water resistant: "+w30.isWaterResistant);
		w30.size="Large";
		System.out.println("The size is "+w30.size);
	}
}