class BigBasketExec
{
	public static void main(String ref[])
	{
		double price;

		price = BigBasket.search("mobile", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("laptop", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("tablet", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("smart watch", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("earphones", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("headphones", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("bluetooth speaker", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("television", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("refrigerator", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("washing machine", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("air conditioner", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("microwave", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("induction stove", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("electric kettle", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("mixer grinder", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("juicer", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("water purifier", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("geyser", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("ceiling fan", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("table fan", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("air cooler", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("iron box", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("hair dryer", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("trimmer", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("camera", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("printer", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("scanner", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("router", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("modem", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("keyboard", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("mouse", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("monitor", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("cpu", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("ups", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("power bank", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("charger", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("usb cable", 3);
		System.out.println("The price is " + price);
		price = BigBasket.search("hard disk", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("pen drive", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("memory card", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("smart bulb", 3);
		System.out.println("The price is " + price);
		price = BigBasket.search("led bulb", 3);
		System.out.println("The price is " + price);
		price = BigBasket.search("tube light", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("extension board", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("inverter", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("stabilizer", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("projector", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("gaming console", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("vr headset", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("smart door lock", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("cctv camera", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("door bell", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("vacuum cleaner", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("dishwasher", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("electric scooter", 1);
		System.out.println("The price is " + price);
		price = BigBasket.search("fitness band", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("digital clock", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("alarm clock", 2);
		System.out.println("The price is " + price);
		price = BigBasket.search("calculator", 2);
		System.out.println("The price is " + price);
	}
}